{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"syncIfNeededWith"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"mode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthMode","preciseIdentifier":"c:@M@WomenHealth@E@WomenHealthMode","text":"WomenHealthMode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"recentMenstrualBegin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"menstrualDuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"menstrualCycle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"advanceDaysToRemind"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"hoursInDayForRemind"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"remindAtWatch"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"pregnancyRemindType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/PregnancyRemindType","preciseIdentifier":"c:@M@WomenHealth@E@PregnancyRemindType","text":"PregnancyRemindType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"menstrualDurationWhenManualBehaviorExist"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"userId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"用户Id"}]}]},{"name":"mode","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"当前女性健康模式"}]}]},{"name":"recentMenstrualBegin","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"最近一次月经开始日期"}]}]},{"name":"menstrualDuration","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"经期长度"}]}]},{"name":"menstrualCycle","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"周期长度"}]}]},{"name":"advanceDaysToRemind","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"提前几天提醒"}]}]},{"name":"hoursInDayForRemind","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"几点提醒"}]}]},{"name":"remindAtWatch","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"是否在手表上提醒"}]}]},{"name":"pregnancyRemindType","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"怀孕期提醒方式"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/womenhealth\/smartwatchsyncable\/syncifneededwith(_:_:_:_:_:_:_:_:_:_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/womenhealth\/smartwatchsyncable\/syncifneededwith(_:_:_:_:_:_:_:_:_:_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/SmartWatchSyncable\/syncIfNeededWith(_:_:_:_:_:_:_:_:_:_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"如果需要则同步女性健康配置给手表"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"syncIfNeededWith::::::::::"}],"role":"symbol","title":"syncIfNeededWith(_:_:_:_:_:_:_:_:_:_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"syncIfNeededWith"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"WomenHealthMode","preciseIdentifier":"c:@M@WomenHealth@E@WomenHealthMode"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"PregnancyRemindType","preciseIdentifier":"c:@M@WomenHealth@E@PregnancyRemindType"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@M@WomenHealth@objc(pl)SmartWatchSyncable(im)syncIfNeededWith::::::::::","required":true,"modules":[{"name":"WomenHealth"}]},"hierarchy":{"paths":[["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/SmartWatchSyncable"]]},"references":{"doc://com.topstep.WomenHealth/documentation/WomenHealth/WomenHealthMode":{"role":"symbol","title":"WomenHealthMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"WomenHealthMode"}],"abstract":[{"type":"text","text":"女性健康模式"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WomenHealthMode"}],"url":"\/documentation\/womenhealth\/womenhealthmode"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/SmartWatchSyncable/syncIfNeededWith(_:_:_:_:_:_:_:_:_:_:)":{"navigatorTitle":[{"kind":"identifier","text":"syncIfNeededWith::::::::::"}],"role":"symbol","title":"syncIfNeededWith(_:_:_:_:_:_:_:_:_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"syncIfNeededWith"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"WomenHealthMode","preciseIdentifier":"c:@M@WomenHealth@E@WomenHealthMode"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"PregnancyRemindType","preciseIdentifier":"c:@M@WomenHealth@E@PregnancyRemindType"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"如果需要则同步女性健康配置给手表"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/SmartWatchSyncable\/syncIfNeededWith(_:_:_:_:_:_:_:_:_:_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/womenhealth\/smartwatchsyncable\/syncifneededwith(_:_:_:_:_:_:_:_:_:_:)"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/PregnancyRemindType":{"role":"symbol","title":"PregnancyRemindType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PregnancyRemindType"}],"abstract":[{"type":"text","text":"怀孕期提醒方式"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/PregnancyRemindType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PregnancyRemindType"}],"url":"\/documentation\/womenhealth\/pregnancyremindtype"},"doc://com.topstep.WomenHealth/documentation/WomenHealth":{"role":"collection","title":"WomenHealth","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","kind":"symbol","type":"topic","url":"\/documentation\/womenhealth"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/SmartWatchSyncable":{"role":"symbol","title":"SmartWatchSyncable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SmartWatchSyncable"}],"abstract":[{"type":"text","text":"智能手表同步协议"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/SmartWatchSyncable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SmartWatchSyncable"}],"url":"\/documentation\/womenhealth\/smartwatchsyncable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"syncIfNeededWith::::::::::"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"syncIfNeededWith::::::::::"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"syncIfNeededWith:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"userId"},{"kind":"text","text":" "},{"kind":"identifier","text":":"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthMode","preciseIdentifier":"c:@M@WomenHealth@E@WomenHealthMode","text":"WomenHealthMode"},{"kind":"text","text":") "},{"kind":"internalParam","text":"mode"},{"kind":"text","text":" "},{"kind":"identifier","text":":"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSDate","preciseIdentifier":"c:objc(cs)NSDate"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"recentMenstrualBegin"},{"kind":"text","text":" "},{"kind":"identifier","text":":"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"menstrualDuration"},{"kind":"text","text":" "},{"kind":"identifier","text":":"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"menstrualCycle"},{"kind":"text","text":" "},{"kind":"identifier","text":":"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"advanceDaysToRemind"},{"kind":"text","text":" "},{"kind":"identifier","text":":"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"hoursInDayForRemind"},{"kind":"text","text":" "},{"kind":"identifier","text":":"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"remindAtWatch"},{"kind":"text","text":" "},{"kind":"identifier","text":":"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/PregnancyRemindType","preciseIdentifier":"c:@M@WomenHealth@E@PregnancyRemindType","text":"PregnancyRemindType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"pregnancyRemindType"},{"kind":"text","text":" "},{"kind":"identifier","text":":"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"menstrualDurationWhenManualBehaviorExist"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthMode\/title","value":"WomenHealthMode"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthMode\/fragments","value":[{"kind":"identifier","text":"WomenHealthMode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1SmartWatchSyncable~1syncIfNeededWith(_:_:_:_:_:_:_:_:_:_:)\/title","value":"syncIfNeededWith::::::::::"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1SmartWatchSyncable~1syncIfNeededWith(_:_:_:_:_:_:_:_:_:_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"syncIfNeededWith::::::::::"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1PregnancyRemindType\/title","value":"PregnancyRemindType"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1PregnancyRemindType\/fragments","value":[{"kind":"identifier","text":"PregnancyRemindType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1SmartWatchSyncable\/title","value":"SmartWatchSyncable"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1SmartWatchSyncable\/fragments","value":[{"kind":"identifier","text":"SmartWatchSyncable"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}