{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"withFeatureOnWatch"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"手表是否支持女性健康功能"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/womenhealth\/smartwatchsyncable\/withfeatureonwatch()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/womenhealth\/smartwatchsyncable\/withfeatureonwatch()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/SmartWatchSyncable\/withFeatureOnWatch()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"手表是否支持女性健康功能"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"withFeatureOnWatch"}],"role":"symbol","title":"withFeatureOnWatch()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"withFeatureOnWatch"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"symbolKind":"method","externalID":"c:@M@WomenHealth@objc(pl)SmartWatchSyncable(im)withFeatureOnWatch","required":true,"modules":[{"name":"WomenHealth"}]},"hierarchy":{"paths":[["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/SmartWatchSyncable"]]},"references":{"doc://com.topstep.WomenHealth/documentation/WomenHealth":{"role":"collection","title":"WomenHealth","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","kind":"symbol","type":"topic","url":"\/documentation\/womenhealth"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/SmartWatchSyncable/withFeatureOnWatch()":{"navigatorTitle":[{"kind":"identifier","text":"withFeatureOnWatch"}],"role":"symbol","title":"withFeatureOnWatch()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"withFeatureOnWatch"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"手表是否支持女性健康功能"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/SmartWatchSyncable\/withFeatureOnWatch()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/womenhealth\/smartwatchsyncable\/withfeatureonwatch()"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/SmartWatchSyncable":{"role":"symbol","title":"SmartWatchSyncable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SmartWatchSyncable"}],"abstract":[{"type":"text","text":"智能手表同步协议"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/SmartWatchSyncable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SmartWatchSyncable"}],"url":"\/documentation\/womenhealth\/smartwatchsyncable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"withFeatureOnWatch"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"withFeatureOnWatch"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"withFeatureOnWatch"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1SmartWatchSyncable~1withFeatureOnWatch()\/title","value":"withFeatureOnWatch"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1SmartWatchSyncable~1withFeatureOnWatch()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"withFeatureOnWatch"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1SmartWatchSyncable\/title","value":"SmartWatchSyncable"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1SmartWatchSyncable\/fragments","value":[{"kind":"identifier","text":"SmartWatchSyncable"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}