{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"menses"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/womenhealth\/womenhealthphase\/menses"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/womenhealth\/womenhealthphase\/menses"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthPhase\/menses","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"月经期"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"WomenHealthPhaseMenses"}],"role":"symbol","title":"WomenHealthPhase.menses","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"menses"}],"symbolKind":"case","externalID":"c:@M@WomenHealth@E@WomenHealthPhase@WomenHealthPhaseMenses","modules":[{"name":"WomenHealth"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"11.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthPhase"]]},"references":{"doc://com.topstep.WomenHealth/documentation/WomenHealth/WomenHealthPhase":{"role":"symbol","title":"WomenHealthPhase","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"WomenHealthPhase"}],"abstract":[{"type":"text","text":"女性健康阶段"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthPhase","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WomenHealthPhase"}],"url":"\/documentation\/womenhealth\/womenhealthphase"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/WomenHealthPhase/menses":{"role":"symbol","title":"WomenHealthPhase.menses","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"menses"}],"abstract":[{"type":"text","text":"月经期"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthPhase\/menses","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WomenHealthPhaseMenses"}],"url":"\/documentation\/womenhealth\/womenhealthphase\/menses"},"doc://com.topstep.WomenHealth/documentation/WomenHealth":{"role":"collection","title":"WomenHealth","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","kind":"symbol","type":"topic","url":"\/documentation\/womenhealth"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"WomenHealthPhaseMenses"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"WomenHealthPhaseMenses"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"WomenHealthPhaseMenses"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthPhase\/title","value":"WomenHealthPhase"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthPhase\/fragments","value":[{"kind":"identifier","text":"WomenHealthPhase"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthPhase~1menses\/title","value":"WomenHealthPhaseMenses"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthPhase~1menses\/fragments","value":[{"kind":"identifier","text":"WomenHealthPhaseMenses"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}