{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"safty"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/womenhealth\/womenhealthphase\/safty"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/womenhealth\/womenhealthphase\/safty"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthPhase\/safty","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"安全期"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"WomenHealthPhaseSafty"}],"role":"symbol","title":"WomenHealthPhase.safty","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"safty"}],"symbolKind":"case","externalID":"c:@M@WomenHealth@E@WomenHealthPhase@WomenHealthPhaseSafty","modules":[{"name":"WomenHealth"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"11.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthPhase"]]},"references":{"doc://com.topstep.WomenHealth/documentation/WomenHealth/WomenHealthPhase/safty":{"role":"symbol","title":"WomenHealthPhase.safty","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"safty"}],"abstract":[{"type":"text","text":"安全期"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthPhase\/safty","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WomenHealthPhaseSafty"}],"url":"\/documentation\/womenhealth\/womenhealthphase\/safty"},"doc://com.topstep.WomenHealth/documentation/WomenHealth":{"role":"collection","title":"WomenHealth","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","kind":"symbol","type":"topic","url":"\/documentation\/womenhealth"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/WomenHealthPhase":{"role":"symbol","title":"WomenHealthPhase","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"WomenHealthPhase"}],"abstract":[{"type":"text","text":"女性健康阶段"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthPhase","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WomenHealthPhase"}],"url":"\/documentation\/womenhealth\/womenhealthphase"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"WomenHealthPhaseSafty"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"WomenHealthPhaseSafty"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"WomenHealthPhaseSafty"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthPhase~1safty\/title","value":"WomenHealthPhaseSafty"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthPhase~1safty\/fragments","value":[{"kind":"identifier","text":"WomenHealthPhaseSafty"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthPhase\/title","value":"WomenHealthPhase"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthPhase\/fragments","value":[{"kind":"identifier","text":"WomenHealthPhase"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}