{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChangeModeConfirmMessageFormat"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/womenhealth\/localizationkey\/changemodeconfirmmessageformat"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/womenhealth\/localizationkey\/changemodeconfirmmessageformat"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/ChangeModeConfirmMessageFormat","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"当前处于%@，是否开始%@?"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChangeModeConfirmMessageFormat"}],"title":"LocalizationKey.ChangeModeConfirmMessageFormat","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@WomenHealth@E@LocalizationKey@LocalizationKeyChangeModeConfirmMessageFormat","modules":[{"name":"WomenHealth"}],"navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyChangeModeConfirmMessageFormat"}]},"hierarchy":{"paths":[["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey"]]},"references":{"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/ChangeModeConfirmMessageFormat":{"role":"symbol","title":"LocalizationKey.ChangeModeConfirmMessageFormat","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChangeModeConfirmMessageFormat"}],"abstract":[{"type":"text","text":"当前处于%@，是否开始%@?"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/ChangeModeConfirmMessageFormat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyChangeModeConfirmMessageFormat"}],"url":"\/documentation\/womenhealth\/localizationkey\/changemodeconfirmmessageformat"},"doc://com.topstep.WomenHealth/documentation/WomenHealth":{"role":"collection","title":"WomenHealth","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","kind":"symbol","type":"topic","url":"\/documentation\/womenhealth"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey":{"role":"symbol","title":"LocalizationKey","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocalizationKey"}],"abstract":[{"type":"text","text":"国际化Key定义"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKey"}],"url":"\/documentation\/womenhealth\/localizationkey"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"LocalizationKeyChangeModeConfirmMessageFormat"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyChangeModeConfirmMessageFormat"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"LocalizationKeyChangeModeConfirmMessageFormat"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1ChangeModeConfirmMessageFormat\/title","value":"LocalizationKeyChangeModeConfirmMessageFormat"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1ChangeModeConfirmMessageFormat\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyChangeModeConfirmMessageFormat"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey\/title","value":"LocalizationKey"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey\/fragments","value":[{"kind":"identifier","text":"LocalizationKey"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}