{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"DaysToEDCFormat"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/womenhealth\/localizationkey\/daystoedcformat"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/womenhealth\/localizationkey\/daystoedcformat"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/DaysToEDCFormat","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"距离预产期还有多少天格式，例如：距离预产期还有%@天"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"DaysToEDCFormat"}],"title":"LocalizationKey.DaysToEDCFormat","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@WomenHealth@E@LocalizationKey@LocalizationKeyDaysToEDCFormat","modules":[{"name":"WomenHealth"}],"navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyDaysToEDCFormat"}]},"hierarchy":{"paths":[["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey"]]},"references":{"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/DaysToEDCFormat":{"role":"symbol","title":"LocalizationKey.DaysToEDCFormat","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"DaysToEDCFormat"}],"abstract":[{"type":"text","text":"距离预产期还有多少天格式，例如：距离预产期还有%@天"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/DaysToEDCFormat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyDaysToEDCFormat"}],"url":"\/documentation\/womenhealth\/localizationkey\/daystoedcformat"},"doc://com.topstep.WomenHealth/documentation/WomenHealth":{"role":"collection","title":"WomenHealth","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","kind":"symbol","type":"topic","url":"\/documentation\/womenhealth"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey":{"role":"symbol","title":"LocalizationKey","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocalizationKey"}],"abstract":[{"type":"text","text":"国际化Key定义"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKey"}],"url":"\/documentation\/womenhealth\/localizationkey"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"LocalizationKeyDaysToEDCFormat"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyDaysToEDCFormat"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"LocalizationKeyDaysToEDCFormat"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1DaysToEDCFormat\/title","value":"LocalizationKeyDaysToEDCFormat"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1DaysToEDCFormat\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyDaysToEDCFormat"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey\/title","value":"LocalizationKey"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey\/fragments","value":[{"kind":"identifier","text":"LocalizationKey"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}