{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"MensesModeSettingsTitle"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/womenhealth\/localizationkey\/mensesmodesettingstitle"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/womenhealth\/localizationkey\/mensesmodesettingstitle"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/MensesModeSettingsTitle","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"经期设置"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"MensesModeSettingsTitle"}],"title":"LocalizationKey.MensesModeSettingsTitle","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@WomenHealth@E@LocalizationKey@LocalizationKeyMensesModeSettingsTitle","modules":[{"name":"WomenHealth"}],"navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyMensesModeSettingsTitle"}]},"hierarchy":{"paths":[["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey"]]},"references":{"doc://com.topstep.WomenHealth/documentation/WomenHealth":{"role":"collection","title":"WomenHealth","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","kind":"symbol","type":"topic","url":"\/documentation\/womenhealth"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey":{"role":"symbol","title":"LocalizationKey","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocalizationKey"}],"abstract":[{"type":"text","text":"国际化Key定义"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKey"}],"url":"\/documentation\/womenhealth\/localizationkey"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/MensesModeSettingsTitle":{"role":"symbol","title":"LocalizationKey.MensesModeSettingsTitle","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"MensesModeSettingsTitle"}],"abstract":[{"type":"text","text":"经期设置"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/MensesModeSettingsTitle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyMensesModeSettingsTitle"}],"url":"\/documentation\/womenhealth\/localizationkey\/mensesmodesettingstitle"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"LocalizationKeyMensesModeSettingsTitle"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyMensesModeSettingsTitle"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"LocalizationKeyMensesModeSettingsTitle"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey\/title","value":"LocalizationKey"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey\/fragments","value":[{"kind":"identifier","text":"LocalizationKey"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1MensesModeSettingsTitle\/title","value":"LocalizationKeyMensesModeSettingsTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1MensesModeSettingsTitle\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyMensesModeSettingsTitle"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}