{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"MenstrualCycleQuestion"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/womenhealth\/localizationkey\/menstrualcyclequestion"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/womenhealth\/localizationkey\/menstrualcyclequestion"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/MenstrualCycleQuestion","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"两次月经开始日大概间隔多久？"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"MenstrualCycleQuestion"}],"title":"LocalizationKey.MenstrualCycleQuestion","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@WomenHealth@E@LocalizationKey@LocalizationKeyMenstrualCycleQuestion","modules":[{"name":"WomenHealth"}],"navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyMenstrualCycleQuestion"}]},"hierarchy":{"paths":[["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey"]]},"references":{"doc://com.topstep.WomenHealth/documentation/WomenHealth":{"role":"collection","title":"WomenHealth","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","kind":"symbol","type":"topic","url":"\/documentation\/womenhealth"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/MenstrualCycleQuestion":{"role":"symbol","title":"LocalizationKey.MenstrualCycleQuestion","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"MenstrualCycleQuestion"}],"abstract":[{"type":"text","text":"两次月经开始日大概间隔多久？"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/MenstrualCycleQuestion","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyMenstrualCycleQuestion"}],"url":"\/documentation\/womenhealth\/localizationkey\/menstrualcyclequestion"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey":{"role":"symbol","title":"LocalizationKey","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocalizationKey"}],"abstract":[{"type":"text","text":"国际化Key定义"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKey"}],"url":"\/documentation\/womenhealth\/localizationkey"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"LocalizationKeyMenstrualCycleQuestion"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyMenstrualCycleQuestion"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"LocalizationKeyMenstrualCycleQuestion"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1MenstrualCycleQuestion\/title","value":"LocalizationKeyMenstrualCycleQuestion"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1MenstrualCycleQuestion\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyMenstrualCycleQuestion"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey\/title","value":"LocalizationKey"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey\/fragments","value":[{"kind":"identifier","text":"LocalizationKey"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}