{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"feature_disabled"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/womenhealth\/menstrualbehaviordate\/feature_disabled"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/womenhealth\/menstrualbehaviordate\/feature_disabled"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorDate\/feature_disabled","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"女性健康未启用"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"MenstrualBehaviorDateFeature_disabled"}],"role":"symbol","title":"MenstrualBehaviorDate.feature_disabled","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"feature_disabled"}],"symbolKind":"case","externalID":"c:@M@WomenHealth@E@MenstrualBehaviorDate@MenstrualBehaviorDateFeature_disabled","modules":[{"name":"WomenHealth"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"11.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorDate"]]},"references":{"doc://com.topstep.WomenHealth/documentation/WomenHealth":{"role":"collection","title":"WomenHealth","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","kind":"symbol","type":"topic","url":"\/documentation\/womenhealth"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/MenstrualBehaviorDate/feature_disabled":{"role":"symbol","title":"MenstrualBehaviorDate.feature_disabled","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"feature_disabled"}],"abstract":[{"type":"text","text":"女性健康未启用"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorDate\/feature_disabled","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MenstrualBehaviorDateFeature_disabled"}],"url":"\/documentation\/womenhealth\/menstrualbehaviordate\/feature_disabled"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/MenstrualBehaviorDate":{"role":"symbol","title":"MenstrualBehaviorDate","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MenstrualBehaviorDate"}],"abstract":[{"type":"text","text":"经期人为操作类型"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorDate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MenstrualBehaviorDate"}],"url":"\/documentation\/womenhealth\/menstrualbehaviordate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MenstrualBehaviorDateFeature_disabled"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MenstrualBehaviorDateFeature_disabled"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"MenstrualBehaviorDateFeature_disabled"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1MenstrualBehaviorDate~1feature_disabled\/title","value":"MenstrualBehaviorDateFeature_disabled"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1MenstrualBehaviorDate~1feature_disabled\/fragments","value":[{"kind":"identifier","text":"MenstrualBehaviorDateFeature_disabled"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1MenstrualBehaviorDate\/title","value":"MenstrualBehaviorDate"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1MenstrualBehaviorDate\/fragments","value":[{"kind":"identifier","text":"MenstrualBehaviorDate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}