{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"menstrual_begin"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/womenhealth\/menstrualbehaviordate\/menstrual_begin"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/womenhealth\/menstrualbehaviordate\/menstrual_begin"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorDate\/menstrual_begin","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"经期开始当天"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"MenstrualBehaviorDateMenstrual_begin"}],"role":"symbol","title":"MenstrualBehaviorDate.menstrual_begin","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"menstrual_begin"}],"symbolKind":"case","externalID":"c:@M@WomenHealth@E@MenstrualBehaviorDate@MenstrualBehaviorDateMenstrual_begin","modules":[{"name":"WomenHealth"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"11.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorDate"]]},"references":{"doc://com.topstep.WomenHealth/documentation/WomenHealth":{"role":"collection","title":"WomenHealth","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","kind":"symbol","type":"topic","url":"\/documentation\/womenhealth"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/MenstrualBehaviorDate/menstrual_begin":{"role":"symbol","title":"MenstrualBehaviorDate.menstrual_begin","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"menstrual_begin"}],"abstract":[{"type":"text","text":"经期开始当天"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorDate\/menstrual_begin","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MenstrualBehaviorDateMenstrual_begin"}],"url":"\/documentation\/womenhealth\/menstrualbehaviordate\/menstrual_begin"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/MenstrualBehaviorDate":{"role":"symbol","title":"MenstrualBehaviorDate","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MenstrualBehaviorDate"}],"abstract":[{"type":"text","text":"经期人为操作类型"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorDate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MenstrualBehaviorDate"}],"url":"\/documentation\/womenhealth\/menstrualbehaviordate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MenstrualBehaviorDateMenstrual_begin"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MenstrualBehaviorDateMenstrual_begin"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"MenstrualBehaviorDateMenstrual_begin"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1MenstrualBehaviorDate~1menstrual_begin\/title","value":"MenstrualBehaviorDateMenstrual_begin"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1MenstrualBehaviorDate~1menstrual_begin\/fragments","value":[{"kind":"identifier","text":"MenstrualBehaviorDateMenstrual_begin"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1MenstrualBehaviorDate\/title","value":"MenstrualBehaviorDate"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1MenstrualBehaviorDate\/fragments","value":[{"kind":"identifier","text":"MenstrualBehaviorDate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}