{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mode_not_match"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/womenhealth\/menstrualbehaviordate\/mode_not_match"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/womenhealth\/menstrualbehaviordate\/mode_not_match"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorDate\/mode_not_match","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"女性健康模式不匹配，当前为怀孕期"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"MenstrualBehaviorDateMode_not_match"}],"role":"symbol","title":"MenstrualBehaviorDate.mode_not_match","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mode_not_match"}],"symbolKind":"case","externalID":"c:@M@WomenHealth@E@MenstrualBehaviorDate@MenstrualBehaviorDateMode_not_match","modules":[{"name":"WomenHealth"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"11.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorDate"]]},"references":{"doc://com.topstep.WomenHealth/documentation/WomenHealth":{"role":"collection","title":"WomenHealth","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","kind":"symbol","type":"topic","url":"\/documentation\/womenhealth"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/MenstrualBehaviorDate/mode_not_match":{"role":"symbol","title":"MenstrualBehaviorDate.mode_not_match","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mode_not_match"}],"abstract":[{"type":"text","text":"女性健康模式不匹配，当前为怀孕期"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorDate\/mode_not_match","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MenstrualBehaviorDateMode_not_match"}],"url":"\/documentation\/womenhealth\/menstrualbehaviordate\/mode_not_match"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/MenstrualBehaviorDate":{"role":"symbol","title":"MenstrualBehaviorDate","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MenstrualBehaviorDate"}],"abstract":[{"type":"text","text":"经期人为操作类型"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorDate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MenstrualBehaviorDate"}],"url":"\/documentation\/womenhealth\/menstrualbehaviordate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MenstrualBehaviorDateMode_not_match"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MenstrualBehaviorDateMode_not_match"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"MenstrualBehaviorDateMode_not_match"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1MenstrualBehaviorDate~1mode_not_match\/title","value":"MenstrualBehaviorDateMode_not_match"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1MenstrualBehaviorDate~1mode_not_match\/fragments","value":[{"kind":"identifier","text":"MenstrualBehaviorDateMode_not_match"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1MenstrualBehaviorDate\/title","value":"MenstrualBehaviorDate"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1MenstrualBehaviorDate\/fragments","value":[{"kind":"identifier","text":"MenstrualBehaviorDate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}