{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/womenhealth"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/womenhealth"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","interfaceLanguage":"swift"},"topicSections":[{"title":"Classes","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthModule","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthNotifications"]},{"title":"Protocols","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/Localizable","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/Loggable","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/SmartWatchSyncable","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/Themable"]},{"title":"Enumerations","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LogLevel","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorDate","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorType","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/PregnancyRemindType","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthMode","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthPhase"]}],"kind":"symbol","metadata":{"roleHeading":"Framework","externalID":"WomenHealth","title":"WomenHealth","symbolKind":"module","role":"collection","modules":[{"name":"WomenHealth"}]},"hierarchy":{"paths":[[]]},"references":{"doc://com.topstep.WomenHealth/documentation/WomenHealth/Loggable":{"role":"symbol","title":"Loggable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Loggable"}],"abstract":[{"type":"text","text":"日志协议"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/Loggable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Loggable"}],"url":"\/documentation\/womenhealth\/loggable"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/WomenHealthNotifications":{"role":"symbol","title":"WomenHealthNotifications","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WomenHealthNotifications"}],"abstract":[{"type":"text","text":"女性健康模块通知"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthNotifications","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WomenHealthNotifications"}],"url":"\/documentation\/womenhealth\/womenhealthnotifications"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/WomenHealthVersionNumber":{"role":"symbol","title":"WomenHealthVersionNumber","fragments":[{"kind":"identifier","text":"WomenHealthVersionNumber"}],"abstract":[{"type":"text","text":"Project version number for WomenHealth."}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthVersionNumber","kind":"symbol","type":"topic","url":"\/documentation\/womenhealth\/womenhealthversionnumber"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/Localizable":{"role":"symbol","title":"Localizable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Localizable"}],"abstract":[{"type":"text","text":"国际化协议"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/Localizable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Localizable"}],"url":"\/documentation\/womenhealth\/localizable"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/WomenHealthModule":{"role":"symbol","title":"WomenHealthModule","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WomenHealthModule"}],"abstract":[{"type":"text","text":"女性健康模块"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthModule","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WomenHealthModule"}],"url":"\/documentation\/womenhealth\/womenhealthmodule"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/ThemeImageKey":{"role":"symbol","title":"ThemeImageKey","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThemeImageKey"}],"abstract":[{"type":"text","text":"图片Key定义"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThemeImageKey"}],"url":"\/documentation\/womenhealth\/themeimagekey"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/PregnancyRemindType":{"role":"symbol","title":"PregnancyRemindType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PregnancyRemindType"}],"abstract":[{"type":"text","text":"怀孕期提醒方式"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/PregnancyRemindType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PregnancyRemindType"}],"url":"\/documentation\/womenhealth\/pregnancyremindtype"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey":{"role":"symbol","title":"LocalizationKey","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocalizationKey"}],"abstract":[{"type":"text","text":"国际化Key定义"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKey"}],"url":"\/documentation\/womenhealth\/localizationkey"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/WomenHealthMode":{"role":"symbol","title":"WomenHealthMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"WomenHealthMode"}],"abstract":[{"type":"text","text":"女性健康模式"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WomenHealthMode"}],"url":"\/documentation\/womenhealth\/womenhealthmode"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/WomenHealthPhase":{"role":"symbol","title":"WomenHealthPhase","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"WomenHealthPhase"}],"abstract":[{"type":"text","text":"女性健康阶段"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthPhase","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WomenHealthPhase"}],"url":"\/documentation\/womenhealth\/womenhealthphase"},"doc://com.topstep.WomenHealth/documentation/WomenHealth":{"role":"collection","title":"WomenHealth","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","kind":"symbol","type":"topic","url":"\/documentation\/womenhealth"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/ThemeColorKey":{"role":"symbol","title":"ThemeColorKey","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThemeColorKey"}],"abstract":[{"type":"text","text":"颜色Key定义"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThemeColorKey"}],"url":"\/documentation\/womenhealth\/themecolorkey"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/MenstrualBehaviorDate":{"role":"symbol","title":"MenstrualBehaviorDate","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MenstrualBehaviorDate"}],"abstract":[{"type":"text","text":"经期人为操作类型"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorDate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MenstrualBehaviorDate"}],"url":"\/documentation\/womenhealth\/menstrualbehaviordate"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LogLevel":{"role":"symbol","title":"LogLevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogLevel"}],"abstract":[{"type":"text","text":"The log level"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LogLevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LogLevel"}],"url":"\/documentation\/womenhealth\/loglevel"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/MenstrualBehaviorType":{"role":"symbol","title":"MenstrualBehaviorType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MenstrualBehaviorType"}],"abstract":[{"type":"text","text":"经期人为操作类型"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MenstrualBehaviorType"}],"url":"\/documentation\/womenhealth\/menstrualbehaviortype"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/SmartWatchSyncable":{"role":"symbol","title":"SmartWatchSyncable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SmartWatchSyncable"}],"abstract":[{"type":"text","text":"智能手表同步协议"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/SmartWatchSyncable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SmartWatchSyncable"}],"url":"\/documentation\/womenhealth\/smartwatchsyncable"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/Themable":{"role":"symbol","title":"Themable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Themable"}],"abstract":[{"type":"text","text":"皮肤协议"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/Themable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Themable"}],"url":"\/documentation\/womenhealth\/themable"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/WomenHealthVersionString":{"role":"symbol","title":"WomenHealthVersionString","fragments":[{"kind":"identifier","text":"WomenHealthVersionString"}],"abstract":[{"type":"text","text":"Project version string for WomenHealth."}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthVersionString","kind":"symbol","type":"topic","url":"\/documentation\/womenhealth\/womenhealthversionstring"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Classes","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthModule","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthNotifications"]},{"title":"Protocols","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/Localizable","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/Loggable","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/SmartWatchSyncable","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/Themable"]},{"title":"Variables","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthVersionNumber","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthVersionString"]},{"title":"Enumerations","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LogLevel","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorDate","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorType","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/PregnancyRemindType","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthMode","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthPhase"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1Loggable\/title","value":"Loggable"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1Loggable\/fragments","value":[{"kind":"identifier","text":"Loggable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthNotifications\/title","value":"WomenHealthNotifications"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthNotifications\/fragments","value":[{"kind":"identifier","text":"WomenHealthNotifications"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1Localizable\/title","value":"Localizable"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1Localizable\/fragments","value":[{"kind":"identifier","text":"Localizable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthModule\/title","value":"WomenHealthModule"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthModule\/fragments","value":[{"kind":"identifier","text":"WomenHealthModule"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeImageKey\/title","value":"ThemeImageKey"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeImageKey\/fragments","value":[{"kind":"identifier","text":"ThemeImageKey"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1PregnancyRemindType\/title","value":"PregnancyRemindType"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1PregnancyRemindType\/fragments","value":[{"kind":"identifier","text":"PregnancyRemindType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey\/title","value":"LocalizationKey"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey\/fragments","value":[{"kind":"identifier","text":"LocalizationKey"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthMode\/title","value":"WomenHealthMode"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthMode\/fragments","value":[{"kind":"identifier","text":"WomenHealthMode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthPhase\/title","value":"WomenHealthPhase"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthPhase\/fragments","value":[{"kind":"identifier","text":"WomenHealthPhase"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeColorKey\/title","value":"ThemeColorKey"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeColorKey\/fragments","value":[{"kind":"identifier","text":"ThemeColorKey"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1MenstrualBehaviorDate\/title","value":"MenstrualBehaviorDate"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1MenstrualBehaviorDate\/fragments","value":[{"kind":"identifier","text":"MenstrualBehaviorDate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LogLevel\/title","value":"LogLevel"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LogLevel\/fragments","value":[{"kind":"identifier","text":"LogLevel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1MenstrualBehaviorType\/title","value":"MenstrualBehaviorType"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1MenstrualBehaviorType\/fragments","value":[{"kind":"identifier","text":"MenstrualBehaviorType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1SmartWatchSyncable\/title","value":"SmartWatchSyncable"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1SmartWatchSyncable\/fragments","value":[{"kind":"identifier","text":"SmartWatchSyncable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1Themable\/title","value":"Themable"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1Themable\/fragments","value":[{"kind":"identifier","text":"Themable"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}