# Uncomment this line to define a global platform for your project

# 忽略引入库的所有警告（强迫症者的福音啊）
inhibit_all_warnings!

target 'FitCloudDFUKitDemo' do
  platform :ios, '9.0'
  workspace 'FitCloudDFUKitDemo.xcworkspace'
  project 'FitCloudDFUKitDemo.xcodeproj'
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  #use_frameworks!

  # Pods for FitCloudKitDFUDemo
  pod 'FitCloudKit', git: 'https://github.com/htangsmart/FitCloudPro-SDK-iOS.git'
  pod 'FitCloudDFUKit', git: 'https://github.com/htangsmart/FitCloudPro-SDK-iOS.git'
end

