#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.2.3 effective-5.10 (swiftlang-6.2.3.3.21 clang-1700.6.3.2)
#ifndef FITCLOUDOTAGENKIT_SWIFT_H
#define FITCLOUDOTAGENKIT_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="FitCloudOTAGenKit",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

/// EPO文件类型
typedef SWIFT_ENUM(NSInteger, EPOFileType, open) {
/// 非法的类型
  EPOFileTypeInvalid = -1,
/// GPS, 美国的全球定位系统
  EPOFileTypeGPS = 0,
/// GLONASS, 俄罗斯的格洛纳斯卫星导航系统
  EPOFileTypeGLONASS = 1,
/// GALILEO, 欧盟的伽利略卫星导航系统
  EPOFileTypeGALILEO = 2,
/// BDS, 中国的北斗卫星导航系统
  EPOFileTypeBDS = 3,
/// IRNSS, 印度区域导航卫星系统
  EPOFileTypeIRNSS = 4,
/// QZSS, 日本卫星定位导航系统
  EPOFileTypeQZSS = 5,
};

/// OTA生成的平台
typedef SWIFT_ENUM(NSInteger, FitCloudOTAGenPlatform, open) {
/// 非法的平台
  FitCloudOTAGenPlatformInvalid = -1,
/// 瑞煜
  FitCloudOTAGenPlatformRealtek = 0,
/// Nordic
  FitCloudOTAGenPlatformNordic = 1,
/// 中科蓝讯
  FitCloudOTAGenPlatformBluetrum = 2,
};

/// OTA文件生成服务
SWIFT_CLASS("_TtC17FitCloudOTAGenKit21FitCloudOTAGenService")
@interface FitCloudOTAGenService : NSObject
/// 初始化
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSString;
@protocol Loggable;
@class ICOEEPOFile;
@interface FitCloudOTAGenService (SWIFT_EXTENSION(FitCloudOTAGenKit))
/// 生成GPS文件(Old)
/// <ul>
///   <li>
///     Parameters:
///   </li>
///   <li>
///     epoFilePaths: epo 文件路径列表，多个epo文件
///   </li>
///   <li>
///     outputDirectory: 输出目录，用于存放生成好的bin文件的地方
///   </li>
///   <li>
///     logProvider: 日志打印服务提供者
///   </li>
/// </ul>
///
/// returns:
/// 生成好的GPS文件路径
+ (NSString * _Nullable)createGpsEpoBin:(NSArray<NSString *> * _Nonnull)epoFilePaths :(NSString * _Nonnull)outputDirectory :(id <Loggable> _Nullable)logProvider error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
/// 生成芯与物GPS文件
/// <ul>
///   <li>
///     Parameters:
///   </li>
///   <li>
///     epoFiles: epo 文件列表，多个epo文件
///   </li>
///   <li>
///     outputDirectory: 输出目录，用于存放生成好的bin文件的地方
///   </li>
///   <li>
///     logProvider: 日志打印服务提供者
///   </li>
/// </ul>
///
/// returns:
/// 生成好的GPS文件路径
+ (NSString * _Nullable)createICOEGpsEpoBin:(enum FitCloudOTAGenPlatform)platform :(NSArray<ICOEEPOFile *> * _Nonnull)epoFiles :(NSString * _Nonnull)outputDirectory :(id <Loggable> _Nullable)logProvider error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
@end

@class NSCoder;
/// 芯与物EPO文件
SWIFT_CLASS("_TtC17FitCloudOTAGenKit11ICOEEPOFile")
@interface ICOEEPOFile : NSObject <NSSecureCoding>
@property (nonatomic) enum EPOFileType fileType;
@property (nonatomic, copy) NSString * _Nonnull filePath;
- (nonnull instancetype)initWithFileType:(enum EPOFileType)fileType filePath:(NSString * _Nonnull)filePath OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL supportsSecureCoding;)
+ (BOOL)supportsSecureCoding SWIFT_WARN_UNUSED_RESULT;
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// The log level
typedef SWIFT_ENUM_NAMED(NSInteger, FitCloudOTAGenKitLogLevel, "LogLevel", open) {
/// verbose
  FitCloudOTAGenKitLogLevelVerbose = 0,
/// debug
  FitCloudOTAGenKitLogLevelDebug = 1,
/// info
  FitCloudOTAGenKitLogLevelInfo = 2,
/// warning
  FitCloudOTAGenKitLogLevelWarning = 3,
/// error
  FitCloudOTAGenKitLogLevelError = 4,
};

/// 日志协议
SWIFT_PROTOCOL("_TtP17FitCloudOTAGenKit8Loggable_")
@protocol Loggable <NSObject>
/// 打印日志
/// \param logLevel 日志等级
///
/// \param message 日志信息
///
- (void)log:(enum FitCloudOTAGenKitLogLevel)logLevel :(NSString * _Nonnull)message;
@end

typedef SWIFT_ENUM(NSInteger, OTAGenError, open) {
/// 文件不存在
  OTAGenErrorFileNotExist = 0,
/// 芯片平台不支持
  OTAGenErrorPlatformNotSupport = 1,
/// 非法的OTA头数据
  OTAGenErrorBadPlatformOTAHeaderData = 2,
};
static NSString * _Nonnull const OTAGenErrorDomain = @"FitCloudOTAGenKit.OTAGenError";

/// OTA 镜像类型
typedef SWIFT_ENUM(NSInteger, OTAImageType, open) {
/// 非法的类型
  OTAImageTypeInvalid = -1,
/// patch 文件
  OTAImageTypePatch = 0,
/// 固件
  OTAImageTypeFirmware = 1,
/// UI 资源
  OTAImageTypeUi = 2,
/// 表盘，单个
  OTAImageTypeWatchface = 3,
/// TP 升级文件，仅 6621 平台使用
  OTAImageTypeTp = 4,
/// 字库文件
  OTAImageTypeFont = 5,
/// 表盘包，多个表盘打到一个bin文件里
  OTAImageTypeWatchface_bundle = 6,
/// 开关机 Logo
  OTAImageTypeOnoff_logo = 7,
/// 游戏皮肤
  OTAImageTypeGame_skin = 8,
/// 游戏 UI 资源包，仅蓝讯平台使用，多个游戏 UI 资源文件合并为一个 bin 包
  OTAImageTypeGame_ui_bundle_lx = 9,
/// 运动模式资源
  OTAImageTypeSports = 10,
/// 运动模式资源包，仅蓝讯平台使用，多个运动模式资源文件合并为一个 bin 包
  OTAImageTypeSports_bundle_lx = 11,
/// GPS EPO 文件，仅 8763x 平台带 GPS 模块的使用
  OTAImageTypeGps_epo = 12,
/// 守护进程，仅 6621 平台使用，需要特殊工程支持
  OTAImageTypeDaemon_process = 13,
/// 小程序，仅 6621 平台使用，需要特殊工程支持
  OTAImageTypeMini_program = 14,
/// 文件表, 仅蓝讯平台使用
  OTAImageTypeFile_tablelist_lx = 15,
/// 全量包，仅蓝讯平台使用
  OTAImageTypeFull_package_lx = 16,
};

/// 参数错误定义
typedef SWIFT_ENUM(NSInteger, ParamsError, open) {
/// 非法的槽位
  ParamsErrorBadSlot = 0,
};
static NSString * _Nonnull const ParamsErrorDomain = @"FitCloudOTAGenKit.ParamsError";

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 6.2.3 effective-5.10 (swiftlang-6.2.3.3.21 clang-1700.6.3.2)
#ifndef FITCLOUDOTAGENKIT_SWIFT_H
#define FITCLOUDOTAGENKIT_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="FitCloudOTAGenKit",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

/// EPO文件类型
typedef SWIFT_ENUM(NSInteger, EPOFileType, open) {
/// 非法的类型
  EPOFileTypeInvalid = -1,
/// GPS, 美国的全球定位系统
  EPOFileTypeGPS = 0,
/// GLONASS, 俄罗斯的格洛纳斯卫星导航系统
  EPOFileTypeGLONASS = 1,
/// GALILEO, 欧盟的伽利略卫星导航系统
  EPOFileTypeGALILEO = 2,
/// BDS, 中国的北斗卫星导航系统
  EPOFileTypeBDS = 3,
/// IRNSS, 印度区域导航卫星系统
  EPOFileTypeIRNSS = 4,
/// QZSS, 日本卫星定位导航系统
  EPOFileTypeQZSS = 5,
};

/// OTA生成的平台
typedef SWIFT_ENUM(NSInteger, FitCloudOTAGenPlatform, open) {
/// 非法的平台
  FitCloudOTAGenPlatformInvalid = -1,
/// 瑞煜
  FitCloudOTAGenPlatformRealtek = 0,
/// Nordic
  FitCloudOTAGenPlatformNordic = 1,
/// 中科蓝讯
  FitCloudOTAGenPlatformBluetrum = 2,
};

/// OTA文件生成服务
SWIFT_CLASS("_TtC17FitCloudOTAGenKit21FitCloudOTAGenService")
@interface FitCloudOTAGenService : NSObject
/// 初始化
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSString;
@protocol Loggable;
@class ICOEEPOFile;
@interface FitCloudOTAGenService (SWIFT_EXTENSION(FitCloudOTAGenKit))
/// 生成GPS文件(Old)
/// <ul>
///   <li>
///     Parameters:
///   </li>
///   <li>
///     epoFilePaths: epo 文件路径列表，多个epo文件
///   </li>
///   <li>
///     outputDirectory: 输出目录，用于存放生成好的bin文件的地方
///   </li>
///   <li>
///     logProvider: 日志打印服务提供者
///   </li>
/// </ul>
///
/// returns:
/// 生成好的GPS文件路径
+ (NSString * _Nullable)createGpsEpoBin:(NSArray<NSString *> * _Nonnull)epoFilePaths :(NSString * _Nonnull)outputDirectory :(id <Loggable> _Nullable)logProvider error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
/// 生成芯与物GPS文件
/// <ul>
///   <li>
///     Parameters:
///   </li>
///   <li>
///     epoFiles: epo 文件列表，多个epo文件
///   </li>
///   <li>
///     outputDirectory: 输出目录，用于存放生成好的bin文件的地方
///   </li>
///   <li>
///     logProvider: 日志打印服务提供者
///   </li>
/// </ul>
///
/// returns:
/// 生成好的GPS文件路径
+ (NSString * _Nullable)createICOEGpsEpoBin:(enum FitCloudOTAGenPlatform)platform :(NSArray<ICOEEPOFile *> * _Nonnull)epoFiles :(NSString * _Nonnull)outputDirectory :(id <Loggable> _Nullable)logProvider error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
@end

@class NSCoder;
/// 芯与物EPO文件
SWIFT_CLASS("_TtC17FitCloudOTAGenKit11ICOEEPOFile")
@interface ICOEEPOFile : NSObject <NSSecureCoding>
@property (nonatomic) enum EPOFileType fileType;
@property (nonatomic, copy) NSString * _Nonnull filePath;
- (nonnull instancetype)initWithFileType:(enum EPOFileType)fileType filePath:(NSString * _Nonnull)filePath OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL supportsSecureCoding;)
+ (BOOL)supportsSecureCoding SWIFT_WARN_UNUSED_RESULT;
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// The log level
typedef SWIFT_ENUM_NAMED(NSInteger, FitCloudOTAGenKitLogLevel, "LogLevel", open) {
/// verbose
  FitCloudOTAGenKitLogLevelVerbose = 0,
/// debug
  FitCloudOTAGenKitLogLevelDebug = 1,
/// info
  FitCloudOTAGenKitLogLevelInfo = 2,
/// warning
  FitCloudOTAGenKitLogLevelWarning = 3,
/// error
  FitCloudOTAGenKitLogLevelError = 4,
};

/// 日志协议
SWIFT_PROTOCOL("_TtP17FitCloudOTAGenKit8Loggable_")
@protocol Loggable <NSObject>
/// 打印日志
/// \param logLevel 日志等级
///
/// \param message 日志信息
///
- (void)log:(enum FitCloudOTAGenKitLogLevel)logLevel :(NSString * _Nonnull)message;
@end

typedef SWIFT_ENUM(NSInteger, OTAGenError, open) {
/// 文件不存在
  OTAGenErrorFileNotExist = 0,
/// 芯片平台不支持
  OTAGenErrorPlatformNotSupport = 1,
/// 非法的OTA头数据
  OTAGenErrorBadPlatformOTAHeaderData = 2,
};
static NSString * _Nonnull const OTAGenErrorDomain = @"FitCloudOTAGenKit.OTAGenError";

/// OTA 镜像类型
typedef SWIFT_ENUM(NSInteger, OTAImageType, open) {
/// 非法的类型
  OTAImageTypeInvalid = -1,
/// patch 文件
  OTAImageTypePatch = 0,
/// 固件
  OTAImageTypeFirmware = 1,
/// UI 资源
  OTAImageTypeUi = 2,
/// 表盘，单个
  OTAImageTypeWatchface = 3,
/// TP 升级文件，仅 6621 平台使用
  OTAImageTypeTp = 4,
/// 字库文件
  OTAImageTypeFont = 5,
/// 表盘包，多个表盘打到一个bin文件里
  OTAImageTypeWatchface_bundle = 6,
/// 开关机 Logo
  OTAImageTypeOnoff_logo = 7,
/// 游戏皮肤
  OTAImageTypeGame_skin = 8,
/// 游戏 UI 资源包，仅蓝讯平台使用，多个游戏 UI 资源文件合并为一个 bin 包
  OTAImageTypeGame_ui_bundle_lx = 9,
/// 运动模式资源
  OTAImageTypeSports = 10,
/// 运动模式资源包，仅蓝讯平台使用，多个运动模式资源文件合并为一个 bin 包
  OTAImageTypeSports_bundle_lx = 11,
/// GPS EPO 文件，仅 8763x 平台带 GPS 模块的使用
  OTAImageTypeGps_epo = 12,
/// 守护进程，仅 6621 平台使用，需要特殊工程支持
  OTAImageTypeDaemon_process = 13,
/// 小程序，仅 6621 平台使用，需要特殊工程支持
  OTAImageTypeMini_program = 14,
/// 文件表, 仅蓝讯平台使用
  OTAImageTypeFile_tablelist_lx = 15,
/// 全量包，仅蓝讯平台使用
  OTAImageTypeFull_package_lx = 16,
};

/// 参数错误定义
typedef SWIFT_ENUM(NSInteger, ParamsError, open) {
/// 非法的槽位
  ParamsErrorBadSlot = 0,
};
static NSString * _Nonnull const ParamsErrorDomain = @"FitCloudOTAGenKit.ParamsError";

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
