{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"calendar_date_selected_background_default"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/womenhealth\/themecolorkey\/calendar_date_selected_background_default"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/womenhealth\/themecolorkey\/calendar_date_selected_background_default"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/calendar_date_selected_background_default","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"选中日期背景色"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"calendar_date_selected_background_default"}],"title":"ThemeColorKey.calendar_date_selected_background_default","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@WomenHealth@E@ThemeColorKey@ThemeColorKeyCalendar_date_selected_background_default","modules":[{"name":"WomenHealth"}],"navigatorTitle":[{"kind":"identifier","text":"ThemeColorKeyCalendar_date_selected_background_default"}]},"hierarchy":{"paths":[["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey"]]},"references":{"doc://com.topstep.WomenHealth/documentation/WomenHealth/ThemeColorKey/calendar_date_selected_background_default":{"role":"symbol","title":"ThemeColorKey.calendar_date_selected_background_default","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"calendar_date_selected_background_default"}],"abstract":[{"type":"text","text":"选中日期背景色"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/calendar_date_selected_background_default","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThemeColorKeyCalendar_date_selected_background_default"}],"url":"\/documentation\/womenhealth\/themecolorkey\/calendar_date_selected_background_default"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/ThemeColorKey":{"role":"symbol","title":"ThemeColorKey","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThemeColorKey"}],"abstract":[{"type":"text","text":"颜色Key定义"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThemeColorKey"}],"url":"\/documentation\/womenhealth\/themecolorkey"},"doc://com.topstep.WomenHealth/documentation/WomenHealth":{"role":"collection","title":"WomenHealth","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","kind":"symbol","type":"topic","url":"\/documentation\/womenhealth"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ThemeColorKeyCalendar_date_selected_background_default"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ThemeColorKeyCalendar_date_selected_background_default"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ThemeColorKeyCalendar_date_selected_background_default"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeColorKey~1calendar_date_selected_background_default\/title","value":"ThemeColorKeyCalendar_date_selected_background_default"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeColorKey~1calendar_date_selected_background_default\/fragments","value":[{"kind":"identifier","text":"ThemeColorKeyCalendar_date_selected_background_default"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeColorKey\/title","value":"ThemeColorKey"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeColorKey\/fragments","value":[{"kind":"identifier","text":"ThemeColorKey"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}