{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ovulation_day_indicator"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/womenhealth\/themecolorkey\/ovulation_day_indicator"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/womenhealth\/themecolorkey\/ovulation_day_indicator"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/ovulation_day_indicator","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"排卵日指示色"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ovulation_day_indicator"}],"title":"ThemeColorKey.ovulation_day_indicator","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@WomenHealth@E@ThemeColorKey@ThemeColorKeyOvulation_day_indicator","modules":[{"name":"WomenHealth"}],"navigatorTitle":[{"kind":"identifier","text":"ThemeColorKeyOvulation_day_indicator"}]},"hierarchy":{"paths":[["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey"]]},"references":{"doc://com.topstep.WomenHealth/documentation/WomenHealth/ThemeColorKey":{"role":"symbol","title":"ThemeColorKey","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThemeColorKey"}],"abstract":[{"type":"text","text":"颜色Key定义"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThemeColorKey"}],"url":"\/documentation\/womenhealth\/themecolorkey"},"doc://com.topstep.WomenHealth/documentation/WomenHealth":{"role":"collection","title":"WomenHealth","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","kind":"symbol","type":"topic","url":"\/documentation\/womenhealth"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/ThemeColorKey/ovulation_day_indicator":{"role":"symbol","title":"ThemeColorKey.ovulation_day_indicator","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ovulation_day_indicator"}],"abstract":[{"type":"text","text":"排卵日指示色"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/ovulation_day_indicator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThemeColorKeyOvulation_day_indicator"}],"url":"\/documentation\/womenhealth\/themecolorkey\/ovulation_day_indicator"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ThemeColorKeyOvulation_day_indicator"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ThemeColorKeyOvulation_day_indicator"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ThemeColorKeyOvulation_day_indicator"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeColorKey\/title","value":"ThemeColorKey"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeColorKey\/fragments","value":[{"kind":"identifier","text":"ThemeColorKey"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeColorKey~1ovulation_day_indicator\/title","value":"ThemeColorKeyOvulation_day_indicator"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeColorKey~1ovulation_day_indicator\/fragments","value":[{"kind":"identifier","text":"ThemeColorKeyOvulation_day_indicator"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}