{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"separator"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/womenhealth\/themecolorkey\/separator"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/womenhealth\/themecolorkey\/separator"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/separator","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"分割线"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"separator"}],"title":"ThemeColorKey.separator","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@WomenHealth@E@ThemeColorKey@ThemeColorKeySeparator","modules":[{"name":"WomenHealth"}],"navigatorTitle":[{"kind":"identifier","text":"ThemeColorKeySeparator"}]},"hierarchy":{"paths":[["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey"]]},"references":{"doc://com.topstep.WomenHealth/documentation/WomenHealth/ThemeColorKey":{"role":"symbol","title":"ThemeColorKey","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThemeColorKey"}],"abstract":[{"type":"text","text":"颜色Key定义"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThemeColorKey"}],"url":"\/documentation\/womenhealth\/themecolorkey"},"doc://com.topstep.WomenHealth/documentation/WomenHealth":{"role":"collection","title":"WomenHealth","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","kind":"symbol","type":"topic","url":"\/documentation\/womenhealth"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/ThemeColorKey/separator":{"role":"symbol","title":"ThemeColorKey.separator","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"separator"}],"abstract":[{"type":"text","text":"分割线"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/separator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThemeColorKeySeparator"}],"url":"\/documentation\/womenhealth\/themecolorkey\/separator"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ThemeColorKeySeparator"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ThemeColorKeySeparator"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ThemeColorKeySeparator"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeColorKey\/title","value":"ThemeColorKey"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeColorKey\/fragments","value":[{"kind":"identifier","text":"ThemeColorKey"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeColorKey~1separator\/title","value":"ThemeColorKeySeparator"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeColorKey~1separator\/fragments","value":[{"kind":"identifier","text":"ThemeColorKeySeparator"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}