# Uncomment this line to define a global platform for your project

# 忽略引入库的所有警告（强迫症者的福音啊）
inhibit_all_warnings!

target 'FitCloudKitDemo' do
  platform :ios, '10.0'
  workspace 'FitCloudKitDemo.xcworkspace'
  project 'FitCloudKitDemo.xcodeproj'
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  #use_frameworks!

  # Pods for FitCloudKitDemo
  pod 'FitCloudKit', git: 'https://github.com/htangsmart/FitCloudPro-SDK-iOS.git'
  pod 'XLFacility', git: 'https://github.com/pcjbird/XLFacility.git'
  pod 'iOSLogBrowserSDK'
  pod 'YYCategories'
  pod 'Toast'
  end

