{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"icon_tablecell_accessory_checkmark"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/womenhealth\/themeimagekey\/icon_tablecell_accessory_checkmark"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/womenhealth\/themeimagekey\/icon_tablecell_accessory_checkmark"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey\/icon_tablecell_accessory_checkmark","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Table Cell checkmark 图标"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"icon_tablecell_accessory_checkmark"}],"title":"ThemeImageKey.icon_tablecell_accessory_checkmark","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@WomenHealth@E@ThemeImageKey@ThemeImageKeyIcon_tablecell_accessory_checkmark","modules":[{"name":"WomenHealth"}],"navigatorTitle":[{"kind":"identifier","text":"ThemeImageKeyIcon_tablecell_accessory_checkmark"}]},"hierarchy":{"paths":[["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey"]]},"references":{"doc://com.topstep.WomenHealth/documentation/WomenHealth/ThemeImageKey/icon_tablecell_accessory_checkmark":{"role":"symbol","title":"ThemeImageKey.icon_tablecell_accessory_checkmark","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"icon_tablecell_accessory_checkmark"}],"abstract":[{"type":"text","text":"Table Cell checkmark 图标"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey\/icon_tablecell_accessory_checkmark","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThemeImageKeyIcon_tablecell_accessory_checkmark"}],"url":"\/documentation\/womenhealth\/themeimagekey\/icon_tablecell_accessory_checkmark"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/ThemeImageKey":{"role":"symbol","title":"ThemeImageKey","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThemeImageKey"}],"abstract":[{"type":"text","text":"图片Key定义"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThemeImageKey"}],"url":"\/documentation\/womenhealth\/themeimagekey"},"doc://com.topstep.WomenHealth/documentation/WomenHealth":{"role":"collection","title":"WomenHealth","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","kind":"symbol","type":"topic","url":"\/documentation\/womenhealth"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ThemeImageKeyIcon_tablecell_accessory_checkmark"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ThemeImageKeyIcon_tablecell_accessory_checkmark"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ThemeImageKeyIcon_tablecell_accessory_checkmark"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeImageKey~1icon_tablecell_accessory_checkmark\/title","value":"ThemeImageKeyIcon_tablecell_accessory_checkmark"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeImageKey~1icon_tablecell_accessory_checkmark\/fragments","value":[{"kind":"identifier","text":"ThemeImageKeyIcon_tablecell_accessory_checkmark"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeImageKey\/title","value":"ThemeImageKey"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeImageKey\/fragments","value":[{"kind":"identifier","text":"ThemeImageKey"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}