{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"icon_ovulationday"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/womenhealth\/themeimagekey\/icon_ovulationday"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/womenhealth\/themeimagekey\/icon_ovulationday"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey\/icon_ovulationday","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"排卵日图标"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"icon_ovulationday"}],"title":"ThemeImageKey.icon_ovulationday","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@WomenHealth@E@ThemeImageKey@ThemeImageKeyIcon_ovulationday","modules":[{"name":"WomenHealth"}],"navigatorTitle":[{"kind":"identifier","text":"ThemeImageKeyIcon_ovulationday"}]},"hierarchy":{"paths":[["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey"]]},"references":{"doc://com.topstep.WomenHealth/documentation/WomenHealth/ThemeImageKey/icon_ovulationday":{"role":"symbol","title":"ThemeImageKey.icon_ovulationday","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"icon_ovulationday"}],"abstract":[{"type":"text","text":"排卵日图标"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey\/icon_ovulationday","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThemeImageKeyIcon_ovulationday"}],"url":"\/documentation\/womenhealth\/themeimagekey\/icon_ovulationday"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/ThemeImageKey":{"role":"symbol","title":"ThemeImageKey","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThemeImageKey"}],"abstract":[{"type":"text","text":"图片Key定义"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThemeImageKey"}],"url":"\/documentation\/womenhealth\/themeimagekey"},"doc://com.topstep.WomenHealth/documentation/WomenHealth":{"role":"collection","title":"WomenHealth","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","kind":"symbol","type":"topic","url":"\/documentation\/womenhealth"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ThemeImageKeyIcon_ovulationday"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ThemeImageKeyIcon_ovulationday"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ThemeImageKeyIcon_ovulationday"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeImageKey~1icon_ovulationday\/title","value":"ThemeImageKeyIcon_ovulationday"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeImageKey~1icon_ovulationday\/fragments","value":[{"kind":"identifier","text":"ThemeImageKeyIcon_ovulationday"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeImageKey\/title","value":"ThemeImageKey"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeImageKey\/fragments","value":[{"kind":"identifier","text":"ThemeImageKey"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}