{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"icon_chevron_down"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/womenhealth\/themeimagekey\/icon_chevron_down"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/womenhealth\/themeimagekey\/icon_chevron_down"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey\/icon_chevron_down","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"chevron.down 图标"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"icon_chevron_down"}],"title":"ThemeImageKey.icon_chevron_down","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@WomenHealth@E@ThemeImageKey@ThemeImageKeyIcon_chevron_down","modules":[{"name":"WomenHealth"}],"navigatorTitle":[{"kind":"identifier","text":"ThemeImageKeyIcon_chevron_down"}]},"hierarchy":{"paths":[["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey"]]},"references":{"doc://com.topstep.WomenHealth/documentation/WomenHealth/ThemeImageKey":{"role":"symbol","title":"ThemeImageKey","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThemeImageKey"}],"abstract":[{"type":"text","text":"图片Key定义"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThemeImageKey"}],"url":"\/documentation\/womenhealth\/themeimagekey"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/ThemeImageKey/icon_chevron_down":{"role":"symbol","title":"ThemeImageKey.icon_chevron_down","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"icon_chevron_down"}],"abstract":[{"type":"text","text":"chevron.down 图标"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey\/icon_chevron_down","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThemeImageKeyIcon_chevron_down"}],"url":"\/documentation\/womenhealth\/themeimagekey\/icon_chevron_down"},"doc://com.topstep.WomenHealth/documentation/WomenHealth":{"role":"collection","title":"WomenHealth","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","kind":"symbol","type":"topic","url":"\/documentation\/womenhealth"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ThemeImageKeyIcon_chevron_down"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ThemeImageKeyIcon_chevron_down"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ThemeImageKeyIcon_chevron_down"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeImageKey\/title","value":"ThemeImageKey"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeImageKey\/fragments","value":[{"kind":"identifier","text":"ThemeImageKey"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeImageKey~1icon_chevron_down\/title","value":"ThemeImageKeyIcon_chevron_down"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeImageKey~1icon_chevron_down\/fragments","value":[{"kind":"identifier","text":"ThemeImageKeyIcon_chevron_down"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}