{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pregnancy"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/womenhealth\/womenhealthmode\/pregnancy"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/womenhealth\/womenhealthmode\/pregnancy"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthMode\/pregnancy","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"怀孕模式"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"WomenHealthModePregnancy"}],"role":"symbol","title":"WomenHealthMode.pregnancy","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pregnancy"}],"symbolKind":"case","externalID":"c:@M@WomenHealth@E@WomenHealthMode@WomenHealthModePregnancy","modules":[{"name":"WomenHealth"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"11.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthMode"]]},"references":{"doc://com.topstep.WomenHealth/documentation/WomenHealth/WomenHealthMode/pregnancy":{"role":"symbol","title":"WomenHealthMode.pregnancy","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pregnancy"}],"abstract":[{"type":"text","text":"怀孕模式"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthMode\/pregnancy","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WomenHealthModePregnancy"}],"url":"\/documentation\/womenhealth\/womenhealthmode\/pregnancy"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/WomenHealthMode":{"role":"symbol","title":"WomenHealthMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"WomenHealthMode"}],"abstract":[{"type":"text","text":"女性健康模式"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WomenHealthMode"}],"url":"\/documentation\/womenhealth\/womenhealthmode"},"doc://com.topstep.WomenHealth/documentation/WomenHealth":{"role":"collection","title":"WomenHealth","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","kind":"symbol","type":"topic","url":"\/documentation\/womenhealth"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"WomenHealthModePregnancy"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"WomenHealthModePregnancy"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"WomenHealthModePregnancy"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthMode~1pregnancy\/title","value":"WomenHealthModePregnancy"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthMode~1pregnancy\/fragments","value":[{"kind":"identifier","text":"WomenHealthModePregnancy"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthMode\/title","value":"WomenHealthMode"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthMode\/fragments","value":[{"kind":"identifier","text":"WomenHealthMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}