# Uncomment this line to define a global platform for your project

# 忽略引入库的所有警告（强迫症者的福音啊）
inhibit_all_warnings!

#install! 'cocoapods', generate_multiple_pod_projects: true


target 'FitCloudWFKitDemo' do
  platform :ios, '9.0'
  workspace 'FitCloudWFKitDemo.xcworkspace'
  project 'FitCloudWFKitDemo.xcodeproj'
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  #use_frameworks!

  # Pods for FitCloudWFKitDemo
  pod 'FitCloudWFKit', :path => '../'
end

