{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"days_before_edc"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/womenhealth\/pregnancyremindtype\/days_before_edc"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/womenhealth\/pregnancyremindtype\/days_before_edc"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/PregnancyRemindType\/days_before_edc","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"距离预产期天数"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"PregnancyRemindTypeDays_before_edc"}],"role":"symbol","title":"PregnancyRemindType.days_before_edc","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"days_before_edc"}],"symbolKind":"case","externalID":"c:@M@WomenHealth@E@PregnancyRemindType@PregnancyRemindTypeDays_before_edc","modules":[{"name":"WomenHealth"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"11.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/PregnancyRemindType"]]},"references":{"doc://com.topstep.WomenHealth/documentation/WomenHealth":{"role":"collection","title":"WomenHealth","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","kind":"symbol","type":"topic","url":"\/documentation\/womenhealth"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/PregnancyRemindType/days_before_edc":{"role":"symbol","title":"PregnancyRemindType.days_before_edc","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"days_before_edc"}],"abstract":[{"type":"text","text":"距离预产期天数"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/PregnancyRemindType\/days_before_edc","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PregnancyRemindTypeDays_before_edc"}],"url":"\/documentation\/womenhealth\/pregnancyremindtype\/days_before_edc"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/PregnancyRemindType":{"role":"symbol","title":"PregnancyRemindType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PregnancyRemindType"}],"abstract":[{"type":"text","text":"怀孕期提醒方式"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/PregnancyRemindType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PregnancyRemindType"}],"url":"\/documentation\/womenhealth\/pregnancyremindtype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"PregnancyRemindTypeDays_before_edc"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PregnancyRemindTypeDays_before_edc"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"PregnancyRemindTypeDays_before_edc"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1PregnancyRemindType~1days_before_edc\/title","value":"PregnancyRemindTypeDays_before_edc"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1PregnancyRemindType~1days_before_edc\/fragments","value":[{"kind":"identifier","text":"PregnancyRemindTypeDays_before_edc"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1PregnancyRemindType\/title","value":"PregnancyRemindType"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1PregnancyRemindType\/fragments","value":[{"kind":"identifier","text":"PregnancyRemindType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}