{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"modeDidChangedNotification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Notification","preciseIdentifier":"s:10Foundation12NotificationV"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Name","preciseIdentifier":"s:10Foundation12NotificationV4Namea"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/womenhealth\/womenhealthnotifications\/modedidchangednotification"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/womenhealth\/womenhealthnotifications\/modedidchangednotification"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthNotifications\/modeDidChangedNotification","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"女性健康当前模式改变通知"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"modeDidChangedNotification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Notification","preciseIdentifier":"s:10Foundation12NotificationV"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Name","preciseIdentifier":"s:10Foundation12NotificationV4Namea"}],"title":"modeDidChangedNotification","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"c:@M@WomenHealth@objc(cs)WomenHealthNotifications(cpy)modeDidChangedNotification","modules":[{"name":"WomenHealth"}],"navigatorTitle":[{"kind":"identifier","text":"modeDidChangedNotification"}]},"hierarchy":{"paths":[["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthNotifications"]]},"references":{"doc://com.topstep.WomenHealth/documentation/WomenHealth/WomenHealthNotifications":{"role":"symbol","title":"WomenHealthNotifications","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WomenHealthNotifications"}],"abstract":[{"type":"text","text":"女性健康模块通知"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthNotifications","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WomenHealthNotifications"}],"url":"\/documentation\/womenhealth\/womenhealthnotifications"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/WomenHealthNotifications/modeDidChangedNotification":{"role":"symbol","title":"modeDidChangedNotification","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"modeDidChangedNotification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Notification","preciseIdentifier":"s:10Foundation12NotificationV"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Name","preciseIdentifier":"s:10Foundation12NotificationV4Namea"}],"abstract":[{"type":"text","text":"女性健康当前模式改变通知"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthNotifications\/modeDidChangedNotification","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"modeDidChangedNotification"}],"url":"\/documentation\/womenhealth\/womenhealthnotifications\/modedidchangednotification"},"doc://com.topstep.WomenHealth/documentation/WomenHealth":{"role":"collection","title":"WomenHealth","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","kind":"symbol","type":"topic","url":"\/documentation\/womenhealth"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"modeDidChangedNotification"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"modeDidChangedNotification"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"modeDidChangedNotification"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthNotifications\/title","value":"WomenHealthNotifications"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthNotifications\/fragments","value":[{"kind":"identifier","text":"WomenHealthNotifications"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthNotifications~1modeDidChangedNotification\/title","value":"modeDidChangedNotification"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthNotifications~1modeDidChangedNotification\/fragments","value":[{"kind":"identifier","text":"modeDidChangedNotification"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}