{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"notifySmartWatchWomenHealthFeatureAvailableChanged"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/womenhealth\/womenhealthmodule\/notifysmartwatchwomenhealthfeatureavailablechanged()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/womenhealth\/womenhealthmodule\/notifysmartwatchwomenhealthfeatureavailablechanged()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthModule\/notifySmartWatchWomenHealthFeatureAvailableChanged()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"通知女性健康模块手表女性健康功能可用状态发生改变"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"notifySmartWatchWomenHealthFeatureAvailableChanged"}],"role":"symbol","title":"notifySmartWatchWomenHealthFeatureAvailableChanged()","roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"notifySmartWatchWomenHealthFeatureAvailableChanged"},{"kind":"text","text":"()"}],"symbolKind":"method","externalID":"c:@M@WomenHealth@objc(cs)WomenHealthModule(cm)notifySmartWatchWomenHealthFeatureAvailableChanged","modules":[{"name":"WomenHealth"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"11.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthModule"]]},"references":{"doc://com.topstep.WomenHealth/documentation/WomenHealth/WomenHealthModule/notifySmartWatchWomenHealthFeatureAvailableChanged()":{"role":"symbol","title":"notifySmartWatchWomenHealthFeatureAvailableChanged()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"notifySmartWatchWomenHealthFeatureAvailableChanged"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"通知女性健康模块手表女性健康功能可用状态发生改变"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthModule\/notifySmartWatchWomenHealthFeatureAvailableChanged()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"notifySmartWatchWomenHealthFeatureAvailableChanged"}],"url":"\/documentation\/womenhealth\/womenhealthmodule\/notifysmartwatchwomenhealthfeatureavailablechanged()"},"doc://com.topstep.WomenHealth/documentation/WomenHealth":{"role":"collection","title":"WomenHealth","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","kind":"symbol","type":"topic","url":"\/documentation\/womenhealth"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/WomenHealthModule":{"role":"symbol","title":"WomenHealthModule","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WomenHealthModule"}],"abstract":[{"type":"text","text":"女性健康模块"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthModule","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WomenHealthModule"}],"url":"\/documentation\/womenhealth\/womenhealthmodule"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"notifySmartWatchWomenHealthFeatureAvailableChanged"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"notifySmartWatchWomenHealthFeatureAvailableChanged"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"notifySmartWatchWomenHealthFeatureAvailableChanged"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthModule~1notifySmartWatchWomenHealthFeatureAvailableChanged()\/title","value":"notifySmartWatchWomenHealthFeatureAvailableChanged"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthModule~1notifySmartWatchWomenHealthFeatureAvailableChanged()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"notifySmartWatchWomenHealthFeatureAvailableChanged"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthModule\/title","value":"WomenHealthModule"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthModule\/fragments","value":[{"kind":"identifier","text":"WomenHealthModule"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}