{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setWatchSyncServiceProvider"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"provider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/SmartWatchSyncable","preciseIdentifier":"c:@M@WomenHealth@objc(pl)SmartWatchSyncable","text":"SmartWatchSyncable"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"provider","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"同步女性健康配置给手表服务提供者"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/womenhealth\/womenhealthmodule\/setwatchsyncserviceprovider(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/womenhealth\/womenhealthmodule\/setwatchsyncserviceprovider(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthModule\/setWatchSyncServiceProvider(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"设置同步女性健康配置给手表服务提供者"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"setWatchSyncServiceProvider:"}],"role":"symbol","title":"setWatchSyncServiceProvider(_:)","roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setWatchSyncServiceProvider"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SmartWatchSyncable","preciseIdentifier":"c:@M@WomenHealth@objc(pl)SmartWatchSyncable"},{"kind":"text","text":"?)"}],"symbolKind":"method","externalID":"c:@M@WomenHealth@objc(cs)WomenHealthModule(cm)setWatchSyncServiceProvider:","modules":[{"name":"WomenHealth"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"11.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthModule"]]},"references":{"doc://com.topstep.WomenHealth/documentation/WomenHealth/WomenHealthModule":{"role":"symbol","title":"WomenHealthModule","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WomenHealthModule"}],"abstract":[{"type":"text","text":"女性健康模块"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthModule","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WomenHealthModule"}],"url":"\/documentation\/womenhealth\/womenhealthmodule"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/WomenHealthModule/setWatchSyncServiceProvider(_:)":{"role":"symbol","title":"setWatchSyncServiceProvider(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setWatchSyncServiceProvider"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SmartWatchSyncable","preciseIdentifier":"c:@M@WomenHealth@objc(pl)SmartWatchSyncable"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"设置同步女性健康配置给手表服务提供者"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthModule\/setWatchSyncServiceProvider(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setWatchSyncServiceProvider:"}],"url":"\/documentation\/womenhealth\/womenhealthmodule\/setwatchsyncserviceprovider(_:)"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/SmartWatchSyncable":{"role":"symbol","title":"SmartWatchSyncable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SmartWatchSyncable"}],"abstract":[{"type":"text","text":"智能手表同步协议"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/SmartWatchSyncable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SmartWatchSyncable"}],"url":"\/documentation\/womenhealth\/smartwatchsyncable"},"doc://com.topstep.WomenHealth/documentation/WomenHealth":{"role":"collection","title":"WomenHealth","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","kind":"symbol","type":"topic","url":"\/documentation\/womenhealth"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"setWatchSyncServiceProvider:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setWatchSyncServiceProvider:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"setWatchSyncServiceProvider:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<SmartWatchSyncable>","preciseIdentifier":"c:Qo@M@WomenHealth@objc(pl)SmartWatchSyncable"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"provider"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthModule\/title","value":"WomenHealthModule"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthModule\/fragments","value":[{"kind":"identifier","text":"WomenHealthModule"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthModule~1setWatchSyncServiceProvider(_:)\/title","value":"setWatchSyncServiceProvider:"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthModule~1setWatchSyncServiceProvider(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setWatchSyncServiceProvider:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1SmartWatchSyncable\/title","value":"SmartWatchSyncable"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1SmartWatchSyncable\/fragments","value":[{"kind":"identifier","text":"SmartWatchSyncable"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}