{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"localizationProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/Localizable","preciseIdentifier":"c:@M@WomenHealth@objc(pl)Localizable","text":"Localizable"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"themeProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/Themable","preciseIdentifier":"c:@M@WomenHealth@objc(pl)Themable","text":"Themable"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"logProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/Loggable","preciseIdentifier":"c:@M@WomenHealth@objc(pl)Loggable","text":"Loggable"},{"kind":"text","text":"? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"userId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"用户Id"}]}]},{"name":"localizationProvider","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"本地化提供者"}]}]},{"name":"themeProvider","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"皮肤提供者"}]}]},{"name":"logProvider","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"日志服务提供者"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/womenhealth\/womenhealthmodule\/start(with:_:_:_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/womenhealth\/womenhealthmodule\/start(with:_:_:_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthModule\/start(with:_:_:_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"初始化女性健康模块"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"startWith::::"}],"role":"symbol","title":"start(with:_:_:_:)","roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Localizable","preciseIdentifier":"c:@M@WomenHealth@objc(pl)Localizable"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Themable","preciseIdentifier":"c:@M@WomenHealth@objc(pl)Themable"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Loggable","preciseIdentifier":"c:@M@WomenHealth@objc(pl)Loggable"},{"kind":"text","text":"?)"}],"symbolKind":"method","externalID":"c:@M@WomenHealth@objc(cs)WomenHealthModule(cm)startWith::::","modules":[{"name":"WomenHealth"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"11.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthModule"]]},"references":{"doc://com.topstep.WomenHealth/documentation/WomenHealth/WomenHealthModule":{"role":"symbol","title":"WomenHealthModule","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WomenHealthModule"}],"abstract":[{"type":"text","text":"女性健康模块"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthModule","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WomenHealthModule"}],"url":"\/documentation\/womenhealth\/womenhealthmodule"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/Themable":{"role":"symbol","title":"Themable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Themable"}],"abstract":[{"type":"text","text":"皮肤协议"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/Themable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Themable"}],"url":"\/documentation\/womenhealth\/themable"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/Loggable":{"role":"symbol","title":"Loggable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Loggable"}],"abstract":[{"type":"text","text":"日志协议"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/Loggable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Loggable"}],"url":"\/documentation\/womenhealth\/loggable"},"doc://com.topstep.WomenHealth/documentation/WomenHealth":{"role":"collection","title":"WomenHealth","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","kind":"symbol","type":"topic","url":"\/documentation\/womenhealth"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/Localizable":{"role":"symbol","title":"Localizable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Localizable"}],"abstract":[{"type":"text","text":"国际化协议"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/Localizable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Localizable"}],"url":"\/documentation\/womenhealth\/localizable"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/WomenHealthModule/start(with:_:_:_:)":{"role":"symbol","title":"start(with:_:_:_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Localizable","preciseIdentifier":"c:@M@WomenHealth@objc(pl)Localizable"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Themable","preciseIdentifier":"c:@M@WomenHealth@objc(pl)Themable"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Loggable","preciseIdentifier":"c:@M@WomenHealth@objc(pl)Loggable"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"初始化女性健康模块"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthModule\/start(with:_:_:_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startWith::::"}],"url":"\/documentation\/womenhealth\/womenhealthmodule\/start(with:_:_:_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"startWith::::"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startWith::::"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"startWith:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"userId"},{"kind":"text","text":" "},{"kind":"identifier","text":":"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<Localizable>","preciseIdentifier":"c:Qo@M@WomenHealth@objc(pl)Localizable"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"localizationProvider"},{"kind":"text","text":" "},{"kind":"identifier","text":":"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<Themable>","preciseIdentifier":"c:Qo@M@WomenHealth@objc(pl)Themable"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"themeProvider"},{"kind":"text","text":" "},{"kind":"identifier","text":":"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<Loggable>","preciseIdentifier":"c:Qo@M@WomenHealth@objc(pl)Loggable"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"logProvider"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthModule\/title","value":"WomenHealthModule"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthModule\/fragments","value":[{"kind":"identifier","text":"WomenHealthModule"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1Themable\/title","value":"Themable"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1Themable\/fragments","value":[{"kind":"identifier","text":"Themable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1Loggable\/title","value":"Loggable"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1Loggable\/fragments","value":[{"kind":"identifier","text":"Loggable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1Localizable\/title","value":"Localizable"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1Localizable\/fragments","value":[{"kind":"identifier","text":"Localizable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthModule~1start(with:_:_:_:)\/title","value":"startWith::::"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthModule~1start(with:_:_:_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startWith::::"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}