{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocalizationKey"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/womenhealth\/localizationkey"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/womenhealth\/localizationkey"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.topstep.WomenHealth\/s12CaseIterableP","doc:\/\/com.topstep.WomenHealth\/s23CustomStringConvertibleP","doc:\/\/com.topstep.WomenHealth\/SQ","doc:\/\/com.topstep.WomenHealth\/SH","doc:\/\/com.topstep.WomenHealth\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"国际化Key定义"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocalizationKey"}],"title":"LocalizationKey","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@WomenHealth@E@LocalizationKey","modules":[{"name":"WomenHealth"}],"navigatorTitle":[{"kind":"identifier","text":"LocalizationKey"}]},"hierarchy":{"paths":[["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/AdvanceDaysToRemindFormat","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/AdvanceDaysToRemindPickerTitle","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/BackToToday","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/BeginTheMenses","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/CalcEDC","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/Cancel","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/ChangeModeConfirmMessageFormat","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/DateFormat","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/DaysFormat","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/DaysToEDC","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/DaysToEDCFormat","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/Done","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/EDCEventRemindTitle","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/EDCQuestion","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/EarlyPregnancyPhase","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/EndTheMenses","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/FutureDateNoOperationAvailable","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/LatePregnancyPhase","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/MensesBeginDaysFormat","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/MensesEventRemindTitleFormat","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/MensesModeSettingsTitle","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/MensesOnly","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/MenstrualBeginDayNoOperationAvailable","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/MenstrualBeginRemind","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/MenstrualCycle","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/MenstrualCyclePickerTitle","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/MenstrualCycleQuestion","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/MenstrualCycleWithDurationFormat","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/MenstrualDuration","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/MenstrualDurationPickerTitle","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/MenstrualDurationQuestion","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/MenstrualMode","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/MenstrualPhase","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/MidPregnancyPhase","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/No","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/Ok","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/OvulationDay","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/OvulationPhase","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/PastDateNoOperationAvailable","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/PregnancyDays","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/PregnancyDaysFormat","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/PregnancyMode","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/PregnancyModeSettingsTitle","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/PregnancyPhase","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/PregnancyPhaseRemind","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/PregnancyPhaseRemindMethodPickerTitle","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/PregnancyPrepareMode","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/PregnancyPrepareModeSettingsTitle","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/PregnancyPreparePhase","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/PregnancyProbabilityFormat","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/RecentMenstrualBegin","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/RemindAtWatch","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/RemindTime","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/RemindTimeFormat","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/RemindTimePickerTitle","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/SafetyPhase","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/SetEDC","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/StartMensesMode","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/StartPregnancyMode","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/StartPregnancyPrepareMode","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/Today","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/TodayIsEDC","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/WomenHealth","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/WomenHealthSettings","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/Yes"]},{"title":"Initializers","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/init(rawValue:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/comment","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/stringValue"]},{"title":"Type Properties","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/sampleLocalizedStrings"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/CustomStringConvertible-Implementations","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/Equatable-Implementations","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/PregnancyDaysFormat":{"role":"symbol","title":"LocalizationKey.PregnancyDaysFormat","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"PregnancyDaysFormat"}],"abstract":[{"type":"text","text":"已怀孕天数格式，例如：已怀孕%@周%@天"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/PregnancyDaysFormat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyPregnancyDaysFormat"}],"url":"\/documentation\/womenhealth\/localizationkey\/pregnancydaysformat"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/AdvanceDaysToRemindPickerTitle":{"role":"symbol","title":"LocalizationKey.AdvanceDaysToRemindPickerTitle","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdvanceDaysToRemindPickerTitle"}],"abstract":[{"type":"text","text":"选择提前几天提醒（单位：天）"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/AdvanceDaysToRemindPickerTitle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyAdvanceDaysToRemindPickerTitle"}],"url":"\/documentation\/womenhealth\/localizationkey\/advancedaystoremindpickertitle"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/Today":{"role":"symbol","title":"LocalizationKey.Today","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"Today"}],"abstract":[{"type":"text","text":"今天"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/Today","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyToday"}],"url":"\/documentation\/womenhealth\/localizationkey\/today"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/OvulationDay":{"role":"symbol","title":"LocalizationKey.OvulationDay","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"OvulationDay"}],"abstract":[{"type":"text","text":"排卵日"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/OvulationDay","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyOvulationDay"}],"url":"\/documentation\/womenhealth\/localizationkey\/ovulationday"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/PregnancyPrepareModeSettingsTitle":{"role":"symbol","title":"LocalizationKey.PregnancyPrepareModeSettingsTitle","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"PregnancyPrepareModeSettingsTitle"}],"abstract":[{"type":"text","text":"备孕设置"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/PregnancyPrepareModeSettingsTitle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyPregnancyPrepareModeSettingsTitle"}],"url":"\/documentation\/womenhealth\/localizationkey\/pregnancypreparemodesettingstitle"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/SetEDC":{"role":"symbol","title":"LocalizationKey.SetEDC","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"SetEDC"}],"abstract":[{"type":"text","text":"设置预产期"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/SetEDC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeySetEDC"}],"url":"\/documentation\/womenhealth\/localizationkey\/setedc"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/sampleLocalizedStrings":{"role":"symbol","title":"sampleLocalizedStrings","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sampleLocalizedStrings"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"默认国际化字符串数组"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/sampleLocalizedStrings","kind":"symbol","type":"topic","url":"\/documentation\/womenhealth\/localizationkey\/samplelocalizedstrings"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/MensesBeginDaysFormat":{"role":"symbol","title":"LocalizationKey.MensesBeginDaysFormat","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"MensesBeginDaysFormat"}],"abstract":[{"type":"text","text":"月经期 第%@天"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/MensesBeginDaysFormat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyMensesBeginDaysFormat"}],"url":"\/documentation\/womenhealth\/localizationkey\/mensesbegindaysformat"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/PregnancyPhaseRemindMethodPickerTitle":{"role":"symbol","title":"LocalizationKey.PregnancyPhaseRemindMethodPickerTitle","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"PregnancyPhaseRemindMethodPickerTitle"}],"abstract":[{"type":"text","text":"选择怀孕期提醒方式"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/PregnancyPhaseRemindMethodPickerTitle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyPregnancyPhaseRemindMethodPickerTitle"}],"url":"\/documentation\/womenhealth\/localizationkey\/pregnancyphaseremindmethodpickertitle"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/Done":{"role":"symbol","title":"LocalizationKey.Done","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"Done"}],"abstract":[{"type":"text","text":"完成"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/Done","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyDone"}],"url":"\/documentation\/womenhealth\/localizationkey\/done"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/EndTheMenses":{"role":"symbol","title":"LocalizationKey.EndTheMenses","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"EndTheMenses"}],"abstract":[{"type":"text","text":"月经结束"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/EndTheMenses","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyEndTheMenses"}],"url":"\/documentation\/womenhealth\/localizationkey\/endthemenses"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/FutureDateNoOperationAvailable":{"role":"symbol","title":"LocalizationKey.FutureDateNoOperationAvailable","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"FutureDateNoOperationAvailable"}],"abstract":[{"type":"text","text":"未来日期，无法操作"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/FutureDateNoOperationAvailable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyFutureDateNoOperationAvailable"}],"url":"\/documentation\/womenhealth\/localizationkey\/futuredatenooperationavailable"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/CustomStringConvertible-Implementations":{"role":"collectionGroup","title":"CustomStringConvertible Implementations","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/CustomStringConvertible-Implementations","kind":"article","type":"topic","url":"\/documentation\/womenhealth\/localizationkey\/customstringconvertible-implementations"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/womenhealth\/localizationkey\/init(rawvalue:)"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/Ok":{"role":"symbol","title":"LocalizationKey.Ok","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"Ok"}],"abstract":[{"type":"text","text":"确定"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/Ok","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyOk"}],"url":"\/documentation\/womenhealth\/localizationkey\/ok"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/MenstrualDuration":{"role":"symbol","title":"LocalizationKey.MenstrualDuration","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"MenstrualDuration"}],"abstract":[{"type":"text","text":"经期长度"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/MenstrualDuration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyMenstrualDuration"}],"url":"\/documentation\/womenhealth\/localizationkey\/menstrualduration"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/BeginTheMenses":{"role":"symbol","title":"LocalizationKey.BeginTheMenses","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"BeginTheMenses"}],"abstract":[{"type":"text","text":"月经开始"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/BeginTheMenses","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyBeginTheMenses"}],"url":"\/documentation\/womenhealth\/localizationkey\/beginthemenses"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/CalcEDC":{"role":"symbol","title":"LocalizationKey.CalcEDC","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"CalcEDC"}],"abstract":[{"type":"text","text":"计算预产期"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/CalcEDC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyCalcEDC"}],"url":"\/documentation\/womenhealth\/localizationkey\/calcedc"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/WomenHealth":{"role":"symbol","title":"LocalizationKey.WomenHealth","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"WomenHealth"}],"abstract":[{"type":"text","text":"女性健康"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/WomenHealth","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyWomenHealth"}],"url":"\/documentation\/womenhealth\/localizationkey\/womenhealth"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/RemindTimePickerTitle":{"role":"symbol","title":"LocalizationKey.RemindTimePickerTitle","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"RemindTimePickerTitle"}],"abstract":[{"type":"text","text":"选择提醒时间"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/RemindTimePickerTitle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyRemindTimePickerTitle"}],"url":"\/documentation\/womenhealth\/localizationkey\/remindtimepickertitle"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/DaysToEDCFormat":{"role":"symbol","title":"LocalizationKey.DaysToEDCFormat","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"DaysToEDCFormat"}],"abstract":[{"type":"text","text":"距离预产期还有多少天格式，例如：距离预产期还有%@天"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/DaysToEDCFormat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyDaysToEDCFormat"}],"url":"\/documentation\/womenhealth\/localizationkey\/daystoedcformat"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/RemindTimeFormat":{"role":"symbol","title":"LocalizationKey.RemindTimeFormat","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"RemindTimeFormat"}],"abstract":[{"type":"text","text":"提醒时间格式，例如： %02ld:%02ld"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/RemindTimeFormat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyRemindTimeFormat"}],"url":"\/documentation\/womenhealth\/localizationkey\/remindtimeformat"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/PregnancyPreparePhase":{"role":"symbol","title":"LocalizationKey.PregnancyPreparePhase","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"PregnancyPreparePhase"}],"abstract":[{"type":"text","text":"备孕期"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/PregnancyPreparePhase","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyPregnancyPreparePhase"}],"url":"\/documentation\/womenhealth\/localizationkey\/pregnancypreparephase"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/MensesOnly":{"role":"symbol","title":"LocalizationKey.MensesOnly","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"MensesOnly"}],"abstract":[{"type":"text","text":"只记经期"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/MensesOnly","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyMensesOnly"}],"url":"\/documentation\/womenhealth\/localizationkey\/mensesonly"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/AdvanceDaysToRemindFormat":{"role":"symbol","title":"LocalizationKey.AdvanceDaysToRemindFormat","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdvanceDaysToRemindFormat"}],"abstract":[{"type":"text","text":"提前几天提醒格式，例如：提前%@天"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/AdvanceDaysToRemindFormat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyAdvanceDaysToRemindFormat"}],"url":"\/documentation\/womenhealth\/localizationkey\/advancedaystoremindformat"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/PregnancyProbabilityFormat":{"role":"symbol","title":"LocalizationKey.PregnancyProbabilityFormat","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"PregnancyProbabilityFormat"}],"abstract":[{"type":"text","text":"怀孕概率 %@%%"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/PregnancyProbabilityFormat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyPregnancyProbabilityFormat"}],"url":"\/documentation\/womenhealth\/localizationkey\/pregnancyprobabilityformat"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/DaysToEDC":{"role":"symbol","title":"LocalizationKey.DaysToEDC","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"DaysToEDC"}],"abstract":[{"type":"text","text":"距离预产期天数"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/DaysToEDC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyDaysToEDC"}],"url":"\/documentation\/womenhealth\/localizationkey\/daystoedc"},"doc://com.topstep.WomenHealth/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.topstep.WomenHealth\/s23CustomStringConvertibleP"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/StartMensesMode":{"role":"symbol","title":"LocalizationKey.StartMensesMode","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"StartMensesMode"}],"abstract":[{"type":"text","text":"开始经期模式"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/StartMensesMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyStartMensesMode"}],"url":"\/documentation\/womenhealth\/localizationkey\/startmensesmode"},"doc://com.topstep.WomenHealth/s12CaseIterableP":{"type":"unresolvable","title":"Swift.CaseIterable","identifier":"doc:\/\/com.topstep.WomenHealth\/s12CaseIterableP"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/LatePregnancyPhase":{"role":"symbol","title":"LocalizationKey.LatePregnancyPhase","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"LatePregnancyPhase"}],"abstract":[{"type":"text","text":"孕晚期"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/LatePregnancyPhase","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyLatePregnancyPhase"}],"url":"\/documentation\/womenhealth\/localizationkey\/latepregnancyphase"},"doc://com.topstep.WomenHealth/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.topstep.WomenHealth\/SY"},"doc://com.topstep.WomenHealth/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.topstep.WomenHealth\/SH"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/PregnancyDays":{"role":"symbol","title":"LocalizationKey.PregnancyDays","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"PregnancyDays"}],"abstract":[{"type":"text","text":"已怀孕天数"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/PregnancyDays","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyPregnancyDays"}],"url":"\/documentation\/womenhealth\/localizationkey\/pregnancydays"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/womenhealth\/localizationkey\/equatable-implementations"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/MenstrualCycleQuestion":{"role":"symbol","title":"LocalizationKey.MenstrualCycleQuestion","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"MenstrualCycleQuestion"}],"abstract":[{"type":"text","text":"两次月经开始日大概间隔多久？"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/MenstrualCycleQuestion","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyMenstrualCycleQuestion"}],"url":"\/documentation\/womenhealth\/localizationkey\/menstrualcyclequestion"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/EDCEventRemindTitle":{"role":"symbol","title":"LocalizationKey.EDCEventRemindTitle","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"EDCEventRemindTitle"}],"abstract":[{"type":"text","text":"预产期提醒事件标题"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/EDCEventRemindTitle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyEDCEventRemindTitle"}],"url":"\/documentation\/womenhealth\/localizationkey\/edceventremindtitle"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/stringValue":{"role":"symbol","title":"stringValue","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"stringValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"字符串信息"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/stringValue","kind":"symbol","type":"topic","url":"\/documentation\/womenhealth\/localizationkey\/stringvalue"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/EarlyPregnancyPhase":{"role":"symbol","title":"LocalizationKey.EarlyPregnancyPhase","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"EarlyPregnancyPhase"}],"abstract":[{"type":"text","text":"孕早期"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/EarlyPregnancyPhase","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyEarlyPregnancyPhase"}],"url":"\/documentation\/womenhealth\/localizationkey\/earlypregnancyphase"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/Yes":{"role":"symbol","title":"LocalizationKey.Yes","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"Yes"}],"abstract":[{"type":"text","text":"是"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/Yes","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyYes"}],"url":"\/documentation\/womenhealth\/localizationkey\/yes"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/MensesEventRemindTitleFormat":{"role":"symbol","title":"LocalizationKey.MensesEventRemindTitleFormat","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"MensesEventRemindTitleFormat"}],"abstract":[{"type":"text","text":"月经期提醒事件标题格式，例如：距离月经期还有%@天"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/MensesEventRemindTitleFormat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyMensesEventRemindTitleFormat"}],"url":"\/documentation\/womenhealth\/localizationkey\/menseseventremindtitleformat"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/RecentMenstrualBegin":{"role":"symbol","title":"LocalizationKey.RecentMenstrualBegin","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"RecentMenstrualBegin"}],"abstract":[{"type":"text","text":"最近一次月经"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/RecentMenstrualBegin","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyRecentMenstrualBegin"}],"url":"\/documentation\/womenhealth\/localizationkey\/recentmenstrualbegin"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/RemindTime":{"role":"symbol","title":"LocalizationKey.RemindTime","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"RemindTime"}],"abstract":[{"type":"text","text":"提醒时间"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/RemindTime","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyRemindTime"}],"url":"\/documentation\/womenhealth\/localizationkey\/remindtime"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/PastDateNoOperationAvailable":{"role":"symbol","title":"LocalizationKey.PastDateNoOperationAvailable","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"PastDateNoOperationAvailable"}],"abstract":[{"type":"text","text":"过去日期，无法操作"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/PastDateNoOperationAvailable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyPastDateNoOperationAvailable"}],"url":"\/documentation\/womenhealth\/localizationkey\/pastdatenooperationavailable"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/ChangeModeConfirmMessageFormat":{"role":"symbol","title":"LocalizationKey.ChangeModeConfirmMessageFormat","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChangeModeConfirmMessageFormat"}],"abstract":[{"type":"text","text":"当前处于%@，是否开始%@?"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/ChangeModeConfirmMessageFormat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyChangeModeConfirmMessageFormat"}],"url":"\/documentation\/womenhealth\/localizationkey\/changemodeconfirmmessageformat"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/MenstrualMode":{"role":"symbol","title":"LocalizationKey.MenstrualMode","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"MenstrualMode"}],"abstract":[{"type":"text","text":"经期模式"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/MenstrualMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyMenstrualMode"}],"url":"\/documentation\/womenhealth\/localizationkey\/menstrualmode"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/PregnancyPhase":{"role":"symbol","title":"LocalizationKey.PregnancyPhase","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"PregnancyPhase"}],"abstract":[{"type":"text","text":"怀孕期"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/PregnancyPhase","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyPregnancyPhase"}],"url":"\/documentation\/womenhealth\/localizationkey\/pregnancyphase"},"doc://com.topstep.WomenHealth/documentation/WomenHealth":{"role":"collection","title":"WomenHealth","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","kind":"symbol","type":"topic","url":"\/documentation\/womenhealth"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/MenstrualDurationQuestion":{"role":"symbol","title":"LocalizationKey.MenstrualDurationQuestion","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"MenstrualDurationQuestion"}],"abstract":[{"type":"text","text":"您的月经大概持续几天？"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/MenstrualDurationQuestion","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyMenstrualDurationQuestion"}],"url":"\/documentation\/womenhealth\/localizationkey\/menstrualdurationquestion"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/WomenHealthSettings":{"role":"symbol","title":"LocalizationKey.WomenHealthSettings","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"WomenHealthSettings"}],"abstract":[{"type":"text","text":"女性健康设置"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/WomenHealthSettings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyWomenHealthSettings"}],"url":"\/documentation\/womenhealth\/localizationkey\/womenhealthsettings"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/MenstrualDurationPickerTitle":{"role":"symbol","title":"LocalizationKey.MenstrualDurationPickerTitle","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"MenstrualDurationPickerTitle"}],"abstract":[{"type":"text","text":"选择经期长度（单位：天）"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/MenstrualDurationPickerTitle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyMenstrualDurationPickerTitle"}],"url":"\/documentation\/womenhealth\/localizationkey\/menstrualdurationpickertitle"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/DaysFormat":{"role":"symbol","title":"LocalizationKey.DaysFormat","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"DaysFormat"}],"abstract":[{"type":"text","text":"天数格式，例如 %@天"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/DaysFormat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyDaysFormat"}],"url":"\/documentation\/womenhealth\/localizationkey\/daysformat"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/PregnancyModeSettingsTitle":{"role":"symbol","title":"LocalizationKey.PregnancyModeSettingsTitle","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"PregnancyModeSettingsTitle"}],"abstract":[{"type":"text","text":"孕期设置"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/PregnancyModeSettingsTitle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyPregnancyModeSettingsTitle"}],"url":"\/documentation\/womenhealth\/localizationkey\/pregnancymodesettingstitle"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey":{"role":"symbol","title":"LocalizationKey","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocalizationKey"}],"abstract":[{"type":"text","text":"国际化Key定义"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKey"}],"url":"\/documentation\/womenhealth\/localizationkey"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/StartPregnancyMode":{"role":"symbol","title":"LocalizationKey.StartPregnancyMode","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"StartPregnancyMode"}],"abstract":[{"type":"text","text":"开始怀孕模式"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/StartPregnancyMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyStartPregnancyMode"}],"url":"\/documentation\/womenhealth\/localizationkey\/startpregnancymode"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/womenhealth\/localizationkey\/rawrepresentable-implementations"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/comment":{"role":"symbol","title":"comment","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"comment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/comment","kind":"symbol","type":"topic","url":"\/documentation\/womenhealth\/localizationkey\/comment"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/RemindAtWatch":{"role":"symbol","title":"LocalizationKey.RemindAtWatch","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"RemindAtWatch"}],"abstract":[{"type":"text","text":"手表提醒"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/RemindAtWatch","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyRemindAtWatch"}],"url":"\/documentation\/womenhealth\/localizationkey\/remindatwatch"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/BackToToday":{"role":"symbol","title":"LocalizationKey.BackToToday","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"BackToToday"}],"abstract":[{"type":"text","text":"回今天"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/BackToToday","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyBackToToday"}],"url":"\/documentation\/womenhealth\/localizationkey\/backtotoday"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/MidPregnancyPhase":{"role":"symbol","title":"LocalizationKey.MidPregnancyPhase","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"MidPregnancyPhase"}],"abstract":[{"type":"text","text":"孕中期"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/MidPregnancyPhase","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyMidPregnancyPhase"}],"url":"\/documentation\/womenhealth\/localizationkey\/midpregnancyphase"},"doc://com.topstep.WomenHealth/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.topstep.WomenHealth\/SQ"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/MenstrualCycleWithDurationFormat":{"role":"symbol","title":"LocalizationKey.MenstrualCycleWithDurationFormat","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"MenstrualCycleWithDurationFormat"}],"abstract":[{"type":"text","text":"月经周期长度和经期长度格式，例如：周期%@天，经期%@天"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/MenstrualCycleWithDurationFormat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyMenstrualCycleWithDurationFormat"}],"url":"\/documentation\/womenhealth\/localizationkey\/menstrualcyclewithdurationformat"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/MenstrualCyclePickerTitle":{"role":"symbol","title":"LocalizationKey.MenstrualCyclePickerTitle","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"MenstrualCyclePickerTitle"}],"abstract":[{"type":"text","text":"选择周期长度（单位：天）"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/MenstrualCyclePickerTitle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyMenstrualCyclePickerTitle"}],"url":"\/documentation\/womenhealth\/localizationkey\/menstrualcyclepickertitle"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/MenstrualBeginRemind":{"role":"symbol","title":"LocalizationKey.MenstrualBeginRemind","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"MenstrualBeginRemind"}],"abstract":[{"type":"text","text":"经期开始提醒"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/MenstrualBeginRemind","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyMenstrualBeginRemind"}],"url":"\/documentation\/womenhealth\/localizationkey\/menstrualbeginremind"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/PregnancyPrepareMode":{"role":"symbol","title":"LocalizationKey.PregnancyPrepareMode","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"PregnancyPrepareMode"}],"abstract":[{"type":"text","text":"备孕模式"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/PregnancyPrepareMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyPregnancyPrepareMode"}],"url":"\/documentation\/womenhealth\/localizationkey\/pregnancypreparemode"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/EDCQuestion":{"role":"symbol","title":"LocalizationKey.EDCQuestion","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"EDCQuestion"}],"abstract":[{"type":"text","text":"您的预产期大概是什么时候？"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/EDCQuestion","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyEDCQuestion"}],"url":"\/documentation\/womenhealth\/localizationkey\/edcquestion"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/MensesModeSettingsTitle":{"role":"symbol","title":"LocalizationKey.MensesModeSettingsTitle","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"MensesModeSettingsTitle"}],"abstract":[{"type":"text","text":"经期设置"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/MensesModeSettingsTitle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyMensesModeSettingsTitle"}],"url":"\/documentation\/womenhealth\/localizationkey\/mensesmodesettingstitle"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/OvulationPhase":{"role":"symbol","title":"LocalizationKey.OvulationPhase","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"OvulationPhase"}],"abstract":[{"type":"text","text":"排卵期"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/OvulationPhase","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyOvulationPhase"}],"url":"\/documentation\/womenhealth\/localizationkey\/ovulationphase"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/PregnancyPhaseRemind":{"role":"symbol","title":"LocalizationKey.PregnancyPhaseRemind","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"PregnancyPhaseRemind"}],"abstract":[{"type":"text","text":"怀孕期提醒"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/PregnancyPhaseRemind","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyPregnancyPhaseRemind"}],"url":"\/documentation\/womenhealth\/localizationkey\/pregnancyphaseremind"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/No":{"role":"symbol","title":"LocalizationKey.No","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"No"}],"abstract":[{"type":"text","text":"否"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/No","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyNo"}],"url":"\/documentation\/womenhealth\/localizationkey\/no"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/PregnancyMode":{"role":"symbol","title":"LocalizationKey.PregnancyMode","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"PregnancyMode"}],"abstract":[{"type":"text","text":"怀孕模式"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/PregnancyMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyPregnancyMode"}],"url":"\/documentation\/womenhealth\/localizationkey\/pregnancymode"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/StartPregnancyPrepareMode":{"role":"symbol","title":"LocalizationKey.StartPregnancyPrepareMode","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"StartPregnancyPrepareMode"}],"abstract":[{"type":"text","text":"开始备孕模式"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/StartPregnancyPrepareMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyStartPregnancyPrepareMode"}],"url":"\/documentation\/womenhealth\/localizationkey\/startpregnancypreparemode"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/Cancel":{"role":"symbol","title":"LocalizationKey.Cancel","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"Cancel"}],"abstract":[{"type":"text","text":"取消"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/Cancel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyCancel"}],"url":"\/documentation\/womenhealth\/localizationkey\/cancel"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/MenstrualCycle":{"role":"symbol","title":"LocalizationKey.MenstrualCycle","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"MenstrualCycle"}],"abstract":[{"type":"text","text":"周期长度"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/MenstrualCycle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyMenstrualCycle"}],"url":"\/documentation\/womenhealth\/localizationkey\/menstrualcycle"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/DateFormat":{"role":"symbol","title":"LocalizationKey.DateFormat","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"DateFormat"}],"abstract":[{"type":"text","text":"日期格式，例如yyyy-MM-dd"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/DateFormat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyDateFormat"}],"url":"\/documentation\/womenhealth\/localizationkey\/dateformat"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/MenstrualPhase":{"role":"symbol","title":"LocalizationKey.MenstrualPhase","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"MenstrualPhase"}],"abstract":[{"type":"text","text":"月经期"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/MenstrualPhase","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyMenstrualPhase"}],"url":"\/documentation\/womenhealth\/localizationkey\/menstrualphase"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/MenstrualBeginDayNoOperationAvailable":{"role":"symbol","title":"LocalizationKey.MenstrualBeginDayNoOperationAvailable","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"MenstrualBeginDayNoOperationAvailable"}],"abstract":[{"type":"text","text":"经期开始，无法操作"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/MenstrualBeginDayNoOperationAvailable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyMenstrualBeginDayNoOperationAvailable"}],"url":"\/documentation\/womenhealth\/localizationkey\/menstrualbegindaynooperationavailable"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/TodayIsEDC":{"role":"symbol","title":"LocalizationKey.TodayIsEDC","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"TodayIsEDC"}],"abstract":[{"type":"text","text":"今日为预产期当日"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/TodayIsEDC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeyTodayIsEDC"}],"url":"\/documentation\/womenhealth\/localizationkey\/todayisedc"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LocalizationKey/SafetyPhase":{"role":"symbol","title":"LocalizationKey.SafetyPhase","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"SafetyPhase"}],"abstract":[{"type":"text","text":"安全期"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/SafetyPhase","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LocalizationKeySafetyPhase"}],"url":"\/documentation\/womenhealth\/localizationkey\/safetyphase"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"LocalizationKey"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"LocalizationKey"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"LocalizationKey"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/AdvanceDaysToRemindFormat","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/AdvanceDaysToRemindPickerTitle","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/BackToToday","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/BeginTheMenses","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/CalcEDC","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/Cancel","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/ChangeModeConfirmMessageFormat","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/DateFormat","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/DaysFormat","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/DaysToEDC","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/DaysToEDCFormat","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/Done","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/EDCEventRemindTitle","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/EDCQuestion","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/EarlyPregnancyPhase","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/EndTheMenses","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/FutureDateNoOperationAvailable","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/LatePregnancyPhase","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/MensesBeginDaysFormat","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/MensesEventRemindTitleFormat","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/MensesModeSettingsTitle","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/MensesOnly","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/MenstrualBeginDayNoOperationAvailable","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/MenstrualBeginRemind","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/MenstrualCycle","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/MenstrualCyclePickerTitle","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/MenstrualCycleQuestion","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/MenstrualCycleWithDurationFormat","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/MenstrualDuration","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/MenstrualDurationPickerTitle","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/MenstrualDurationQuestion","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/MenstrualMode","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/MenstrualPhase","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/MidPregnancyPhase","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/No","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/Ok","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/OvulationDay","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/OvulationPhase","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/PastDateNoOperationAvailable","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/PregnancyDays","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/PregnancyDaysFormat","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/PregnancyMode","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/PregnancyModeSettingsTitle","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/PregnancyPhase","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/PregnancyPhaseRemind","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/PregnancyPhaseRemindMethodPickerTitle","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/PregnancyPrepareMode","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/PregnancyPrepareModeSettingsTitle","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/PregnancyPreparePhase","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/PregnancyProbabilityFormat","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/RecentMenstrualBegin","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/RemindAtWatch","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/RemindTime","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/RemindTimeFormat","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/RemindTimePickerTitle","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/SafetyPhase","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/SetEDC","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/StartMensesMode","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/StartPregnancyMode","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/StartPregnancyPrepareMode","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/Today","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/TodayIsEDC","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/WomenHealth","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/WomenHealthSettings","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LocalizationKey\/Yes"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocalizationKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1PregnancyDaysFormat\/title","value":"LocalizationKeyPregnancyDaysFormat"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1PregnancyDaysFormat\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyPregnancyDaysFormat"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1AdvanceDaysToRemindPickerTitle\/title","value":"LocalizationKeyAdvanceDaysToRemindPickerTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1AdvanceDaysToRemindPickerTitle\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyAdvanceDaysToRemindPickerTitle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1Today\/title","value":"LocalizationKeyToday"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1Today\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyToday"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1OvulationDay\/title","value":"LocalizationKeyOvulationDay"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1OvulationDay\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyOvulationDay"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1PregnancyPrepareModeSettingsTitle\/title","value":"LocalizationKeyPregnancyPrepareModeSettingsTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1PregnancyPrepareModeSettingsTitle\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyPregnancyPrepareModeSettingsTitle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1SetEDC\/title","value":"LocalizationKeySetEDC"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1SetEDC\/fragments","value":[{"kind":"identifier","text":"LocalizationKeySetEDC"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1MensesBeginDaysFormat\/title","value":"LocalizationKeyMensesBeginDaysFormat"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1MensesBeginDaysFormat\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyMensesBeginDaysFormat"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1PregnancyPhaseRemindMethodPickerTitle\/title","value":"LocalizationKeyPregnancyPhaseRemindMethodPickerTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1PregnancyPhaseRemindMethodPickerTitle\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyPregnancyPhaseRemindMethodPickerTitle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1Done\/title","value":"LocalizationKeyDone"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1Done\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyDone"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1EndTheMenses\/title","value":"LocalizationKeyEndTheMenses"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1EndTheMenses\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyEndTheMenses"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1FutureDateNoOperationAvailable\/title","value":"LocalizationKeyFutureDateNoOperationAvailable"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1FutureDateNoOperationAvailable\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyFutureDateNoOperationAvailable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1Ok\/title","value":"LocalizationKeyOk"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1Ok\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyOk"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1MenstrualDuration\/title","value":"LocalizationKeyMenstrualDuration"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1MenstrualDuration\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyMenstrualDuration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1BeginTheMenses\/title","value":"LocalizationKeyBeginTheMenses"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1BeginTheMenses\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyBeginTheMenses"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1CalcEDC\/title","value":"LocalizationKeyCalcEDC"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1CalcEDC\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyCalcEDC"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1WomenHealth\/title","value":"LocalizationKeyWomenHealth"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1WomenHealth\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyWomenHealth"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1RemindTimePickerTitle\/title","value":"LocalizationKeyRemindTimePickerTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1RemindTimePickerTitle\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyRemindTimePickerTitle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1DaysToEDCFormat\/title","value":"LocalizationKeyDaysToEDCFormat"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1DaysToEDCFormat\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyDaysToEDCFormat"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1RemindTimeFormat\/title","value":"LocalizationKeyRemindTimeFormat"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1RemindTimeFormat\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyRemindTimeFormat"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1PregnancyPreparePhase\/title","value":"LocalizationKeyPregnancyPreparePhase"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1PregnancyPreparePhase\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyPregnancyPreparePhase"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1MensesOnly\/title","value":"LocalizationKeyMensesOnly"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1MensesOnly\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyMensesOnly"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1AdvanceDaysToRemindFormat\/title","value":"LocalizationKeyAdvanceDaysToRemindFormat"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1AdvanceDaysToRemindFormat\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyAdvanceDaysToRemindFormat"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1PregnancyProbabilityFormat\/title","value":"LocalizationKeyPregnancyProbabilityFormat"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1PregnancyProbabilityFormat\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyPregnancyProbabilityFormat"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1DaysToEDC\/title","value":"LocalizationKeyDaysToEDC"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1DaysToEDC\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyDaysToEDC"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1StartMensesMode\/title","value":"LocalizationKeyStartMensesMode"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1StartMensesMode\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyStartMensesMode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1LatePregnancyPhase\/title","value":"LocalizationKeyLatePregnancyPhase"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1LatePregnancyPhase\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyLatePregnancyPhase"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1PregnancyDays\/title","value":"LocalizationKeyPregnancyDays"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1PregnancyDays\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyPregnancyDays"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1MenstrualCycleQuestion\/title","value":"LocalizationKeyMenstrualCycleQuestion"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1MenstrualCycleQuestion\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyMenstrualCycleQuestion"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1EDCEventRemindTitle\/title","value":"LocalizationKeyEDCEventRemindTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1EDCEventRemindTitle\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyEDCEventRemindTitle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1EarlyPregnancyPhase\/title","value":"LocalizationKeyEarlyPregnancyPhase"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1EarlyPregnancyPhase\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyEarlyPregnancyPhase"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1Yes\/title","value":"LocalizationKeyYes"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1Yes\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyYes"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1MensesEventRemindTitleFormat\/title","value":"LocalizationKeyMensesEventRemindTitleFormat"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1MensesEventRemindTitleFormat\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyMensesEventRemindTitleFormat"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1RecentMenstrualBegin\/title","value":"LocalizationKeyRecentMenstrualBegin"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1RecentMenstrualBegin\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyRecentMenstrualBegin"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1RemindTime\/title","value":"LocalizationKeyRemindTime"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1RemindTime\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyRemindTime"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1PastDateNoOperationAvailable\/title","value":"LocalizationKeyPastDateNoOperationAvailable"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1PastDateNoOperationAvailable\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyPastDateNoOperationAvailable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1ChangeModeConfirmMessageFormat\/title","value":"LocalizationKeyChangeModeConfirmMessageFormat"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1ChangeModeConfirmMessageFormat\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyChangeModeConfirmMessageFormat"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1MenstrualMode\/title","value":"LocalizationKeyMenstrualMode"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1MenstrualMode\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyMenstrualMode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1PregnancyPhase\/title","value":"LocalizationKeyPregnancyPhase"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1PregnancyPhase\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyPregnancyPhase"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1MenstrualDurationQuestion\/title","value":"LocalizationKeyMenstrualDurationQuestion"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1MenstrualDurationQuestion\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyMenstrualDurationQuestion"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1WomenHealthSettings\/title","value":"LocalizationKeyWomenHealthSettings"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1WomenHealthSettings\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyWomenHealthSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1MenstrualDurationPickerTitle\/title","value":"LocalizationKeyMenstrualDurationPickerTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1MenstrualDurationPickerTitle\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyMenstrualDurationPickerTitle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1DaysFormat\/title","value":"LocalizationKeyDaysFormat"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1DaysFormat\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyDaysFormat"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1PregnancyModeSettingsTitle\/title","value":"LocalizationKeyPregnancyModeSettingsTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1PregnancyModeSettingsTitle\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyPregnancyModeSettingsTitle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey\/title","value":"LocalizationKey"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey\/fragments","value":[{"kind":"identifier","text":"LocalizationKey"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1StartPregnancyMode\/title","value":"LocalizationKeyStartPregnancyMode"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1StartPregnancyMode\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyStartPregnancyMode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1RemindAtWatch\/title","value":"LocalizationKeyRemindAtWatch"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1RemindAtWatch\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyRemindAtWatch"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1BackToToday\/title","value":"LocalizationKeyBackToToday"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1BackToToday\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyBackToToday"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1MidPregnancyPhase\/title","value":"LocalizationKeyMidPregnancyPhase"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1MidPregnancyPhase\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyMidPregnancyPhase"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1MenstrualCycleWithDurationFormat\/title","value":"LocalizationKeyMenstrualCycleWithDurationFormat"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1MenstrualCycleWithDurationFormat\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyMenstrualCycleWithDurationFormat"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1MenstrualCyclePickerTitle\/title","value":"LocalizationKeyMenstrualCyclePickerTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1MenstrualCyclePickerTitle\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyMenstrualCyclePickerTitle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1MenstrualBeginRemind\/title","value":"LocalizationKeyMenstrualBeginRemind"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1MenstrualBeginRemind\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyMenstrualBeginRemind"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1PregnancyPrepareMode\/title","value":"LocalizationKeyPregnancyPrepareMode"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1PregnancyPrepareMode\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyPregnancyPrepareMode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1EDCQuestion\/title","value":"LocalizationKeyEDCQuestion"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1EDCQuestion\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyEDCQuestion"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1MensesModeSettingsTitle\/title","value":"LocalizationKeyMensesModeSettingsTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1MensesModeSettingsTitle\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyMensesModeSettingsTitle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1OvulationPhase\/title","value":"LocalizationKeyOvulationPhase"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1OvulationPhase\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyOvulationPhase"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1PregnancyPhaseRemind\/title","value":"LocalizationKeyPregnancyPhaseRemind"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1PregnancyPhaseRemind\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyPregnancyPhaseRemind"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1No\/title","value":"LocalizationKeyNo"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1No\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyNo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1PregnancyMode\/title","value":"LocalizationKeyPregnancyMode"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1PregnancyMode\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyPregnancyMode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1StartPregnancyPrepareMode\/title","value":"LocalizationKeyStartPregnancyPrepareMode"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1StartPregnancyPrepareMode\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyStartPregnancyPrepareMode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1Cancel\/title","value":"LocalizationKeyCancel"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1Cancel\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyCancel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1MenstrualCycle\/title","value":"LocalizationKeyMenstrualCycle"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1MenstrualCycle\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyMenstrualCycle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1DateFormat\/title","value":"LocalizationKeyDateFormat"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1DateFormat\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyDateFormat"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1MenstrualPhase\/title","value":"LocalizationKeyMenstrualPhase"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1MenstrualPhase\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyMenstrualPhase"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1MenstrualBeginDayNoOperationAvailable\/title","value":"LocalizationKeyMenstrualBeginDayNoOperationAvailable"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1MenstrualBeginDayNoOperationAvailable\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyMenstrualBeginDayNoOperationAvailable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1TodayIsEDC\/title","value":"LocalizationKeyTodayIsEDC"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1TodayIsEDC\/fragments","value":[{"kind":"identifier","text":"LocalizationKeyTodayIsEDC"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1SafetyPhase\/title","value":"LocalizationKeySafetyPhase"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LocalizationKey~1SafetyPhase\/fragments","value":[{"kind":"identifier","text":"LocalizationKeySafetyPhase"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}