{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Localizable"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/womenhealth\/localizable"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/womenhealth\/localizable"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.topstep.WomenHealth\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/Localizable","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"国际化协议"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Localizable"}],"title":"Localizable","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@WomenHealth@objc(pl)Localizable","modules":[{"name":"WomenHealth"}],"navigatorTitle":[{"kind":"identifier","text":"Localizable"}]},"hierarchy":{"paths":[["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/Localizable\/localizationString(_:)"]}],"references":{"doc://com.topstep.WomenHealth/documentation/WomenHealth/Localizable":{"role":"symbol","title":"Localizable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Localizable"}],"abstract":[{"type":"text","text":"国际化协议"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/Localizable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Localizable"}],"url":"\/documentation\/womenhealth\/localizable"},"doc://com.topstep.WomenHealth/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.topstep.WomenHealth\/objc(pl)NSObject"},"doc://com.topstep.WomenHealth/documentation/WomenHealth":{"role":"collection","title":"WomenHealth","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","kind":"symbol","type":"topic","url":"\/documentation\/womenhealth"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/Localizable/localizationString(_:)":{"navigatorTitle":[{"kind":"identifier","text":"localizationString:"}],"role":"symbol","title":"localizationString(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"localizationString"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"LocalizationKey","preciseIdentifier":"c:@M@WomenHealth@E@LocalizationKey"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"根据 localizationKey 返回国际化字符串"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/Localizable\/localizationString(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/womenhealth\/localizable\/localizationstring(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"Localizable"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"Localizable"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"Localizable"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/Localizable\/localizationString(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.topstep.WomenHealth\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Localizable"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1Localizable\/title","value":"Localizable"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1Localizable\/fragments","value":[{"kind":"identifier","text":"Localizable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1Localizable~1localizationString(_:)\/title","value":"localizationString:"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1Localizable~1localizationString(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"localizationString:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}