{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogLevel"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/womenhealth\/loglevel"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/womenhealth\/loglevel"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.topstep.WomenHealth\/s23CustomStringConvertibleP","doc:\/\/com.topstep.WomenHealth\/SQ","doc:\/\/com.topstep.WomenHealth\/SH","doc:\/\/com.topstep.WomenHealth\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LogLevel","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The log level"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"LogLevel"}],"role":"symbol","title":"LogLevel","roleHeading":"Enumeration","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogLevel"}],"symbolKind":"enum","externalID":"c:@M@WomenHealth@E@LogLevel","modules":[{"name":"WomenHealth"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"11.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LogLevel\/debug","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LogLevel\/error","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LogLevel\/info","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LogLevel\/verbose","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LogLevel\/warning"]},{"title":"Initializers","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LogLevel\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LogLevel\/CustomStringConvertible-Implementations","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LogLevel\/Equatable-Implementations","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LogLevel\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.topstep.WomenHealth/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.topstep.WomenHealth\/s23CustomStringConvertibleP"},"doc://com.topstep.WomenHealth/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.topstep.WomenHealth\/SQ"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LogLevel/debug":{"role":"symbol","title":"LogLevel.debug","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"debug"}],"abstract":[{"type":"text","text":"debug"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LogLevel\/debug","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LogLevelDebug"}],"url":"\/documentation\/womenhealth\/loglevel\/debug"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LogLevel/info":{"role":"symbol","title":"LogLevel.info","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"info"}],"abstract":[{"type":"text","text":"info"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LogLevel\/info","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LogLevelInfo"}],"url":"\/documentation\/womenhealth\/loglevel\/info"},"doc://com.topstep.WomenHealth/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.topstep.WomenHealth\/SY"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LogLevel/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LogLevel\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/womenhealth\/loglevel\/init(rawvalue:)"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LogLevel/CustomStringConvertible-Implementations":{"role":"collectionGroup","title":"CustomStringConvertible Implementations","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LogLevel\/CustomStringConvertible-Implementations","kind":"article","type":"topic","url":"\/documentation\/womenhealth\/loglevel\/customstringconvertible-implementations"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LogLevel/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LogLevel\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/womenhealth\/loglevel\/rawrepresentable-implementations"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LogLevel/error":{"role":"symbol","title":"LogLevel.error","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"}],"abstract":[{"type":"text","text":"error"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LogLevel\/error","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LogLevelError"}],"url":"\/documentation\/womenhealth\/loglevel\/error"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LogLevel/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LogLevel\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/womenhealth\/loglevel\/equatable-implementations"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LogLevel/verbose":{"role":"symbol","title":"LogLevel.verbose","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"verbose"}],"abstract":[{"type":"text","text":"verbose"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LogLevel\/verbose","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LogLevelVerbose"}],"url":"\/documentation\/womenhealth\/loglevel\/verbose"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LogLevel/warning":{"role":"symbol","title":"LogLevel.warning","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"warning"}],"abstract":[{"type":"text","text":"warning"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LogLevel\/warning","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LogLevelWarning"}],"url":"\/documentation\/womenhealth\/loglevel\/warning"},"doc://com.topstep.WomenHealth/documentation/WomenHealth":{"role":"collection","title":"WomenHealth","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","kind":"symbol","type":"topic","url":"\/documentation\/womenhealth"},"doc://com.topstep.WomenHealth/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.topstep.WomenHealth\/SH"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/LogLevel":{"role":"symbol","title":"LogLevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogLevel"}],"abstract":[{"type":"text","text":"The log level"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LogLevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LogLevel"}],"url":"\/documentation\/womenhealth\/loglevel"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"LogLevel"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"LogLevel"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"LogLevel"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LogLevel\/debug","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LogLevel\/error","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LogLevel\/info","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LogLevel\/verbose","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/LogLevel\/warning"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LogLevel~1debug\/title","value":"LogLevelDebug"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LogLevel~1debug\/fragments","value":[{"kind":"identifier","text":"LogLevelDebug"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LogLevel~1info\/title","value":"LogLevelInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LogLevel~1info\/fragments","value":[{"kind":"identifier","text":"LogLevelInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LogLevel~1error\/title","value":"LogLevelError"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LogLevel~1error\/fragments","value":[{"kind":"identifier","text":"LogLevelError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LogLevel~1verbose\/title","value":"LogLevelVerbose"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LogLevel~1verbose\/fragments","value":[{"kind":"identifier","text":"LogLevelVerbose"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LogLevel~1warning\/title","value":"LogLevelWarning"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LogLevel~1warning\/fragments","value":[{"kind":"identifier","text":"LogLevelWarning"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LogLevel\/title","value":"LogLevel"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1LogLevel\/fragments","value":[{"kind":"identifier","text":"LogLevel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}