{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MenstrualBehaviorDate"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/womenhealth\/menstrualbehaviordate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/womenhealth\/menstrualbehaviordate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.topstep.WomenHealth\/SQ","doc:\/\/com.topstep.WomenHealth\/SH","doc:\/\/com.topstep.WomenHealth\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorDate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"经期人为操作类型"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"MenstrualBehaviorDate"}],"role":"symbol","title":"MenstrualBehaviorDate","roleHeading":"Enumeration","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MenstrualBehaviorDate"}],"symbolKind":"enum","externalID":"c:@M@WomenHealth@E@MenstrualBehaviorDate","modules":[{"name":"WomenHealth"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"11.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorDate\/end_available","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorDate\/feature_disabled","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorDate\/future","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorDate\/future_outscope","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorDate\/invalid","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorDate\/menstrual_begin","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorDate\/mode_not_match","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorDate\/past","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorDate\/start_available"]},{"title":"Initializers","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorDate\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorDate\/Equatable-Implementations","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorDate\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.topstep.WomenHealth/documentation/WomenHealth/MenstrualBehaviorDate/future":{"role":"symbol","title":"MenstrualBehaviorDate.future","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"future"}],"abstract":[{"type":"text","text":"未来日期"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorDate\/future","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MenstrualBehaviorDateFuture"}],"url":"\/documentation\/womenhealth\/menstrualbehaviordate\/future"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/MenstrualBehaviorDate/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorDate\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/womenhealth\/menstrualbehaviordate\/equatable-implementations"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/MenstrualBehaviorDate/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorDate\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/womenhealth\/menstrualbehaviordate\/init(rawvalue:)"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/MenstrualBehaviorDate/feature_disabled":{"role":"symbol","title":"MenstrualBehaviorDate.feature_disabled","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"feature_disabled"}],"abstract":[{"type":"text","text":"女性健康未启用"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorDate\/feature_disabled","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MenstrualBehaviorDateFeature_disabled"}],"url":"\/documentation\/womenhealth\/menstrualbehaviordate\/feature_disabled"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/MenstrualBehaviorDate/future_outscope":{"role":"symbol","title":"MenstrualBehaviorDate.future_outscope","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"future_outscope"}],"abstract":[{"type":"text","text":"未来超出范围日期"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorDate\/future_outscope","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MenstrualBehaviorDateFuture_outscope"}],"url":"\/documentation\/womenhealth\/menstrualbehaviordate\/future_outscope"},"doc://com.topstep.WomenHealth/documentation/WomenHealth":{"role":"collection","title":"WomenHealth","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","kind":"symbol","type":"topic","url":"\/documentation\/womenhealth"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/MenstrualBehaviorDate/end_available":{"role":"symbol","title":"MenstrualBehaviorDate.end_available","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"end_available"}],"abstract":[{"type":"text","text":"可以操作结束月经"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorDate\/end_available","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MenstrualBehaviorDateEnd_available"}],"url":"\/documentation\/womenhealth\/menstrualbehaviordate\/end_available"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/MenstrualBehaviorDate/start_available":{"role":"symbol","title":"MenstrualBehaviorDate.start_available","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"start_available"}],"abstract":[{"type":"text","text":"可以操作开始月经"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorDate\/start_available","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MenstrualBehaviorDateStart_available"}],"url":"\/documentation\/womenhealth\/menstrualbehaviordate\/start_available"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/MenstrualBehaviorDate/mode_not_match":{"role":"symbol","title":"MenstrualBehaviorDate.mode_not_match","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mode_not_match"}],"abstract":[{"type":"text","text":"女性健康模式不匹配，当前为怀孕期"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorDate\/mode_not_match","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MenstrualBehaviorDateMode_not_match"}],"url":"\/documentation\/womenhealth\/menstrualbehaviordate\/mode_not_match"},"doc://com.topstep.WomenHealth/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.topstep.WomenHealth\/SY"},"doc://com.topstep.WomenHealth/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.topstep.WomenHealth\/SH"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/MenstrualBehaviorDate/past":{"role":"symbol","title":"MenstrualBehaviorDate.past","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"past"}],"abstract":[{"type":"text","text":"过去日期"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorDate\/past","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MenstrualBehaviorDatePast"}],"url":"\/documentation\/womenhealth\/menstrualbehaviordate\/past"},"doc://com.topstep.WomenHealth/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.topstep.WomenHealth\/SQ"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/MenstrualBehaviorDate":{"role":"symbol","title":"MenstrualBehaviorDate","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MenstrualBehaviorDate"}],"abstract":[{"type":"text","text":"经期人为操作类型"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorDate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MenstrualBehaviorDate"}],"url":"\/documentation\/womenhealth\/menstrualbehaviordate"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/MenstrualBehaviorDate/menstrual_begin":{"role":"symbol","title":"MenstrualBehaviorDate.menstrual_begin","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"menstrual_begin"}],"abstract":[{"type":"text","text":"经期开始当天"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorDate\/menstrual_begin","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MenstrualBehaviorDateMenstrual_begin"}],"url":"\/documentation\/womenhealth\/menstrualbehaviordate\/menstrual_begin"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/MenstrualBehaviorDate/invalid":{"role":"symbol","title":"MenstrualBehaviorDate.invalid","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalid"}],"abstract":[{"type":"text","text":"非法日期"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorDate\/invalid","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MenstrualBehaviorDateInvalid"}],"url":"\/documentation\/womenhealth\/menstrualbehaviordate\/invalid"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/MenstrualBehaviorDate/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorDate\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/womenhealth\/menstrualbehaviordate\/rawrepresentable-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"MenstrualBehaviorDate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MenstrualBehaviorDate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MenstrualBehaviorDate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorDate\/end_available","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorDate\/feature_disabled","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorDate\/future","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorDate\/future_outscope","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorDate\/invalid","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorDate\/menstrual_begin","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorDate\/mode_not_match","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorDate\/past","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorDate\/start_available"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MenstrualBehaviorDate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1MenstrualBehaviorDate~1future\/title","value":"MenstrualBehaviorDateFuture"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1MenstrualBehaviorDate~1future\/fragments","value":[{"kind":"identifier","text":"MenstrualBehaviorDateFuture"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1MenstrualBehaviorDate~1feature_disabled\/title","value":"MenstrualBehaviorDateFeature_disabled"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1MenstrualBehaviorDate~1feature_disabled\/fragments","value":[{"kind":"identifier","text":"MenstrualBehaviorDateFeature_disabled"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1MenstrualBehaviorDate~1future_outscope\/title","value":"MenstrualBehaviorDateFuture_outscope"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1MenstrualBehaviorDate~1future_outscope\/fragments","value":[{"kind":"identifier","text":"MenstrualBehaviorDateFuture_outscope"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1MenstrualBehaviorDate~1end_available\/title","value":"MenstrualBehaviorDateEnd_available"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1MenstrualBehaviorDate~1end_available\/fragments","value":[{"kind":"identifier","text":"MenstrualBehaviorDateEnd_available"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1MenstrualBehaviorDate~1start_available\/title","value":"MenstrualBehaviorDateStart_available"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1MenstrualBehaviorDate~1start_available\/fragments","value":[{"kind":"identifier","text":"MenstrualBehaviorDateStart_available"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1MenstrualBehaviorDate~1mode_not_match\/title","value":"MenstrualBehaviorDateMode_not_match"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1MenstrualBehaviorDate~1mode_not_match\/fragments","value":[{"kind":"identifier","text":"MenstrualBehaviorDateMode_not_match"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1MenstrualBehaviorDate~1past\/title","value":"MenstrualBehaviorDatePast"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1MenstrualBehaviorDate~1past\/fragments","value":[{"kind":"identifier","text":"MenstrualBehaviorDatePast"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1MenstrualBehaviorDate\/title","value":"MenstrualBehaviorDate"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1MenstrualBehaviorDate\/fragments","value":[{"kind":"identifier","text":"MenstrualBehaviorDate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1MenstrualBehaviorDate~1menstrual_begin\/title","value":"MenstrualBehaviorDateMenstrual_begin"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1MenstrualBehaviorDate~1menstrual_begin\/fragments","value":[{"kind":"identifier","text":"MenstrualBehaviorDateMenstrual_begin"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1MenstrualBehaviorDate~1invalid\/title","value":"MenstrualBehaviorDateInvalid"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1MenstrualBehaviorDate~1invalid\/fragments","value":[{"kind":"identifier","text":"MenstrualBehaviorDateInvalid"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}