{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MenstrualBehaviorType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/womenhealth\/menstrualbehaviortype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/womenhealth\/menstrualbehaviortype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.topstep.WomenHealth\/s23CustomStringConvertibleP","doc:\/\/com.topstep.WomenHealth\/Se","doc:\/\/com.topstep.WomenHealth\/SE","doc:\/\/com.topstep.WomenHealth\/SQ","doc:\/\/com.topstep.WomenHealth\/SH","doc:\/\/com.topstep.WomenHealth\/SY","doc:\/\/com.topstep.WomenHealth\/9WCDBSwift17ColumnCodableBaseP","doc:\/\/com.topstep.WomenHealth\/9WCDBSwift15ColumnDecodableP","doc:\/\/com.topstep.WomenHealth\/9WCDBSwift15ColumnEncodableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"经期人为操作类型"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"MenstrualBehaviorType"}],"role":"symbol","title":"MenstrualBehaviorType","roleHeading":"Enumeration","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MenstrualBehaviorType"}],"symbolKind":"enum","externalID":"c:@M@WomenHealth@E@MenstrualBehaviorType","modules":[{"name":"WomenHealth"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"11.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorType\/begin_manual","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorType\/end_manual"]},{"title":"Initializers","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorType\/ColumnCodableBase-Implementations","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorType\/ColumnDecodable-Implementations","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorType\/ColumnEncodable-Implementations","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorType\/CustomStringConvertible-Implementations","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorType\/Equatable-Implementations","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorType\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.topstep.WomenHealth/documentation/WomenHealth/MenstrualBehaviorType":{"role":"symbol","title":"MenstrualBehaviorType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MenstrualBehaviorType"}],"abstract":[{"type":"text","text":"经期人为操作类型"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MenstrualBehaviorType"}],"url":"\/documentation\/womenhealth\/menstrualbehaviortype"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/MenstrualBehaviorType/begin_manual":{"role":"symbol","title":"MenstrualBehaviorType.begin_manual","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"begin_manual"}],"abstract":[{"type":"text","text":"开始月经"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorType\/begin_manual","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MenstrualBehaviorTypeBegin_manual"}],"url":"\/documentation\/womenhealth\/menstrualbehaviortype\/begin_manual"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/MenstrualBehaviorType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/womenhealth\/menstrualbehaviortype\/rawrepresentable-implementations"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/MenstrualBehaviorType/ColumnEncodable-Implementations":{"role":"collectionGroup","title":"ColumnEncodable Implementations","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorType\/ColumnEncodable-Implementations","kind":"article","type":"topic","url":"\/documentation\/womenhealth\/menstrualbehaviortype\/columnencodable-implementations"},"doc://com.topstep.WomenHealth/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.topstep.WomenHealth\/SY"},"doc://com.topstep.WomenHealth/9WCDBSwift17ColumnCodableBaseP":{"type":"unresolvable","title":"WCDBSwift.ColumnCodableBase","identifier":"doc:\/\/com.topstep.WomenHealth\/9WCDBSwift17ColumnCodableBaseP"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/MenstrualBehaviorType/end_manual":{"role":"symbol","title":"MenstrualBehaviorType.end_manual","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"end_manual"}],"abstract":[{"type":"text","text":"结束月经"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorType\/end_manual","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MenstrualBehaviorTypeEnd_manual"}],"url":"\/documentation\/womenhealth\/menstrualbehaviortype\/end_manual"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/MenstrualBehaviorType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/womenhealth\/menstrualbehaviortype\/init(rawvalue:)"},"doc://com.topstep.WomenHealth/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.topstep.WomenHealth\/SQ"},"doc://com.topstep.WomenHealth/9WCDBSwift15ColumnDecodableP":{"type":"unresolvable","title":"WCDBSwift.ColumnDecodable","identifier":"doc:\/\/com.topstep.WomenHealth\/9WCDBSwift15ColumnDecodableP"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/MenstrualBehaviorType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/womenhealth\/menstrualbehaviortype\/equatable-implementations"},"doc://com.topstep.WomenHealth/documentation/WomenHealth":{"role":"collection","title":"WomenHealth","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","kind":"symbol","type":"topic","url":"\/documentation\/womenhealth"},"doc://com.topstep.WomenHealth/9WCDBSwift15ColumnEncodableP":{"type":"unresolvable","title":"WCDBSwift.ColumnEncodable","identifier":"doc:\/\/com.topstep.WomenHealth\/9WCDBSwift15ColumnEncodableP"},"doc://com.topstep.WomenHealth/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.topstep.WomenHealth\/SE"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/MenstrualBehaviorType/ColumnDecodable-Implementations":{"role":"collectionGroup","title":"ColumnDecodable Implementations","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorType\/ColumnDecodable-Implementations","kind":"article","type":"topic","url":"\/documentation\/womenhealth\/menstrualbehaviortype\/columndecodable-implementations"},"doc://com.topstep.WomenHealth/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.topstep.WomenHealth\/Se"},"doc://com.topstep.WomenHealth/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.topstep.WomenHealth\/SH"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/MenstrualBehaviorType/ColumnCodableBase-Implementations":{"role":"collectionGroup","title":"ColumnCodableBase Implementations","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorType\/ColumnCodableBase-Implementations","kind":"article","type":"topic","url":"\/documentation\/womenhealth\/menstrualbehaviortype\/columncodablebase-implementations"},"doc://com.topstep.WomenHealth/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.topstep.WomenHealth\/s23CustomStringConvertibleP"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/MenstrualBehaviorType/CustomStringConvertible-Implementations":{"role":"collectionGroup","title":"CustomStringConvertible Implementations","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorType\/CustomStringConvertible-Implementations","kind":"article","type":"topic","url":"\/documentation\/womenhealth\/menstrualbehaviortype\/customstringconvertible-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"MenstrualBehaviorType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MenstrualBehaviorType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MenstrualBehaviorType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorType\/begin_manual","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/MenstrualBehaviorType\/end_manual"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MenstrualBehaviorType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1MenstrualBehaviorType\/title","value":"MenstrualBehaviorType"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1MenstrualBehaviorType\/fragments","value":[{"kind":"identifier","text":"MenstrualBehaviorType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1MenstrualBehaviorType~1begin_manual\/title","value":"MenstrualBehaviorTypeBegin_manual"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1MenstrualBehaviorType~1begin_manual\/fragments","value":[{"kind":"identifier","text":"MenstrualBehaviorTypeBegin_manual"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1MenstrualBehaviorType~1end_manual\/title","value":"MenstrualBehaviorTypeEnd_manual"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1MenstrualBehaviorType~1end_manual\/fragments","value":[{"kind":"identifier","text":"MenstrualBehaviorTypeEnd_manual"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}