{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PregnancyRemindType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/womenhealth\/pregnancyremindtype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/womenhealth\/pregnancyremindtype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.topstep.WomenHealth\/s23CustomStringConvertibleP","doc:\/\/com.topstep.WomenHealth\/Se","doc:\/\/com.topstep.WomenHealth\/SE","doc:\/\/com.topstep.WomenHealth\/SQ","doc:\/\/com.topstep.WomenHealth\/SH","doc:\/\/com.topstep.WomenHealth\/SY","doc:\/\/com.topstep.WomenHealth\/9WCDBSwift17ColumnCodableBaseP","doc:\/\/com.topstep.WomenHealth\/9WCDBSwift15ColumnDecodableP","doc:\/\/com.topstep.WomenHealth\/9WCDBSwift15ColumnEncodableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/PregnancyRemindType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"怀孕期提醒方式"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"PregnancyRemindType"}],"role":"symbol","title":"PregnancyRemindType","roleHeading":"Enumeration","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PregnancyRemindType"}],"symbolKind":"enum","externalID":"c:@M@WomenHealth@E@PregnancyRemindType","modules":[{"name":"WomenHealth"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"11.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/PregnancyRemindType\/days_before_edc","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/PregnancyRemindType\/pregnancy_days"]},{"title":"Initializers","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/PregnancyRemindType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/PregnancyRemindType\/ColumnCodableBase-Implementations","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/PregnancyRemindType\/ColumnDecodable-Implementations","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/PregnancyRemindType\/ColumnEncodable-Implementations","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/PregnancyRemindType\/CustomStringConvertible-Implementations","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/PregnancyRemindType\/Equatable-Implementations","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/PregnancyRemindType\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.topstep.WomenHealth/documentation/WomenHealth/PregnancyRemindType/ColumnCodableBase-Implementations":{"role":"collectionGroup","title":"ColumnCodableBase Implementations","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/PregnancyRemindType\/ColumnCodableBase-Implementations","kind":"article","type":"topic","url":"\/documentation\/womenhealth\/pregnancyremindtype\/columncodablebase-implementations"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/PregnancyRemindType":{"role":"symbol","title":"PregnancyRemindType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PregnancyRemindType"}],"abstract":[{"type":"text","text":"怀孕期提醒方式"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/PregnancyRemindType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PregnancyRemindType"}],"url":"\/documentation\/womenhealth\/pregnancyremindtype"},"doc://com.topstep.WomenHealth/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.topstep.WomenHealth\/SQ"},"doc://com.topstep.WomenHealth/9WCDBSwift15ColumnDecodableP":{"type":"unresolvable","title":"WCDBSwift.ColumnDecodable","identifier":"doc:\/\/com.topstep.WomenHealth\/9WCDBSwift15ColumnDecodableP"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/PregnancyRemindType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/PregnancyRemindType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/womenhealth\/pregnancyremindtype\/init(rawvalue:)"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/PregnancyRemindType/CustomStringConvertible-Implementations":{"role":"collectionGroup","title":"CustomStringConvertible Implementations","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/PregnancyRemindType\/CustomStringConvertible-Implementations","kind":"article","type":"topic","url":"\/documentation\/womenhealth\/pregnancyremindtype\/customstringconvertible-implementations"},"doc://com.topstep.WomenHealth/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.topstep.WomenHealth\/s23CustomStringConvertibleP"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/PregnancyRemindType/ColumnDecodable-Implementations":{"role":"collectionGroup","title":"ColumnDecodable Implementations","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/PregnancyRemindType\/ColumnDecodable-Implementations","kind":"article","type":"topic","url":"\/documentation\/womenhealth\/pregnancyremindtype\/columndecodable-implementations"},"doc://com.topstep.WomenHealth/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.topstep.WomenHealth\/SE"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/PregnancyRemindType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/PregnancyRemindType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/womenhealth\/pregnancyremindtype\/equatable-implementations"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/PregnancyRemindType/pregnancy_days":{"role":"symbol","title":"PregnancyRemindType.pregnancy_days","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pregnancy_days"}],"abstract":[{"type":"text","text":"已怀孕天数"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/PregnancyRemindType\/pregnancy_days","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PregnancyRemindTypePregnancy_days"}],"url":"\/documentation\/womenhealth\/pregnancyremindtype\/pregnancy_days"},"doc://com.topstep.WomenHealth/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.topstep.WomenHealth\/Se"},"doc://com.topstep.WomenHealth/9WCDBSwift15ColumnEncodableP":{"type":"unresolvable","title":"WCDBSwift.ColumnEncodable","identifier":"doc:\/\/com.topstep.WomenHealth\/9WCDBSwift15ColumnEncodableP"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/PregnancyRemindType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/PregnancyRemindType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/womenhealth\/pregnancyremindtype\/rawrepresentable-implementations"},"doc://com.topstep.WomenHealth/9WCDBSwift17ColumnCodableBaseP":{"type":"unresolvable","title":"WCDBSwift.ColumnCodableBase","identifier":"doc:\/\/com.topstep.WomenHealth\/9WCDBSwift17ColumnCodableBaseP"},"doc://com.topstep.WomenHealth/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.topstep.WomenHealth\/SH"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/PregnancyRemindType/ColumnEncodable-Implementations":{"role":"collectionGroup","title":"ColumnEncodable Implementations","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/PregnancyRemindType\/ColumnEncodable-Implementations","kind":"article","type":"topic","url":"\/documentation\/womenhealth\/pregnancyremindtype\/columnencodable-implementations"},"doc://com.topstep.WomenHealth/documentation/WomenHealth":{"role":"collection","title":"WomenHealth","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","kind":"symbol","type":"topic","url":"\/documentation\/womenhealth"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/PregnancyRemindType/days_before_edc":{"role":"symbol","title":"PregnancyRemindType.days_before_edc","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"days_before_edc"}],"abstract":[{"type":"text","text":"距离预产期天数"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/PregnancyRemindType\/days_before_edc","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PregnancyRemindTypeDays_before_edc"}],"url":"\/documentation\/womenhealth\/pregnancyremindtype\/days_before_edc"},"doc://com.topstep.WomenHealth/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.topstep.WomenHealth\/SY"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"PregnancyRemindType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PregnancyRemindType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PregnancyRemindType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/PregnancyRemindType\/days_before_edc","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/PregnancyRemindType\/pregnancy_days"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PregnancyRemindType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1PregnancyRemindType\/title","value":"PregnancyRemindType"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1PregnancyRemindType\/fragments","value":[{"kind":"identifier","text":"PregnancyRemindType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1PregnancyRemindType~1pregnancy_days\/title","value":"PregnancyRemindTypePregnancy_days"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1PregnancyRemindType~1pregnancy_days\/fragments","value":[{"kind":"identifier","text":"PregnancyRemindTypePregnancy_days"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1PregnancyRemindType~1days_before_edc\/title","value":"PregnancyRemindTypeDays_before_edc"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1PregnancyRemindType~1days_before_edc\/fragments","value":[{"kind":"identifier","text":"PregnancyRemindTypeDays_before_edc"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}