{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SmartWatchSyncable"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/womenhealth\/smartwatchsyncable"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/womenhealth\/smartwatchsyncable"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.topstep.WomenHealth\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/SmartWatchSyncable","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"智能手表同步协议"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SmartWatchSyncable"}],"title":"SmartWatchSyncable","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@WomenHealth@objc(pl)SmartWatchSyncable","modules":[{"name":"WomenHealth"}],"navigatorTitle":[{"kind":"identifier","text":"SmartWatchSyncable"}]},"hierarchy":{"paths":[["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/SmartWatchSyncable\/syncIfNeededWith(_:_:_:_:_:_:_:_:_:_:)","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/SmartWatchSyncable\/withFeatureOnWatch()"]}],"references":{"doc://com.topstep.WomenHealth/documentation/WomenHealth":{"role":"collection","title":"WomenHealth","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","kind":"symbol","type":"topic","url":"\/documentation\/womenhealth"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/SmartWatchSyncable/withFeatureOnWatch()":{"navigatorTitle":[{"kind":"identifier","text":"withFeatureOnWatch"}],"role":"symbol","title":"withFeatureOnWatch()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"withFeatureOnWatch"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"手表是否支持女性健康功能"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/SmartWatchSyncable\/withFeatureOnWatch()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/womenhealth\/smartwatchsyncable\/withfeatureonwatch()"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/SmartWatchSyncable/syncIfNeededWith(_:_:_:_:_:_:_:_:_:_:)":{"navigatorTitle":[{"kind":"identifier","text":"syncIfNeededWith::::::::::"}],"role":"symbol","title":"syncIfNeededWith(_:_:_:_:_:_:_:_:_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"syncIfNeededWith"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"WomenHealthMode","preciseIdentifier":"c:@M@WomenHealth@E@WomenHealthMode"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"PregnancyRemindType","preciseIdentifier":"c:@M@WomenHealth@E@PregnancyRemindType"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"如果需要则同步女性健康配置给手表"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/SmartWatchSyncable\/syncIfNeededWith(_:_:_:_:_:_:_:_:_:_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/womenhealth\/smartwatchsyncable\/syncifneededwith(_:_:_:_:_:_:_:_:_:_:)"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/SmartWatchSyncable":{"role":"symbol","title":"SmartWatchSyncable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SmartWatchSyncable"}],"abstract":[{"type":"text","text":"智能手表同步协议"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/SmartWatchSyncable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SmartWatchSyncable"}],"url":"\/documentation\/womenhealth\/smartwatchsyncable"},"doc://com.topstep.WomenHealth/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.topstep.WomenHealth\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SmartWatchSyncable"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SmartWatchSyncable"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SmartWatchSyncable"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/SmartWatchSyncable\/syncIfNeededWith(_:_:_:_:_:_:_:_:_:_:)","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/SmartWatchSyncable\/withFeatureOnWatch()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.topstep.WomenHealth\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SmartWatchSyncable"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1SmartWatchSyncable~1withFeatureOnWatch()\/title","value":"withFeatureOnWatch"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1SmartWatchSyncable~1withFeatureOnWatch()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"withFeatureOnWatch"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1SmartWatchSyncable~1syncIfNeededWith(_:_:_:_:_:_:_:_:_:_:)\/title","value":"syncIfNeededWith::::::::::"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1SmartWatchSyncable~1syncIfNeededWith(_:_:_:_:_:_:_:_:_:_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"syncIfNeededWith::::::::::"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1SmartWatchSyncable\/title","value":"SmartWatchSyncable"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1SmartWatchSyncable\/fragments","value":[{"kind":"identifier","text":"SmartWatchSyncable"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}