{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Themable"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/womenhealth\/themable"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/womenhealth\/themable"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.topstep.WomenHealth\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/Themable","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"皮肤协议"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Themable"}],"title":"Themable","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@WomenHealth@objc(pl)Themable","modules":[{"name":"WomenHealth"}],"navigatorTitle":[{"kind":"identifier","text":"Themable"}]},"hierarchy":{"paths":[["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/Themable\/colorWith(_:_:)","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/Themable\/imageWith(_:_:)"]}],"references":{"doc://com.topstep.WomenHealth/documentation/WomenHealth/Themable":{"role":"symbol","title":"Themable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Themable"}],"abstract":[{"type":"text","text":"皮肤协议"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/Themable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Themable"}],"url":"\/documentation\/womenhealth\/themable"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/Themable/colorWith(_:_:)":{"navigatorTitle":[{"kind":"identifier","text":"colorWith::"}],"role":"symbol","title":"colorWith(_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"colorWith"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ThemeColorKey","preciseIdentifier":"c:@M@WomenHealth@E@ThemeColorKey"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"UITraitCollection","preciseIdentifier":"c:objc(cs)UITraitCollection"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"根据 colorKey，traits返回皮肤颜色"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/Themable\/colorWith(_:_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/womenhealth\/themable\/colorwith(_:_:)"},"doc://com.topstep.WomenHealth/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.topstep.WomenHealth\/objc(pl)NSObject"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/Themable/imageWith(_:_:)":{"navigatorTitle":[{"kind":"identifier","text":"imageWith::"}],"role":"symbol","title":"imageWith(_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageWith"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ThemeImageKey","preciseIdentifier":"c:@M@WomenHealth@E@ThemeImageKey"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"UITraitCollection","preciseIdentifier":"c:objc(cs)UITraitCollection"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"根据 imageKey，traits返回皮肤图片"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/Themable\/imageWith(_:_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/womenhealth\/themable\/imagewith(_:_:)"},"doc://com.topstep.WomenHealth/documentation/WomenHealth":{"role":"collection","title":"WomenHealth","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","kind":"symbol","type":"topic","url":"\/documentation\/womenhealth"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"Themable"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"Themable"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"Themable"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/Themable\/colorWith(_:_:)","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/Themable\/imageWith(_:_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.topstep.WomenHealth\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Themable"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1Themable\/title","value":"Themable"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1Themable\/fragments","value":[{"kind":"identifier","text":"Themable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1Themable~1colorWith(_:_:)\/title","value":"colorWith::"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1Themable~1colorWith(_:_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"colorWith::"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1Themable~1imageWith(_:_:)\/title","value":"imageWith::"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1Themable~1imageWith(_:_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imageWith::"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}