{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThemeImageKey"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/womenhealth\/themeimagekey"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/womenhealth\/themeimagekey"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.topstep.WomenHealth\/s12CaseIterableP","doc:\/\/com.topstep.WomenHealth\/s23CustomStringConvertibleP","doc:\/\/com.topstep.WomenHealth\/SQ","doc:\/\/com.topstep.WomenHealth\/SH","doc:\/\/com.topstep.WomenHealth\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"图片Key定义"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThemeImageKey"}],"title":"ThemeImageKey","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@WomenHealth@E@ThemeImageKey","modules":[{"name":"WomenHealth"}],"navigatorTitle":[{"kind":"identifier","text":"ThemeImageKey"}]},"hierarchy":{"paths":[["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey\/icon_button_calendar_page_next","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey\/icon_button_calendar_page_prev","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey\/icon_chevron_down","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey\/icon_edc_date","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey\/icon_edc_today","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey\/icon_menstrual_behavior","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey\/icon_menstrual_date_begin","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey\/icon_navbar_settings","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey\/icon_ovulationday","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey\/icon_tablecell_accessory_checkmark","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey\/icon_tablecell_accessory_chevron_right"]},{"title":"Initializers","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey\/init(rawValue:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey\/comment","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey\/stringValue"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey\/CustomStringConvertible-Implementations","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey\/Equatable-Implementations","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.topstep.WomenHealth/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.topstep.WomenHealth\/SH"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/ThemeImageKey/CustomStringConvertible-Implementations":{"role":"collectionGroup","title":"CustomStringConvertible Implementations","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey\/CustomStringConvertible-Implementations","kind":"article","type":"topic","url":"\/documentation\/womenhealth\/themeimagekey\/customstringconvertible-implementations"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/ThemeImageKey/icon_edc_date":{"role":"symbol","title":"ThemeImageKey.icon_edc_date","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"icon_edc_date"}],"abstract":[{"type":"text","text":"预产期图标"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey\/icon_edc_date","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThemeImageKeyIcon_edc_date"}],"url":"\/documentation\/womenhealth\/themeimagekey\/icon_edc_date"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/ThemeImageKey/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/womenhealth\/themeimagekey\/rawrepresentable-implementations"},"doc://com.topstep.WomenHealth/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.topstep.WomenHealth\/SY"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/ThemeImageKey/icon_edc_today":{"role":"symbol","title":"ThemeImageKey.icon_edc_today","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"icon_edc_today"}],"abstract":[{"type":"text","text":"预产期当日图标"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey\/icon_edc_today","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThemeImageKeyIcon_edc_today"}],"url":"\/documentation\/womenhealth\/themeimagekey\/icon_edc_today"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/ThemeImageKey/icon_button_calendar_page_next":{"role":"symbol","title":"ThemeImageKey.icon_button_calendar_page_next","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"icon_button_calendar_page_next"}],"abstract":[{"type":"text","text":"日历下一页按钮图标"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey\/icon_button_calendar_page_next","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThemeImageKeyIcon_button_calendar_page_next"}],"url":"\/documentation\/womenhealth\/themeimagekey\/icon_button_calendar_page_next"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/ThemeImageKey/icon_tablecell_accessory_checkmark":{"role":"symbol","title":"ThemeImageKey.icon_tablecell_accessory_checkmark","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"icon_tablecell_accessory_checkmark"}],"abstract":[{"type":"text","text":"Table Cell checkmark 图标"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey\/icon_tablecell_accessory_checkmark","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThemeImageKeyIcon_tablecell_accessory_checkmark"}],"url":"\/documentation\/womenhealth\/themeimagekey\/icon_tablecell_accessory_checkmark"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/ThemeImageKey":{"role":"symbol","title":"ThemeImageKey","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThemeImageKey"}],"abstract":[{"type":"text","text":"图片Key定义"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThemeImageKey"}],"url":"\/documentation\/womenhealth\/themeimagekey"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/ThemeImageKey/icon_navbar_settings":{"role":"symbol","title":"ThemeImageKey.icon_navbar_settings","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"icon_navbar_settings"}],"abstract":[{"type":"text","text":"导航栏设置图标"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey\/icon_navbar_settings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThemeImageKeyIcon_navbar_settings"}],"url":"\/documentation\/womenhealth\/themeimagekey\/icon_navbar_settings"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/ThemeImageKey/stringValue":{"role":"symbol","title":"stringValue","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"stringValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"字符串"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey\/stringValue","kind":"symbol","type":"topic","url":"\/documentation\/womenhealth\/themeimagekey\/stringvalue"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/ThemeImageKey/icon_menstrual_date_begin":{"role":"symbol","title":"ThemeImageKey.icon_menstrual_date_begin","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"icon_menstrual_date_begin"}],"abstract":[{"type":"text","text":"最近一次月经开始日期图标"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey\/icon_menstrual_date_begin","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThemeImageKeyIcon_menstrual_date_begin"}],"url":"\/documentation\/womenhealth\/themeimagekey\/icon_menstrual_date_begin"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/ThemeImageKey/icon_button_calendar_page_prev":{"role":"symbol","title":"ThemeImageKey.icon_button_calendar_page_prev","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"icon_button_calendar_page_prev"}],"abstract":[{"type":"text","text":"日历上一页按钮图标"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey\/icon_button_calendar_page_prev","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThemeImageKeyIcon_button_calendar_page_prev"}],"url":"\/documentation\/womenhealth\/themeimagekey\/icon_button_calendar_page_prev"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/ThemeImageKey/icon_menstrual_behavior":{"role":"symbol","title":"ThemeImageKey.icon_menstrual_behavior","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"icon_menstrual_behavior"}],"abstract":[{"type":"text","text":"开始月经\/结束月经图标"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey\/icon_menstrual_behavior","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThemeImageKeyIcon_menstrual_behavior"}],"url":"\/documentation\/womenhealth\/themeimagekey\/icon_menstrual_behavior"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/ThemeImageKey/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/womenhealth\/themeimagekey\/equatable-implementations"},"doc://com.topstep.WomenHealth/s12CaseIterableP":{"type":"unresolvable","title":"Swift.CaseIterable","identifier":"doc:\/\/com.topstep.WomenHealth\/s12CaseIterableP"},"doc://com.topstep.WomenHealth/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.topstep.WomenHealth\/SQ"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/ThemeImageKey/icon_chevron_down":{"role":"symbol","title":"ThemeImageKey.icon_chevron_down","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"icon_chevron_down"}],"abstract":[{"type":"text","text":"chevron.down 图标"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey\/icon_chevron_down","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThemeImageKeyIcon_chevron_down"}],"url":"\/documentation\/womenhealth\/themeimagekey\/icon_chevron_down"},"doc://com.topstep.WomenHealth/documentation/WomenHealth":{"role":"collection","title":"WomenHealth","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","kind":"symbol","type":"topic","url":"\/documentation\/womenhealth"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/ThemeImageKey/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/womenhealth\/themeimagekey\/init(rawvalue:)"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/ThemeImageKey/icon_tablecell_accessory_chevron_right":{"role":"symbol","title":"ThemeImageKey.icon_tablecell_accessory_chevron_right","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"icon_tablecell_accessory_chevron_right"}],"abstract":[{"type":"text","text":"Table Cell chevron.right 图标"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey\/icon_tablecell_accessory_chevron_right","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThemeImageKeyIcon_tablecell_accessory_chevron_right"}],"url":"\/documentation\/womenhealth\/themeimagekey\/icon_tablecell_accessory_chevron_right"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/ThemeImageKey/comment":{"role":"symbol","title":"comment","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"comment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey\/comment","kind":"symbol","type":"topic","url":"\/documentation\/womenhealth\/themeimagekey\/comment"},"doc://com.topstep.WomenHealth/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.topstep.WomenHealth\/s23CustomStringConvertibleP"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/ThemeImageKey/icon_ovulationday":{"role":"symbol","title":"ThemeImageKey.icon_ovulationday","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"icon_ovulationday"}],"abstract":[{"type":"text","text":"排卵日图标"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey\/icon_ovulationday","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThemeImageKeyIcon_ovulationday"}],"url":"\/documentation\/womenhealth\/themeimagekey\/icon_ovulationday"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"ThemeImageKey"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ThemeImageKey"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ThemeImageKey"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey\/icon_button_calendar_page_next","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey\/icon_button_calendar_page_prev","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey\/icon_chevron_down","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey\/icon_edc_date","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey\/icon_edc_today","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey\/icon_menstrual_behavior","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey\/icon_menstrual_date_begin","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey\/icon_navbar_settings","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey\/icon_ovulationday","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey\/icon_tablecell_accessory_checkmark","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeImageKey\/icon_tablecell_accessory_chevron_right"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThemeImageKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeImageKey~1icon_edc_date\/title","value":"ThemeImageKeyIcon_edc_date"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeImageKey~1icon_edc_date\/fragments","value":[{"kind":"identifier","text":"ThemeImageKeyIcon_edc_date"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeImageKey~1icon_edc_today\/title","value":"ThemeImageKeyIcon_edc_today"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeImageKey~1icon_edc_today\/fragments","value":[{"kind":"identifier","text":"ThemeImageKeyIcon_edc_today"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeImageKey~1icon_button_calendar_page_next\/title","value":"ThemeImageKeyIcon_button_calendar_page_next"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeImageKey~1icon_button_calendar_page_next\/fragments","value":[{"kind":"identifier","text":"ThemeImageKeyIcon_button_calendar_page_next"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeImageKey~1icon_tablecell_accessory_checkmark\/title","value":"ThemeImageKeyIcon_tablecell_accessory_checkmark"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeImageKey~1icon_tablecell_accessory_checkmark\/fragments","value":[{"kind":"identifier","text":"ThemeImageKeyIcon_tablecell_accessory_checkmark"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeImageKey\/title","value":"ThemeImageKey"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeImageKey\/fragments","value":[{"kind":"identifier","text":"ThemeImageKey"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeImageKey~1icon_navbar_settings\/title","value":"ThemeImageKeyIcon_navbar_settings"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeImageKey~1icon_navbar_settings\/fragments","value":[{"kind":"identifier","text":"ThemeImageKeyIcon_navbar_settings"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeImageKey~1icon_menstrual_date_begin\/title","value":"ThemeImageKeyIcon_menstrual_date_begin"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeImageKey~1icon_menstrual_date_begin\/fragments","value":[{"kind":"identifier","text":"ThemeImageKeyIcon_menstrual_date_begin"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeImageKey~1icon_button_calendar_page_prev\/title","value":"ThemeImageKeyIcon_button_calendar_page_prev"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeImageKey~1icon_button_calendar_page_prev\/fragments","value":[{"kind":"identifier","text":"ThemeImageKeyIcon_button_calendar_page_prev"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeImageKey~1icon_menstrual_behavior\/title","value":"ThemeImageKeyIcon_menstrual_behavior"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeImageKey~1icon_menstrual_behavior\/fragments","value":[{"kind":"identifier","text":"ThemeImageKeyIcon_menstrual_behavior"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeImageKey~1icon_chevron_down\/title","value":"ThemeImageKeyIcon_chevron_down"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeImageKey~1icon_chevron_down\/fragments","value":[{"kind":"identifier","text":"ThemeImageKeyIcon_chevron_down"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeImageKey~1icon_tablecell_accessory_chevron_right\/title","value":"ThemeImageKeyIcon_tablecell_accessory_chevron_right"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeImageKey~1icon_tablecell_accessory_chevron_right\/fragments","value":[{"kind":"identifier","text":"ThemeImageKeyIcon_tablecell_accessory_chevron_right"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeImageKey~1icon_ovulationday\/title","value":"ThemeImageKeyIcon_ovulationday"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeImageKey~1icon_ovulationday\/fragments","value":[{"kind":"identifier","text":"ThemeImageKeyIcon_ovulationday"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}