{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThemeColorKey"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/womenhealth\/themecolorkey"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/womenhealth\/themecolorkey"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.topstep.WomenHealth\/s12CaseIterableP","doc:\/\/com.topstep.WomenHealth\/s23CustomStringConvertibleP","doc:\/\/com.topstep.WomenHealth\/SQ","doc:\/\/com.topstep.WomenHealth\/SH","doc:\/\/com.topstep.WomenHealth\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"颜色Key定义"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThemeColorKey"}],"title":"ThemeColorKey","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@WomenHealth@E@ThemeColorKey","modules":[{"name":"WomenHealth"}],"navigatorTitle":[{"kind":"identifier","text":"ThemeColorKey"}]},"hierarchy":{"paths":[["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/brand","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/button_title_destructive","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/calendar_background_default","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/calendar_date_selected_background_default","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/early_pregnancy_indicator","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/late_pregnancy_indicator","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/menstrual_phase_indicator","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/mid_pregnancy_indicator","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/ovulation_day_indicator","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/ovulation_phase_indicator","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/safety_phase_indicator","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/separator","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/table_background_default","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/tablecell_accessory_chevron_right","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/tablecell_background_default","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/tablecell_background_secondary"]},{"title":"Initializers","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/init(rawValue:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/comment","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/stringValue"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/CustomStringConvertible-Implementations","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/Equatable-Implementations","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.topstep.WomenHealth/documentation/WomenHealth/ThemeColorKey/tablecell_background_secondary":{"role":"symbol","title":"ThemeColorKey.tablecell_background_secondary","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tablecell_background_secondary"}],"abstract":[{"type":"text","text":"Secondary Table Cell 背景色"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/tablecell_background_secondary","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThemeColorKeyTablecell_background_secondary"}],"url":"\/documentation\/womenhealth\/themecolorkey\/tablecell_background_secondary"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/ThemeColorKey/ovulation_phase_indicator":{"role":"symbol","title":"ThemeColorKey.ovulation_phase_indicator","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ovulation_phase_indicator"}],"abstract":[{"type":"text","text":"排卵期指示色"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/ovulation_phase_indicator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThemeColorKeyOvulation_phase_indicator"}],"url":"\/documentation\/womenhealth\/themecolorkey\/ovulation_phase_indicator"},"doc://com.topstep.WomenHealth/documentation/WomenHealth":{"role":"collection","title":"WomenHealth","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","kind":"symbol","type":"topic","url":"\/documentation\/womenhealth"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/ThemeColorKey/CustomStringConvertible-Implementations":{"role":"collectionGroup","title":"CustomStringConvertible Implementations","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/CustomStringConvertible-Implementations","kind":"article","type":"topic","url":"\/documentation\/womenhealth\/themecolorkey\/customstringconvertible-implementations"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/ThemeColorKey/comment":{"role":"symbol","title":"comment","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"comment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/comment","kind":"symbol","type":"topic","url":"\/documentation\/womenhealth\/themecolorkey\/comment"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/ThemeColorKey/calendar_background_default":{"role":"symbol","title":"ThemeColorKey.calendar_background_default","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"calendar_background_default"}],"abstract":[{"type":"text","text":"日历背景色"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/calendar_background_default","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThemeColorKeyCalendar_background_default"}],"url":"\/documentation\/womenhealth\/themecolorkey\/calendar_background_default"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/ThemeColorKey/early_pregnancy_indicator":{"role":"symbol","title":"ThemeColorKey.early_pregnancy_indicator","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"early_pregnancy_indicator"}],"abstract":[{"type":"text","text":"孕早期指示色"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/early_pregnancy_indicator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThemeColorKeyEarly_pregnancy_indicator"}],"url":"\/documentation\/womenhealth\/themecolorkey\/early_pregnancy_indicator"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/ThemeColorKey/menstrual_phase_indicator":{"role":"symbol","title":"ThemeColorKey.menstrual_phase_indicator","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"menstrual_phase_indicator"}],"abstract":[{"type":"text","text":"月经期指示色"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/menstrual_phase_indicator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThemeColorKeyMenstrual_phase_indicator"}],"url":"\/documentation\/womenhealth\/themecolorkey\/menstrual_phase_indicator"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/ThemeColorKey":{"role":"symbol","title":"ThemeColorKey","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThemeColorKey"}],"abstract":[{"type":"text","text":"颜色Key定义"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThemeColorKey"}],"url":"\/documentation\/womenhealth\/themecolorkey"},"doc://com.topstep.WomenHealth/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.topstep.WomenHealth\/SQ"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/ThemeColorKey/tablecell_background_default":{"role":"symbol","title":"ThemeColorKey.tablecell_background_default","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tablecell_background_default"}],"abstract":[{"type":"text","text":"Table Cell 背景色"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/tablecell_background_default","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThemeColorKeyTablecell_background_default"}],"url":"\/documentation\/womenhealth\/themecolorkey\/tablecell_background_default"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/ThemeColorKey/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/womenhealth\/themecolorkey\/init(rawvalue:)"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/ThemeColorKey/mid_pregnancy_indicator":{"role":"symbol","title":"ThemeColorKey.mid_pregnancy_indicator","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mid_pregnancy_indicator"}],"abstract":[{"type":"text","text":"孕中期指示色"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/mid_pregnancy_indicator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThemeColorKeyMid_pregnancy_indicator"}],"url":"\/documentation\/womenhealth\/themecolorkey\/mid_pregnancy_indicator"},"doc://com.topstep.WomenHealth/s12CaseIterableP":{"type":"unresolvable","title":"Swift.CaseIterable","identifier":"doc:\/\/com.topstep.WomenHealth\/s12CaseIterableP"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/ThemeColorKey/late_pregnancy_indicator":{"role":"symbol","title":"ThemeColorKey.late_pregnancy_indicator","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"late_pregnancy_indicator"}],"abstract":[{"type":"text","text":"孕晚期指示色"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/late_pregnancy_indicator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThemeColorKeyLate_pregnancy_indicator"}],"url":"\/documentation\/womenhealth\/themecolorkey\/late_pregnancy_indicator"},"doc://com.topstep.WomenHealth/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.topstep.WomenHealth\/SH"},"doc://com.topstep.WomenHealth/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.topstep.WomenHealth\/s23CustomStringConvertibleP"},"doc://com.topstep.WomenHealth/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.topstep.WomenHealth\/SY"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/ThemeColorKey/button_title_destructive":{"role":"symbol","title":"ThemeColorKey.button_title_destructive","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"button_title_destructive"}],"abstract":[{"type":"text","text":"警示(重要\/凸显)按钮标题颜色"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/button_title_destructive","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThemeColorKeyButton_title_destructive"}],"url":"\/documentation\/womenhealth\/themecolorkey\/button_title_destructive"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/ThemeColorKey/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/womenhealth\/themecolorkey\/equatable-implementations"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/ThemeColorKey/separator":{"role":"symbol","title":"ThemeColorKey.separator","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"separator"}],"abstract":[{"type":"text","text":"分割线"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/separator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThemeColorKeySeparator"}],"url":"\/documentation\/womenhealth\/themecolorkey\/separator"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/ThemeColorKey/brand":{"role":"symbol","title":"ThemeColorKey.brand","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"brand"}],"abstract":[{"type":"text","text":"品牌色"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/brand","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThemeColorKeyBrand"}],"url":"\/documentation\/womenhealth\/themecolorkey\/brand"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/ThemeColorKey/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/womenhealth\/themecolorkey\/rawrepresentable-implementations"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/ThemeColorKey/calendar_date_selected_background_default":{"role":"symbol","title":"ThemeColorKey.calendar_date_selected_background_default","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"calendar_date_selected_background_default"}],"abstract":[{"type":"text","text":"选中日期背景色"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/calendar_date_selected_background_default","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThemeColorKeyCalendar_date_selected_background_default"}],"url":"\/documentation\/womenhealth\/themecolorkey\/calendar_date_selected_background_default"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/ThemeColorKey/stringValue":{"role":"symbol","title":"stringValue","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"stringValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"字符串"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/stringValue","kind":"symbol","type":"topic","url":"\/documentation\/womenhealth\/themecolorkey\/stringvalue"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/ThemeColorKey/tablecell_accessory_chevron_right":{"role":"symbol","title":"ThemeColorKey.tablecell_accessory_chevron_right","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tablecell_accessory_chevron_right"}],"abstract":[{"type":"text","text":"Table Cell chevron.right 图标颜色"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/tablecell_accessory_chevron_right","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThemeColorKeyTablecell_accessory_chevron_right"}],"url":"\/documentation\/womenhealth\/themecolorkey\/tablecell_accessory_chevron_right"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/ThemeColorKey/ovulation_day_indicator":{"role":"symbol","title":"ThemeColorKey.ovulation_day_indicator","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ovulation_day_indicator"}],"abstract":[{"type":"text","text":"排卵日指示色"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/ovulation_day_indicator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThemeColorKeyOvulation_day_indicator"}],"url":"\/documentation\/womenhealth\/themecolorkey\/ovulation_day_indicator"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/ThemeColorKey/table_background_default":{"role":"symbol","title":"ThemeColorKey.table_background_default","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"table_background_default"}],"abstract":[{"type":"text","text":"UITable背景色"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/table_background_default","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThemeColorKeyTable_background_default"}],"url":"\/documentation\/womenhealth\/themecolorkey\/table_background_default"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/ThemeColorKey/safety_phase_indicator":{"role":"symbol","title":"ThemeColorKey.safety_phase_indicator","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"safety_phase_indicator"}],"abstract":[{"type":"text","text":"安全期指示色"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/safety_phase_indicator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThemeColorKeySafety_phase_indicator"}],"url":"\/documentation\/womenhealth\/themecolorkey\/safety_phase_indicator"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"ThemeColorKey"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ThemeColorKey"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ThemeColorKey"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/brand","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/button_title_destructive","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/calendar_background_default","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/calendar_date_selected_background_default","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/early_pregnancy_indicator","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/late_pregnancy_indicator","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/menstrual_phase_indicator","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/mid_pregnancy_indicator","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/ovulation_day_indicator","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/ovulation_phase_indicator","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/safety_phase_indicator","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/separator","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/table_background_default","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/tablecell_accessory_chevron_right","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/tablecell_background_default","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey\/tablecell_background_secondary"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThemeColorKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeColorKey~1tablecell_background_secondary\/title","value":"ThemeColorKeyTablecell_background_secondary"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeColorKey~1tablecell_background_secondary\/fragments","value":[{"kind":"identifier","text":"ThemeColorKeyTablecell_background_secondary"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeColorKey~1ovulation_phase_indicator\/title","value":"ThemeColorKeyOvulation_phase_indicator"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeColorKey~1ovulation_phase_indicator\/fragments","value":[{"kind":"identifier","text":"ThemeColorKeyOvulation_phase_indicator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeColorKey~1calendar_background_default\/title","value":"ThemeColorKeyCalendar_background_default"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeColorKey~1calendar_background_default\/fragments","value":[{"kind":"identifier","text":"ThemeColorKeyCalendar_background_default"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeColorKey~1early_pregnancy_indicator\/title","value":"ThemeColorKeyEarly_pregnancy_indicator"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeColorKey~1early_pregnancy_indicator\/fragments","value":[{"kind":"identifier","text":"ThemeColorKeyEarly_pregnancy_indicator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeColorKey~1menstrual_phase_indicator\/title","value":"ThemeColorKeyMenstrual_phase_indicator"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeColorKey~1menstrual_phase_indicator\/fragments","value":[{"kind":"identifier","text":"ThemeColorKeyMenstrual_phase_indicator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeColorKey\/title","value":"ThemeColorKey"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeColorKey\/fragments","value":[{"kind":"identifier","text":"ThemeColorKey"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeColorKey~1tablecell_background_default\/title","value":"ThemeColorKeyTablecell_background_default"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeColorKey~1tablecell_background_default\/fragments","value":[{"kind":"identifier","text":"ThemeColorKeyTablecell_background_default"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeColorKey~1mid_pregnancy_indicator\/title","value":"ThemeColorKeyMid_pregnancy_indicator"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeColorKey~1mid_pregnancy_indicator\/fragments","value":[{"kind":"identifier","text":"ThemeColorKeyMid_pregnancy_indicator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeColorKey~1late_pregnancy_indicator\/title","value":"ThemeColorKeyLate_pregnancy_indicator"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeColorKey~1late_pregnancy_indicator\/fragments","value":[{"kind":"identifier","text":"ThemeColorKeyLate_pregnancy_indicator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeColorKey~1button_title_destructive\/title","value":"ThemeColorKeyButton_title_destructive"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeColorKey~1button_title_destructive\/fragments","value":[{"kind":"identifier","text":"ThemeColorKeyButton_title_destructive"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeColorKey~1separator\/title","value":"ThemeColorKeySeparator"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeColorKey~1separator\/fragments","value":[{"kind":"identifier","text":"ThemeColorKeySeparator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeColorKey~1brand\/title","value":"ThemeColorKeyBrand"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeColorKey~1brand\/fragments","value":[{"kind":"identifier","text":"ThemeColorKeyBrand"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeColorKey~1calendar_date_selected_background_default\/title","value":"ThemeColorKeyCalendar_date_selected_background_default"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeColorKey~1calendar_date_selected_background_default\/fragments","value":[{"kind":"identifier","text":"ThemeColorKeyCalendar_date_selected_background_default"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeColorKey~1tablecell_accessory_chevron_right\/title","value":"ThemeColorKeyTablecell_accessory_chevron_right"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeColorKey~1tablecell_accessory_chevron_right\/fragments","value":[{"kind":"identifier","text":"ThemeColorKeyTablecell_accessory_chevron_right"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeColorKey~1ovulation_day_indicator\/title","value":"ThemeColorKeyOvulation_day_indicator"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeColorKey~1ovulation_day_indicator\/fragments","value":[{"kind":"identifier","text":"ThemeColorKeyOvulation_day_indicator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeColorKey~1table_background_default\/title","value":"ThemeColorKeyTable_background_default"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeColorKey~1table_background_default\/fragments","value":[{"kind":"identifier","text":"ThemeColorKeyTable_background_default"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeColorKey~1safety_phase_indicator\/title","value":"ThemeColorKeySafety_phase_indicator"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeColorKey~1safety_phase_indicator\/fragments","value":[{"kind":"identifier","text":"ThemeColorKeySafety_phase_indicator"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}