{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"WomenHealthPhase"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/womenhealth\/womenhealthphase"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/womenhealth\/womenhealthphase"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.topstep.WomenHealth\/s23CustomStringConvertibleP","doc:\/\/com.topstep.WomenHealth\/SQ","doc:\/\/com.topstep.WomenHealth\/SH","doc:\/\/com.topstep.WomenHealth\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthPhase","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"女性健康阶段"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"WomenHealthPhase"}],"role":"symbol","title":"WomenHealthPhase","roleHeading":"Enumeration","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"WomenHealthPhase"}],"symbolKind":"enum","externalID":"c:@M@WomenHealth@E@WomenHealthPhase","modules":[{"name":"WomenHealth"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"11.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthPhase\/menses","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthPhase\/ovulation","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthPhase\/safty","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthPhase\/unknown"]},{"title":"Initializers","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthPhase\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthPhase\/CustomStringConvertible-Implementations","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthPhase\/Equatable-Implementations","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthPhase\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.topstep.WomenHealth/documentation/WomenHealth/WomenHealthPhase/ovulation":{"role":"symbol","title":"WomenHealthPhase.ovulation","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ovulation"}],"abstract":[{"type":"text","text":"排卵期"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthPhase\/ovulation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WomenHealthPhaseOvulation"}],"url":"\/documentation\/womenhealth\/womenhealthphase\/ovulation"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/WomenHealthPhase/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthPhase\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/womenhealth\/womenhealthphase\/rawrepresentable-implementations"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/WomenHealthPhase/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthPhase\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/womenhealth\/womenhealthphase\/init(rawvalue:)"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/WomenHealthPhase/menses":{"role":"symbol","title":"WomenHealthPhase.menses","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"menses"}],"abstract":[{"type":"text","text":"月经期"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthPhase\/menses","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WomenHealthPhaseMenses"}],"url":"\/documentation\/womenhealth\/womenhealthphase\/menses"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/WomenHealthPhase/safty":{"role":"symbol","title":"WomenHealthPhase.safty","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"safty"}],"abstract":[{"type":"text","text":"安全期"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthPhase\/safty","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WomenHealthPhaseSafty"}],"url":"\/documentation\/womenhealth\/womenhealthphase\/safty"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/WomenHealthPhase":{"role":"symbol","title":"WomenHealthPhase","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"WomenHealthPhase"}],"abstract":[{"type":"text","text":"女性健康阶段"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthPhase","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WomenHealthPhase"}],"url":"\/documentation\/womenhealth\/womenhealthphase"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/WomenHealthPhase/CustomStringConvertible-Implementations":{"role":"collectionGroup","title":"CustomStringConvertible Implementations","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthPhase\/CustomStringConvertible-Implementations","kind":"article","type":"topic","url":"\/documentation\/womenhealth\/womenhealthphase\/customstringconvertible-implementations"},"doc://com.topstep.WomenHealth/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.topstep.WomenHealth\/s23CustomStringConvertibleP"},"doc://com.topstep.WomenHealth/documentation/WomenHealth":{"role":"collection","title":"WomenHealth","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","kind":"symbol","type":"topic","url":"\/documentation\/womenhealth"},"doc://com.topstep.WomenHealth/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.topstep.WomenHealth\/SY"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/WomenHealthPhase/unknown":{"role":"symbol","title":"WomenHealthPhase.unknown","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"abstract":[{"type":"text","text":"未知"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthPhase\/unknown","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WomenHealthPhaseUnknown"}],"url":"\/documentation\/womenhealth\/womenhealthphase\/unknown"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/WomenHealthPhase/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthPhase\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/womenhealth\/womenhealthphase\/equatable-implementations"},"doc://com.topstep.WomenHealth/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.topstep.WomenHealth\/SQ"},"doc://com.topstep.WomenHealth/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.topstep.WomenHealth\/SH"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"WomenHealthPhase"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"WomenHealthPhase"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"WomenHealthPhase"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthPhase\/menses","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthPhase\/ovulation","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthPhase\/safty","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthPhase\/unknown"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"WomenHealthPhase"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthPhase~1ovulation\/title","value":"WomenHealthPhaseOvulation"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthPhase~1ovulation\/fragments","value":[{"kind":"identifier","text":"WomenHealthPhaseOvulation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthPhase~1menses\/title","value":"WomenHealthPhaseMenses"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthPhase~1menses\/fragments","value":[{"kind":"identifier","text":"WomenHealthPhaseMenses"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthPhase~1safty\/title","value":"WomenHealthPhaseSafty"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthPhase~1safty\/fragments","value":[{"kind":"identifier","text":"WomenHealthPhaseSafty"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthPhase\/title","value":"WomenHealthPhase"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthPhase\/fragments","value":[{"kind":"identifier","text":"WomenHealthPhase"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthPhase~1unknown\/title","value":"WomenHealthPhaseUnknown"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthPhase~1unknown\/fragments","value":[{"kind":"identifier","text":"WomenHealthPhaseUnknown"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}