{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WomenHealthNotifications"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/womenhealth\/womenhealthnotifications"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/womenhealth\/womenhealthnotifications"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.topstep.WomenHealth\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.topstep.WomenHealth\/objc(pl)NSObject","doc:\/\/com.topstep.WomenHealth\/s7CVarArgP","doc:\/\/com.topstep.WomenHealth\/s28CustomDebugStringConvertibleP","doc:\/\/com.topstep.WomenHealth\/s23CustomStringConvertibleP","doc:\/\/com.topstep.WomenHealth\/SQ","doc:\/\/com.topstep.WomenHealth\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthNotifications","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"女性健康模块通知"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WomenHealthNotifications"}],"title":"WomenHealthNotifications","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@WomenHealth@objc(cs)WomenHealthNotifications","modules":[{"name":"WomenHealth"}],"navigatorTitle":[{"kind":"identifier","text":"WomenHealthNotifications"}]},"hierarchy":{"paths":[["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth"]]},"topicSections":[{"title":"Type Properties","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthNotifications\/modeDidChangedNotification"]}],"references":{"doc://com.topstep.WomenHealth/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.topstep.WomenHealth\/s7CVarArgP"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/WomenHealthNotifications":{"role":"symbol","title":"WomenHealthNotifications","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WomenHealthNotifications"}],"abstract":[{"type":"text","text":"女性健康模块通知"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthNotifications","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WomenHealthNotifications"}],"url":"\/documentation\/womenhealth\/womenhealthnotifications"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/WomenHealthNotifications/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthNotifications\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/womenhealth\/womenhealthnotifications\/init"},"doc://com.topstep.WomenHealth/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.topstep.WomenHealth\/SQ"},"doc://com.topstep.WomenHealth/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.topstep.WomenHealth\/s28CustomDebugStringConvertibleP"},"doc://com.topstep.WomenHealth/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.topstep.WomenHealth\/s23CustomStringConvertibleP"},"doc://com.topstep.WomenHealth/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.topstep.WomenHealth\/objc(pl)NSObject"},"doc://com.topstep.WomenHealth/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.topstep.WomenHealth\/objc(cs)NSObject"},"doc://com.topstep.WomenHealth/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.topstep.WomenHealth\/SH"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/WomenHealthNotifications/modeDidChangedNotification":{"role":"symbol","title":"modeDidChangedNotification","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"modeDidChangedNotification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Notification","preciseIdentifier":"s:10Foundation12NotificationV"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Name","preciseIdentifier":"s:10Foundation12NotificationV4Namea"}],"abstract":[{"type":"text","text":"女性健康当前模式改变通知"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthNotifications\/modeDidChangedNotification","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"modeDidChangedNotification"}],"url":"\/documentation\/womenhealth\/womenhealthnotifications\/modedidchangednotification"},"doc://com.topstep.WomenHealth/documentation/WomenHealth":{"role":"collection","title":"WomenHealth","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","kind":"symbol","type":"topic","url":"\/documentation\/womenhealth"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"WomenHealthNotifications"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"WomenHealthNotifications"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"WomenHealthNotifications"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthNotifications\/init"]},{"title":"Type Properties","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthNotifications\/modeDidChangedNotification"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.topstep.WomenHealth\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"WomenHealthNotifications"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthNotifications\/title","value":"WomenHealthNotifications"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthNotifications\/fragments","value":[{"kind":"identifier","text":"WomenHealthNotifications"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthNotifications~1modeDidChangedNotification\/title","value":"modeDidChangedNotification"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthNotifications~1modeDidChangedNotification\/fragments","value":[{"kind":"identifier","text":"modeDidChangedNotification"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}