{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WomenHealthModule"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/womenhealth\/womenhealthmodule"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/womenhealth\/womenhealthmodule"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.topstep.WomenHealth\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.topstep.WomenHealth\/objc(pl)NSObject","doc:\/\/com.topstep.WomenHealth\/s7CVarArgP","doc:\/\/com.topstep.WomenHealth\/s28CustomDebugStringConvertibleP","doc:\/\/com.topstep.WomenHealth\/s23CustomStringConvertibleP","doc:\/\/com.topstep.WomenHealth\/SQ","doc:\/\/com.topstep.WomenHealth\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthModule","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"女性健康模块"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"WomenHealthModule"}],"role":"symbol","title":"WomenHealthModule","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WomenHealthModule"}],"symbolKind":"class","externalID":"c:@M@WomenHealth@objc(cs)WomenHealthModule","modules":[{"name":"WomenHealth"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"11.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthModule\/userId"]},{"title":"Type Methods","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthModule\/enterCurrentModeHome(from:)","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthModule\/enterMainSettings(from:)","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthModule\/exportDB(_:)","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthModule\/localizableStrings()","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthModule\/notifySmartWatchWomenHealthFeatureAvailableChanged()","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthModule\/setWatchSyncServiceProvider(_:)","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthModule\/start(with:_:_:_:)","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthModule\/syncModeSettingsToSmartWatchIfNeeded()"]}],"references":{"doc://com.topstep.WomenHealth/documentation/WomenHealth/WomenHealthModule/exportDB(_:)":{"role":"symbol","title":"exportDB(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"exportDB"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"导出女性健康数据库"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthModule\/exportDB(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"exportDB:"}],"url":"\/documentation\/womenhealth\/womenhealthmodule\/exportdb(_:)"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/WomenHealthModule/enterCurrentModeHome(from:)":{"role":"symbol","title":"enterCurrentModeHome(from:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enterCurrentModeHome"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"进入当前女性健康模式(月经期\/备孕期\/怀孕期)主页"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthModule\/enterCurrentModeHome(from:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enterCurrentModeHomeFrom:"}],"url":"\/documentation\/womenhealth\/womenhealthmodule\/entercurrentmodehome(from:)"},"doc://com.topstep.WomenHealth/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.topstep.WomenHealth\/objc(pl)NSObject"},"doc://com.topstep.WomenHealth/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.topstep.WomenHealth\/s7CVarArgP"},"doc://com.topstep.WomenHealth/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.topstep.WomenHealth\/objc(cs)NSObject"},"doc://com.topstep.WomenHealth/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.topstep.WomenHealth\/SQ"},"doc://com.topstep.WomenHealth/documentation/WomenHealth":{"role":"collection","title":"WomenHealth","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","kind":"symbol","type":"topic","url":"\/documentation\/womenhealth"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/WomenHealthModule/setWatchSyncServiceProvider(_:)":{"role":"symbol","title":"setWatchSyncServiceProvider(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setWatchSyncServiceProvider"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SmartWatchSyncable","preciseIdentifier":"c:@M@WomenHealth@objc(pl)SmartWatchSyncable"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"设置同步女性健康配置给手表服务提供者"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthModule\/setWatchSyncServiceProvider(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setWatchSyncServiceProvider:"}],"url":"\/documentation\/womenhealth\/womenhealthmodule\/setwatchsyncserviceprovider(_:)"},"doc://com.topstep.WomenHealth/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.topstep.WomenHealth\/SH"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/WomenHealthModule/start(with:_:_:_:)":{"role":"symbol","title":"start(with:_:_:_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Localizable","preciseIdentifier":"c:@M@WomenHealth@objc(pl)Localizable"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Themable","preciseIdentifier":"c:@M@WomenHealth@objc(pl)Themable"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Loggable","preciseIdentifier":"c:@M@WomenHealth@objc(pl)Loggable"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"初始化女性健康模块"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthModule\/start(with:_:_:_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startWith::::"}],"url":"\/documentation\/womenhealth\/womenhealthmodule\/start(with:_:_:_:)"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/WomenHealthModule/notifySmartWatchWomenHealthFeatureAvailableChanged()":{"role":"symbol","title":"notifySmartWatchWomenHealthFeatureAvailableChanged()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"notifySmartWatchWomenHealthFeatureAvailableChanged"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"通知女性健康模块手表女性健康功能可用状态发生改变"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthModule\/notifySmartWatchWomenHealthFeatureAvailableChanged()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"notifySmartWatchWomenHealthFeatureAvailableChanged"}],"url":"\/documentation\/womenhealth\/womenhealthmodule\/notifysmartwatchwomenhealthfeatureavailablechanged()"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/WomenHealthModule/userId":{"role":"symbol","title":"userId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"用户Id"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthModule\/userId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userId"}],"url":"\/documentation\/womenhealth\/womenhealthmodule\/userid"},"doc://com.topstep.WomenHealth/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.topstep.WomenHealth\/s28CustomDebugStringConvertibleP"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/WomenHealthModule/enterMainSettings(from:)":{"role":"symbol","title":"enterMainSettings(from:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enterMainSettings"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"进入主设置界面"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthModule\/enterMainSettings(from:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enterMainSettingsFrom:"}],"url":"\/documentation\/womenhealth\/womenhealthmodule\/entermainsettings(from:)"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/WomenHealthModule":{"role":"symbol","title":"WomenHealthModule","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WomenHealthModule"}],"abstract":[{"type":"text","text":"女性健康模块"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthModule","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WomenHealthModule"}],"url":"\/documentation\/womenhealth\/womenhealthmodule"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/WomenHealthModule/localizableStrings()":{"role":"symbol","title":"localizableStrings()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"localizableStrings"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"可本地化的字符串数组"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthModule\/localizableStrings()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"localizableStrings"}],"url":"\/documentation\/womenhealth\/womenhealthmodule\/localizablestrings()"},"doc://com.topstep.WomenHealth/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.topstep.WomenHealth\/s23CustomStringConvertibleP"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/WomenHealthModule/syncModeSettingsToSmartWatchIfNeeded()":{"role":"symbol","title":"syncModeSettingsToSmartWatchIfNeeded()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"syncModeSettingsToSmartWatchIfNeeded"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"若有必要将女性健康当前模式配置同步给手表"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthModule\/syncModeSettingsToSmartWatchIfNeeded()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"syncModeSettingsToSmartWatchIfNeeded"}],"url":"\/documentation\/womenhealth\/womenhealthmodule\/syncmodesettingstosmartwatchifneeded()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"WomenHealthModule"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"WomenHealthModule"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"WomenHealthModule"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthModule\/userId"]},{"title":"Type Methods","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthModule\/enterCurrentModeHome(from:)","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthModule\/enterMainSettings(from:)","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthModule\/exportDB(_:)","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthModule\/localizableStrings()","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthModule\/notifySmartWatchWomenHealthFeatureAvailableChanged()","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthModule\/setWatchSyncServiceProvider(_:)","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthModule\/start(with:_:_:_:)","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthModule\/syncModeSettingsToSmartWatchIfNeeded()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.topstep.WomenHealth\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"WomenHealthModule"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthModule~1exportDB(_:)\/title","value":"exportDB:"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthModule~1exportDB(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"exportDB:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthModule~1enterCurrentModeHome(from:)\/title","value":"enterCurrentModeHomeFrom:"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthModule~1enterCurrentModeHome(from:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"enterCurrentModeHomeFrom:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthModule~1setWatchSyncServiceProvider(_:)\/title","value":"setWatchSyncServiceProvider:"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthModule~1setWatchSyncServiceProvider(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setWatchSyncServiceProvider:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthModule~1start(with:_:_:_:)\/title","value":"startWith::::"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthModule~1start(with:_:_:_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startWith::::"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthModule~1notifySmartWatchWomenHealthFeatureAvailableChanged()\/title","value":"notifySmartWatchWomenHealthFeatureAvailableChanged"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthModule~1notifySmartWatchWomenHealthFeatureAvailableChanged()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"notifySmartWatchWomenHealthFeatureAvailableChanged"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthModule~1userId\/title","value":"userId"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthModule~1userId\/fragments","value":[{"kind":"identifier","text":"userId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthModule~1enterMainSettings(from:)\/title","value":"enterMainSettingsFrom:"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthModule~1enterMainSettings(from:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"enterMainSettingsFrom:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthModule\/title","value":"WomenHealthModule"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthModule\/fragments","value":[{"kind":"identifier","text":"WomenHealthModule"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthModule~1localizableStrings()\/title","value":"localizableStrings"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthModule~1localizableStrings()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"localizableStrings"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthModule~1syncModeSettingsToSmartWatchIfNeeded()\/title","value":"syncModeSettingsToSmartWatchIfNeeded"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthModule~1syncModeSettingsToSmartWatchIfNeeded()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"syncModeSettingsToSmartWatchIfNeeded"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}