{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"WomenHealthMode"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/womenhealth\/womenhealthmode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/womenhealth\/womenhealthmode"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.topstep.WomenHealth\/s23CustomStringConvertibleP","doc:\/\/com.topstep.WomenHealth\/Se","doc:\/\/com.topstep.WomenHealth\/SE","doc:\/\/com.topstep.WomenHealth\/SQ","doc:\/\/com.topstep.WomenHealth\/SH","doc:\/\/com.topstep.WomenHealth\/SY","doc:\/\/com.topstep.WomenHealth\/9WCDBSwift17ColumnCodableBaseP","doc:\/\/com.topstep.WomenHealth\/9WCDBSwift15ColumnDecodableP","doc:\/\/com.topstep.WomenHealth\/9WCDBSwift15ColumnEncodableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthMode","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"女性健康模式"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"WomenHealthMode"}],"role":"symbol","title":"WomenHealthMode","roleHeading":"Enumeration","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"WomenHealthMode"}],"symbolKind":"enum","externalID":"c:@M@WomenHealth@E@WomenHealthMode","modules":[{"name":"WomenHealth"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"11.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthMode\/menses","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthMode\/none","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthMode\/pregnancy","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthMode\/pregnancy_prepare"]},{"title":"Initializers","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthMode\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthMode\/ColumnCodableBase-Implementations","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthMode\/ColumnDecodable-Implementations","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthMode\/ColumnEncodable-Implementations","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthMode\/CustomStringConvertible-Implementations","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthMode\/Equatable-Implementations","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthMode\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.topstep.WomenHealth/documentation/WomenHealth/WomenHealthMode/CustomStringConvertible-Implementations":{"role":"collectionGroup","title":"CustomStringConvertible Implementations","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthMode\/CustomStringConvertible-Implementations","kind":"article","type":"topic","url":"\/documentation\/womenhealth\/womenhealthmode\/customstringconvertible-implementations"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/WomenHealthMode/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthMode\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/womenhealth\/womenhealthmode\/init(rawvalue:)"},"doc://com.topstep.WomenHealth/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.topstep.WomenHealth\/Se"},"doc://com.topstep.WomenHealth/9WCDBSwift15ColumnEncodableP":{"type":"unresolvable","title":"WCDBSwift.ColumnEncodable","identifier":"doc:\/\/com.topstep.WomenHealth\/9WCDBSwift15ColumnEncodableP"},"doc://com.topstep.WomenHealth/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.topstep.WomenHealth\/s23CustomStringConvertibleP"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/WomenHealthMode/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthMode\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/womenhealth\/womenhealthmode\/rawrepresentable-implementations"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/WomenHealthMode/pregnancy_prepare":{"role":"symbol","title":"WomenHealthMode.pregnancy_prepare","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pregnancy_prepare"}],"abstract":[{"type":"text","text":"备孕模式"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthMode\/pregnancy_prepare","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WomenHealthModePregnancy_prepare"}],"url":"\/documentation\/womenhealth\/womenhealthmode\/pregnancy_prepare"},"doc://com.topstep.WomenHealth/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.topstep.WomenHealth\/SY"},"doc://com.topstep.WomenHealth/9WCDBSwift17ColumnCodableBaseP":{"type":"unresolvable","title":"WCDBSwift.ColumnCodableBase","identifier":"doc:\/\/com.topstep.WomenHealth\/9WCDBSwift17ColumnCodableBaseP"},"doc://com.topstep.WomenHealth/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.topstep.WomenHealth\/SH"},"doc://com.topstep.WomenHealth/documentation/WomenHealth":{"role":"collection","title":"WomenHealth","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","kind":"symbol","type":"topic","url":"\/documentation\/womenhealth"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/WomenHealthMode/pregnancy":{"role":"symbol","title":"WomenHealthMode.pregnancy","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pregnancy"}],"abstract":[{"type":"text","text":"怀孕模式"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthMode\/pregnancy","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WomenHealthModePregnancy"}],"url":"\/documentation\/womenhealth\/womenhealthmode\/pregnancy"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/WomenHealthMode":{"role":"symbol","title":"WomenHealthMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"WomenHealthMode"}],"abstract":[{"type":"text","text":"女性健康模式"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WomenHealthMode"}],"url":"\/documentation\/womenhealth\/womenhealthmode"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/WomenHealthMode/ColumnEncodable-Implementations":{"role":"collectionGroup","title":"ColumnEncodable Implementations","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthMode\/ColumnEncodable-Implementations","kind":"article","type":"topic","url":"\/documentation\/womenhealth\/womenhealthmode\/columnencodable-implementations"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/WomenHealthMode/ColumnCodableBase-Implementations":{"role":"collectionGroup","title":"ColumnCodableBase Implementations","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthMode\/ColumnCodableBase-Implementations","kind":"article","type":"topic","url":"\/documentation\/womenhealth\/womenhealthmode\/columncodablebase-implementations"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/WomenHealthMode/none":{"role":"symbol","title":"WomenHealthMode.none","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"abstract":[{"type":"text","text":"未设置"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthMode\/none","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WomenHealthModeNone"}],"url":"\/documentation\/womenhealth\/womenhealthmode\/none"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/WomenHealthMode/ColumnDecodable-Implementations":{"role":"collectionGroup","title":"ColumnDecodable Implementations","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthMode\/ColumnDecodable-Implementations","kind":"article","type":"topic","url":"\/documentation\/womenhealth\/womenhealthmode\/columndecodable-implementations"},"doc://com.topstep.WomenHealth/9WCDBSwift15ColumnDecodableP":{"type":"unresolvable","title":"WCDBSwift.ColumnDecodable","identifier":"doc:\/\/com.topstep.WomenHealth\/9WCDBSwift15ColumnDecodableP"},"doc://com.topstep.WomenHealth/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.topstep.WomenHealth\/SQ"},"doc://com.topstep.WomenHealth/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.topstep.WomenHealth\/SE"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/WomenHealthMode/menses":{"role":"symbol","title":"WomenHealthMode.menses","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"menses"}],"abstract":[{"type":"text","text":"经期模式"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthMode\/menses","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WomenHealthModeMenses"}],"url":"\/documentation\/womenhealth\/womenhealthmode\/menses"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/WomenHealthMode/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthMode\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/womenhealth\/womenhealthmode\/equatable-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"WomenHealthMode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"WomenHealthMode"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"WomenHealthMode"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthMode\/menses","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthMode\/none","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthMode\/pregnancy","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/WomenHealthMode\/pregnancy_prepare"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"WomenHealthMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthMode~1pregnancy_prepare\/title","value":"WomenHealthModePregnancy_prepare"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthMode~1pregnancy_prepare\/fragments","value":[{"kind":"identifier","text":"WomenHealthModePregnancy_prepare"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthMode~1pregnancy\/title","value":"WomenHealthModePregnancy"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthMode~1pregnancy\/fragments","value":[{"kind":"identifier","text":"WomenHealthModePregnancy"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthMode\/title","value":"WomenHealthMode"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthMode\/fragments","value":[{"kind":"identifier","text":"WomenHealthMode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthMode~1none\/title","value":"WomenHealthModeNone"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthMode~1none\/fragments","value":[{"kind":"identifier","text":"WomenHealthModeNone"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthMode~1menses\/title","value":"WomenHealthModeMenses"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1WomenHealthMode~1menses\/fragments","value":[{"kind":"identifier","text":"WomenHealthModeMenses"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}