{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"colorWith"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"colorKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey","preciseIdentifier":"c:@M@WomenHealth@E@ThemeColorKey","text":"ThemeColorKey"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"traits"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITraitCollection","preciseIdentifier":"c:objc(cs)UITraitCollection"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/womenhealth\/themable\/colorwith(_:_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/womenhealth\/themable\/colorwith(_:_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/Themable\/colorWith(_:_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"根据 colorKey，traits返回皮肤颜色"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"colorWith::"}],"role":"symbol","title":"colorWith(_:_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"colorWith"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ThemeColorKey","preciseIdentifier":"c:@M@WomenHealth@E@ThemeColorKey"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"UITraitCollection","preciseIdentifier":"c:objc(cs)UITraitCollection"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?"}],"symbolKind":"method","externalID":"c:@M@WomenHealth@objc(pl)Themable(im)colorWith::","required":true,"modules":[{"name":"WomenHealth"}]},"hierarchy":{"paths":[["doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/Themable"]]},"references":{"doc://com.topstep.WomenHealth/documentation/WomenHealth/Themable/colorWith(_:_:)":{"navigatorTitle":[{"kind":"identifier","text":"colorWith::"}],"role":"symbol","title":"colorWith(_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"colorWith"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ThemeColorKey","preciseIdentifier":"c:@M@WomenHealth@E@ThemeColorKey"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"UITraitCollection","preciseIdentifier":"c:objc(cs)UITraitCollection"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"根据 colorKey，traits返回皮肤颜色"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/Themable\/colorWith(_:_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/womenhealth\/themable\/colorwith(_:_:)"},"doc://com.topstep.WomenHealth/documentation/WomenHealth":{"role":"collection","title":"WomenHealth","abstract":[],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth","kind":"symbol","type":"topic","url":"\/documentation\/womenhealth"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/Themable":{"role":"symbol","title":"Themable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Themable"}],"abstract":[{"type":"text","text":"皮肤协议"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/Themable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Themable"}],"url":"\/documentation\/womenhealth\/themable"},"doc://com.topstep.WomenHealth/documentation/WomenHealth/ThemeColorKey":{"role":"symbol","title":"ThemeColorKey","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThemeColorKey"}],"abstract":[{"type":"text","text":"颜色Key定义"}],"identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ThemeColorKey"}],"url":"\/documentation\/womenhealth\/themecolorkey"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"colorWith::"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"colorWith::"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"colorWith:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.topstep.WomenHealth\/documentation\/WomenHealth\/ThemeColorKey","preciseIdentifier":"c:@M@WomenHealth@E@ThemeColorKey","text":"ThemeColorKey"},{"kind":"text","text":") "},{"kind":"internalParam","text":"colorKey"},{"kind":"text","text":" "},{"kind":"identifier","text":":"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITraitCollection","preciseIdentifier":"c:objc(cs)UITraitCollection"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"traits"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1Themable~1colorWith(_:_:)\/title","value":"colorWith::"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1Themable~1colorWith(_:_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"colorWith::"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1Themable\/title","value":"Themable"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1Themable\/fragments","value":[{"kind":"identifier","text":"Themable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeColorKey\/title","value":"ThemeColorKey"},{"op":"replace","path":"\/references\/doc:~1~1com.topstep.WomenHealth~1documentation~1WomenHealth~1ThemeColorKey\/fragments","value":[{"kind":"identifier","text":"ThemeColorKey"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}